### PR TITLE
Add an es6 build, synchronize rollup settings between repos.

### PR DESCRIPTION
**Pull request by nsthorat**
- Switch mobilenet to rollup
- Add es6 builds for both models. Set jsnext / module defaults for es6 users.
- Syncs up rollup settings, standalone models depend on "tf" symbol from union package. In practice, this will work with the correct set of "tf" extensions (layers + core).
- Update versions of models to 0.1.0

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/20)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[mobilenet/package.json, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2kl2u7rKLS6Nw_DsP:-LD2kl2u7rKLS6Nw_DsQ:bk9xnzm) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L6)):*
> ```JSON
>   "description": "Pretrained MobileNet in TensorFlow.js",
>   "main": "dist/index.js",
>   "unpkg": "dist/mobilenet.js",
> ```

d3 uses the *.min.js version for unpkg and jsdelivr. we did the same for tfjs-core.
https://github.com/d3/d3/blob/master/package.json#L19

---

*[mobilenet/package.json, line 9 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2lDM32xjPW9MEcRQm:-LD2lDM4-IvY4p9D80OA:b6clysa) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L9)):*
> ```JSON
>   "jsdelivr": "dist/mobilenet.js",
>   "types": "dist/index.d.ts",
>   "repository": {
> ```

missing `module` and `jsnext`

---

*[mobilenet/package.json, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2eybS7Oss09XRXPX4:-LD2eybS7Oss09XRXPX5:b-hudp0p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L20)):*
> ```JSON
>     "babel-core": "^6.26.0",
>     "babel-plugin-transform-runtime": "~6.23.0",
>     "browserify": "~14.5.0",
> ```

remove browserify, browserify-shim, tsify, watchify

---

*[mobilenet/package.json, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2kbrxAb75dP_lfHhR:-LD2kbrxAb75dP_lfHhS:b-39ll45) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L32)):*
> ```JSON
>   },
>   "scripts": {
>     "build": "rm -r dist dist-es6 && tsc --project tsconfig-es5.json && tsc && rollup -c && uglifyjs dist/mobilenet.js -c -m -o dist/mobilenet.min.js",
> ```

use rimraf (npm package) so rm -r works in all OS's.

---

*[mobilenet/tsconfig.json, line 10 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2m3md7LeZmHtENBT4:-LD2m3md7LeZmHtENBT5:becrjn7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/tsconfig.json#L10)):*
> ```JSON
>     "preserveConstEnums": true,
>     "declaration": true,
>     "target": "es5",
> ```

just double-checking that even though you are using es2015 for importing/exporting, the code is still es5 since "target" is es5. Should we just make it es6 completely? If you go with target es6, make sure you explicitly set it back to es5 in tsconfig-es5.json

---

*[mobilenet/tsconfig-es5.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2mv9n--muuaLvo8ie:-LD2mv9n--muuaLvo8if:b-ta1k86) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/tsconfig-es5.json#L2)):*
> ```JSON
> {
>   "extends": "./tsconfig.json",
> ```

nit: `dist/` has config `tsconfig-es5.json`, while `dist-es6/` has config  `tsconfig.json`. might be good to align at some point.

---

*[posenet/package.json, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2mYqC4B41t4QrfIkw:-LD2mYqC4B41t4QrfIkx:b40yq10) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/posenet/package.json#L36)):*
> ```JSON
>     "typescript": "2.7.2",
>     "uglify-js": "~3.0.28",
>     "watchify": "~3.11.0"
> ```

remove watchify

---

*[posenet/package.json, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2mavLEvFPimoirEGB:-LD2mavLEvFPimoirEGC:bil94lk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/posenet/package.json#L39)):*
> ```JSON
>   },
>   "scripts": {
>     "build": "tsc --project tsconfig-es5.json && tsc && rollup -c && uglifyjs dist/posenet.js -c -m -o dist/posenet.min.js",
> ```

to be consistent with mobilenet, missing `rm -r dist dist-es6` before tsc

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-:-LD2nFye9Jdk9nb8ji-f:b-jbsf8z)*

**Comment by nsthorat** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[mobilenet/package.json, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2kl2u7rKLS6Nw_DsP:-LD2oDMB-kNMmq2IDENI:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L6)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

d3 uses the *.min.js version for unpkg and jsdelivr. we did the same for tfjs-core.
https://github.com/d3/d3/blob/master/package.json#L19
</blockquote></details>

Done.

---

*[mobilenet/package.json, line 9 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2lDM32xjPW9MEcRQm:-LD2oEDI0xuEPYm91tE_:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L9)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

missing `module` and `jsnext`
</blockquote></details>

Done.

---

*[mobilenet/package.json, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2eybS7Oss09XRXPX4:-LD2oNqy6BzY7tnuU67i:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L20)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

remove browserify, browserify-shim, tsify, watchify
</blockquote></details>

Done.

---

*[mobilenet/package.json, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2kbrxAb75dP_lfHhR:-LD2oZS_Crru82WQ2_Eb:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/package.json#L32)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

use rimraf (npm package) so rm -r works in all OS's.
</blockquote></details>

Done.

---

*[mobilenet/tsconfig.json, line 10 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2m3md7LeZmHtENBT4:-LD2o_a2CeER23GNnsfF:b-q9yw49) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/tsconfig.json#L10)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

just double-checking that even though you are using es2015 for importing/exporting, the code is still es5 since "target" is es5. Should we just make it es6 completely? If you go with target es6, make sure you explicitly set it back to es5 in tsconfig-es5.json
</blockquote></details>

This is correct :) I did the minimal changes in the es6 folder so rollup would work on union. We can come back to shipping real es6.

---

*[mobilenet/tsconfig-es5.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2mv9n--muuaLvo8ie:-LD2ok3rEBW4bHGmSNlE:br0ng50) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/mobilenet/tsconfig-es5.json#L2)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

nit: `dist/` has config `tsconfig-es5.json`, while `dist-es6/` has config  `tsconfig.json`. might be good to align at some point.
</blockquote></details>

Nice observation :)

What happened was rollup only allows tsconfig.json (no --project flag), and it must be "ES2015". So I ended up making a tsconfig-es5.json, and leaving the dist as is. We can revisit this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/20)*

**Comment by nsthorat** [comment]
Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[posenet/package.json, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2mYqC4B41t4QrfIkw:-LD2q4sB188rLC38-8GC:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/posenet/package.json#L36)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

remove watchify
</blockquote></details>

Done.

---

*[posenet/package.json, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/20#-LD2mavLEvFPimoirEGB:-LD2q5BY96SYVmzU0y_Q:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/912223b9448d78ff2ab58bd970fb7603b4399692/posenet/package.json#L39)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

to be consistent with mobilenet, missing `rm -r dist dist-es6` before tsc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/20)*

**Comment by oveddan** [comment]
@nsthorat I believe this has broken the demos (see issue [323](https://github.com/tensorflow/tfjs/issues/323)).

**Comment by dsmilkov** [comment]
Let me investigate and will get back to you.

**Pull request merged**
