### PR TITLE
Made onboarding for pose-detection a bit better

### PR DESCRIPTION
**Pull request by TheUltragon**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/768)

### CODE REVIEW

**Comment by TheUltragon** [comment]
@googlebot I signed it!

**Comment by TheUltragon** [comment]
Guess I need a bit help. Cant really add another mail to my agreement account, but I use another account for myself on my pc.

**Comment by TheUltragon** [comment]
@googlebot I fixed it.

**Comment by TheUltragon** [comment]
@googlebot I consent.

**Comment by nkolbe96** [comment]
@googlebot I consent.

**Comment by nkolbe96** [comment]
Holy shit this is tiring. I'm like literally both persons, just from different accounts. Would be nice if this process can be made easier for such cases.

**Comment by TheUltragon** [comment]
Definitely agreed ;)

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/768)* status: 0 of 1 approvals obtained (waiting on @TheUltragon)

___
*[pose-detection/demos/README.md, line 42 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7cxiI1WsPpOoRPU5V:-Mg7cxiI1WsPpOoRPU5W:bmhmlx2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/README.md#L42)):*
> ```
> npm install --global yarn
> ```
We don't want to be opinionated about how users install yarn.
___
*[pose-detection/demos/README.md, line 44 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7cbbX9UOQBwD2q1Fc:-Mg7cbbX9UOQBwD2q1Fd:btoiorv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/README.md#L44)):*
> ```
> npm install --global parcel
> npm install --global cross-env
> ```
I don't think you need to manually install these dependencies, as long as you run `yarn` at the top tfjs-models level and in the demo folder, it will install the dependencies for you. The only think you need to install yourself is yarn.
___
*[pose-detection/demos/live_video/package.json, line 12 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7d5PB5ul0kjAciwdl:-Mg7d5PC1t8paHfbMnRw:b-k0jhda) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/live_video/package.json#L12)):*
> ```
> "^0.0.4",
> ```
We symlink the dist so that it can pick up the head of the code, which is not released.
___
*[pose-detection/demos/live_video/src/index.js, line 156 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7dRDEAdU1ZtlRA7VR:-Mg7dRDF5lqccCcRUnrb:bs7ni2h) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/live_video/src/index.js#L156)):*
> ```
> Setting blazepose as default. 
> ```
I don't think any default is set.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 64 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7da-A2PFFjNHQ3APC:-Mg7da-A2PFFjNHQ3APD:b-jok84k) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/src/blazepose_tfjs/README.md#L64)):*
> ```
> // 
> ```
This is needed.

**Comment by TheUltragon** [comment]
> 
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/768)_ status: 0 of 1 approvals obtained (waiting on @TheUltragon)
> 
> _[pose-detection/demos/README.md, line 42 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7cxiI1WsPpOoRPU5V:-Mg7cxiI1WsPpOoRPU5W:bmhmlx2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/README.md#L42)):_
> 
> > ```
> > npm install --global yarn
> > ```
> 
> We don't want to be opinionated about how users install yarn.
Can totally understand this, but a newcomer like me has no idea how to install yarn, as they have never heard about stuff like npm and such. Therefore, atleast a hint how to actually do it would be needed imho. 

> 
> _[pose-detection/demos/README.md, line 44 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7cbbX9UOQBwD2q1Fc:-Mg7cbbX9UOQBwD2q1Fd:btoiorv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/README.md#L44)):_
> 
> > ```
> > npm install --global parcel
> > npm install --global cross-env
> > ```
> 
> I don't think you need to manually install these dependencies, as long as you run `yarn` at the top tfjs-models level and in the demo folder, it will install the dependencies for you. The only think you need to install yourself is yarn.

Yeah, this was probably caused by the next issue that I changed, being that yarn didnt run at all through all the commands as it failed at the "symlink of the dist" step. Therefore my next comment would be....

> 
> _[pose-detection/demos/live_video/package.json, line 12 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7d5PB5ul0kjAciwdl:-Mg7d5PC1t8paHfbMnRw:b-k0jhda) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/live_video/package.json#L12)):_
> 
> > ```
> > "^0.0.4",
> > ```
> 
> We symlink the dist so that it can pick up the head of the code, which is not released.

Well it didnt work when I copied the code into my own project, nor did it work as I tested it in the fork. So either fix the symlink and give a clear warning to newcomers, that they have to readjust it on copy or keep it as I suggested.

> 
> _[pose-detection/demos/live_video/src/index.js, line 156 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7dRDEAdU1ZtlRA7VR:-Mg7dRDF5lqccCcRUnrb:bs7ni2h) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/demos/live_video/src/index.js#L156)):_
> 
> > ```
> > Setting blazepose as default. 
> > ```
> 
> I don't think any default is set.

That's why I added this line. Again, newcomers perspective: "Oh, the program runs, but as soon as I open the website, I get a notification telling me that something isnt working, without any apparent fix and nothing else happening. Must be broken". This scenario (which happened to me) I want to prevent for future people.

> 
> _[pose-detection/src/blazepose_tfjs/README.md, line 64 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/768#-Mg7da-A2PFFjNHQ3APC:-Mg7da-A2PFFjNHQ3APD:b-jok84k) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c24aab368774b426e772e0b527c23c79bf5b4a8/pose-detection/src/blazepose_tfjs/README.md#L64)):_
> 
> > ```
> > // 
> > ```
> 
> This is needed.

Well, I didnt include this because it just worked for me the way it was setup.


For future reference, please look at my issue that primed all of this here: https://github.com/tensorflow/tfjs/issues/5371

**Comment by TheUltragon** [comment]
Ok. Will reiterate on my changes once I find the time to and request further review then.

**Review by soffieprincess02 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/768)* status: 0 of 1 approvals obtained (waiting on @lina128 and @TheUltragon)

**Comment by TheUltragon** [comment]
@soffieprincess02 sorry, but what should this comment say? A little confused here, probably because I'm not familiar with the review process

**Comment by jenperson** [comment]
Closing this PR since the requested changes were not made.

**Pull request closed without merging**
