### PR TITLE
Add travis / browserstack testing.

### PR DESCRIPTION
**Pull request by nsthorat**
This PR:
- Adds travis testing for models. All tests run in travis via Node with a CPU backend. WebGL tests are not necessary (and we don't have the complexity of dealing with browserstack).
- Makes tests hermetic. PoseNet now doesn't actually make a request to GCP for MobileNet weights, MobileNet.predict is mocked.
- Allow PoseNet to also take a Tensor as an input. This is useful for the API and also lets us use it in Node.
- Adds a small test util to kick off jasmine tests. It needs a "jasmine_util" which is bound to a particular tfjs-core module.
- Add KNN Classifier test.

Fixes https://github.com/tensorflow/tfjs/issues/450

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/38)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[posenet/src/posenet_model.ts, line 296 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LF_Lb9U53dQyMV4B0hz:-LF_L4zN3FYN4P1uESn6:b-7ru3ws) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/posenet/src/posenet_model.ts#L296)):*
> ```XML
> }
> 
> export const mobilenetLoader = {
> ```

this is for testing purposes (jasmine needs an object + method on object)

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/38)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice!

---

Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[package.json, line 10 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcQfGXDGcEsWw6Lrfy:-LFcQfGXDGcEsWw6Lrfz:b-ljl2ot) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/package.json#L10)):*
> ```JSON
>   },
>   "devDependencies": {
>     "@types/node": "^10.3.4",
> ```

s/^/~/

---

*[presubmit.ts, line 41 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcQz6E8sDvPi_MQtrW:-LFcQz6E8sDvPi_MQtrX:b-fwwu35) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/presubmit.ts#L41)):*
> ```XML
>     console.log(`************ Testing ${dir} ************`);
>     shell.exec('yarn test');
>   }
> ```

else warn that no 'script.test' was found in $dir/package.json.

It's good to have that warning to remind us to add tests for new models

---

*[knn-classifier/package.json, line 24 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcRDsW-GJbFflw-23c:-LFcRDsW-GJbFflw-23d:b-ljl2ot) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/package.json#L24)):*
> ```JSON
>     "babel-plugin-transform-runtime": "~6.23.0",
>     "jasmine": "~3.1.0",
>     "jasmine-core": "^3.1.0",
> ```

s/^/~/

---

*[knn-classifier/src/index_test.ts, line 42 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcSCg2EJ_s-dsi-B0A:-LFcSCg2EJ_s-dsi-B0B:b1g1vpi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/src/index_test.ts#L42)):*
> ```XML
>     await classifier.predictClass(x0);
> 
>     const tensors = tf.memory().numTensors;
> ```

s/tensors/numTensorsBefore/

---

*[mobilenet/package.json, line 31 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcSTuQ3PnbMJ4DsW4V:-LFcSTuQ3PnbMJ4DsW4W:bni5i31) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/mobilenet/package.json#L31)):*
> ```JSON
>   },
>   "scripts": {
>     "build": "rimraf dist && tsc && rollup -c",
> ```

curious as to why mobilenet didn't get any unit tests?

---

*[posenet/src/posenet_model.ts, line 154 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcTCtQCZHMpBHfT9Td:-LFcTCtR22eYp_I2wigX:b490pbe) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/posenet/src/posenet_model.ts#L154)):*
> ```XML
>     assertValidScaleFactor(imageScaleFactor);
> 
>     const [height, width] = input instanceof tf.Tensor ?
> ```

fyi, I'll investigate why this instanceof fails in nodejs when user code uses good-old require('...') imports (see why people get duplication of imports)

---

*[posenet/src/posenet_test.ts, line 28 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcU_gzDxJHUaRpOJ-q:-LFcU_gzDxJHUaRpOJ-r:b11mgcc) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/posenet/src/posenet_test.ts#L28)):*
> ```XML
>     // Mock out the actual load so we don't make network requests in the unit
>     // test.
>     spyOn(posenetModel.mobilenetLoader, 'load').and.callFake(() => {
> ```

ha, so you couldn't spyOn(posenetModel, 'load') , is that right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-:-LFcUs513KN1TjdI5jP8:b-pfdznz)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[knn-classifier/package.json, line 39 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFctHG7-lRDw-s07RyN:-LFctHG7-lRDw-s07RyO:bgxsj1v) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/package.json#L39)):*
> ```
> test"
> ```

Great!

But can you update the README files so developers will know how to run the tests?

---

*[knn-classifier/src/index_test.ts, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcstpmAjZYwf6g0bgo:-LFcstpmAjZYwf6g0bgp:byt5yz6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/src/index_test.ts#L23)):*
> ```
> it('simple nearest neighbors', async () => {
> ```

Maybe add some test for error conditions, such as 
1) calling predictClass() before calling addExample
2) calling predictClass() when there is only one class.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-:-LFctO3K3Ro5wlAZrKrC:b-jbsf8z)*

**Comment by nsthorat** [comment]
Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[package.json, line 10 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcQfGXDGcEsWw6Lrfy:-LFcmZALBoqKOfxQcZwm:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/package.json#L10)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

s/^/~/
</blockquote></details>

Done

---

*[presubmit.ts, line 41 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcQz6E8sDvPi_MQtrW:-LFcmtYfDEsXIH_Zj-pT:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/presubmit.ts#L41)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

else warn that no 'script.test' was found in $dir/package.json.

It's good to have that warning to remind us to add tests for new models
</blockquote></details>

Done.

---

*[knn-classifier/package.json, line 24 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcRDsW-GJbFflw-23c:-LFcmxoF4fskeV9kolRJ:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/package.json#L24)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

s/^/~/
</blockquote></details>

Done

---

*[knn-classifier/package.json, line 39 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFctHG7-lRDw-s07RyN:-LFcvnAe01KB9JRW2L__:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/package.json#L39)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> test"
> ```

Great!

But can you update the README files so developers will know how to run the tests?
</blockquote></details>

Done.

---

*[knn-classifier/src/index_test.ts, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcstpmAjZYwf6g0bgo:-LFcyAtj5kaMyHRcuC4m:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/src/index_test.ts#L23)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> it('simple nearest neighbors', async () => {
> ```

Maybe add some test for error conditions, such as 
1) calling predictClass() before calling addExample
2) calling predictClass() when there is only one class.
</blockquote></details>

Done.

---

*[knn-classifier/src/index_test.ts, line 42 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/38#-LFcSCg2EJ_s-dsi-B0A:-LFcnEW57cvdOauvaxaY:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6e4b702a033b21a8b6389a63006941b266c34fd7/knn-classifier/src/index_test.ts#L42)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

s/tensors/numTensorsBefore/
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/38)*

**Comment by asadovsky** [comment]
Hi,
Would it be possible to push a new release that includes these changes? I ask b/c in my code I want to pass a tf.Tensor as input to estimateSinglePose. Thanks!

**Comment by nsthorat** [comment]
@asadovsky just released PoseNet 0.1.3 with this change. Let me know if you have issues.

**Pull request merged**
