### PR TITLE
Face detection model npm release

### PR DESCRIPTION
**Pull request by fengwuyao**
Update the dependency for face detection model. Aiming to publish new npm release.

### CODE REVIEW

**Comment by mattsoulanille** [comment]
Should we also update the TFJS versions for the [demos](https://github.com/tensorflow/tfjs-models/blob/master/face-detection/demos/live_video/package.json) in this PR, or will that be a different PR?

**Comment by fengwuyao** [comment]
Sg, updated the TFJS version for demos.

**Comment by Linchenn** [comment]
Just tested the live demo and it works on my mac. LGTM! Thanks!

**Review by Linchenn — APPROVED** [review]

**Review by mattsoulanille — APPROVED** [review]
LGTM

**Pull request merged**
