### PR TITLE
[docs]: Reformat the README into a table with installation instructions and links to demos

### PR DESCRIPTION
**Pull request by sdll**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/216)

### CODE REVIEW

**Comment by sdll** [comment]
@dsmilkov, I have reformatted the README into a table of models, including the logos and links to demos.

**Comment by dsmilkov** [comment]
Awesome. Can you make the icons much smaller (something like 50-75px)

**Comment by sdll** [comment]
@dsmilkov, done. Alas, icons become illegible, and GitHub markdown rendering does not seem to respect the nowrap directive.

**Comment by dsmilkov** [comment]
Oh, that preview is not good (lots of margin around the icons). Nevermind, can you remove the icons? Sorry for going back and forth on this. Otherwise, this PR is good to go! Really nice work! Thank you!

**Comment by sdll** [comment]
@dsmilkov, done!

**Comment by dsmilkov** [comment]
Fantastic!

**Pull request merged**
