### PR TITLE
[pose-detection]Add README.md to BlazePoseTfjs

### PR DESCRIPTION
**Pull request by lina128**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/720)

### CODE REVIEW

**Review by mhays-google — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/720)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[pose-detection/src/blazepose_tfjs/README.md, line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8CJy9aqQlwfknHMj:-M_g8CJy9aqQlwfknHMk:bixaoww) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L52)):*
> ```Markdown
> ```
> export interface BlazePoseModelConfig extends ModelConfig {
>   // Defaults to 'mediapipe' if not provided.
> ```

Does it still?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/720)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mhays-google and @pyu10055)

___
*[pose-detection/src/blazepose_tfjs/README.md, line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8CJy9aqQlwfknHMj:-M_g8QAt6ELmWVwrhfdP:b-vv37km) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L52)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

Does it still?
</blockquote></details>

Nice catch! Removed.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/720)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @mhays-google)

___
*[pose-detection/src/blazepose_tfjs/README.md, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g87aZCRMBaV5bfBWm:-M_g87aZCRMBaV5bfBWn:b-tvhg7v) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L3)):*
> ```Markdown
> # BlazePose
> 
> BlazePoseTfjs uses TF.js runtime to execute the model, the preprocessing and postprocessing steps.
> ```

Should it be separated into two works? BlazePose TFJS ?
___
*[pose-detection/src/blazepose_tfjs/README.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8HMU5it0lWW9DG5t:-M_g8HMU5it0lWW9DG5u:bwp6115) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L6)):*
> ```Markdown
> Three models are offered.
> 
> * 'lite' - our smallest model which trades footprint for accuracy.
> ```

our smallest model that is less accurate but with minimal memory footprint
___
*[pose-detection/src/blazepose_tfjs/README.md, line 8 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8XjP0agdo5a5JD70:-M_g8XjP0agdo5a5JD71:b-irs9pq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L8)):*
> ```Markdown
> * 'lite' - our smallest model which trades footprint for accuracy.
> * 'heavy' - our largest model intended for high accuracy, regardless of size.
> * 'full' - A middle ground between Lite and Heavy.
> ```

A medium model that balances performance and accuracy. 
___
*[pose-detection/src/blazepose_tfjs/README.md, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8rXr5jn9EeX1vuCA:-M_g8rXr5jn9EeX1vuCB:b-kkdi38) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L38)):*
> ```Markdown
> // Register one of the TF.js backends.
> import '@tensorflow/tfjs-backend-webgl';
> // import '@tensorflow/tfjs-backend-wasm';
> ```

add comment like: if you prefer to use TFJS WASM backend please swap with the following line.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g94dX6EAzZ3SBzs1d:-M_g94dX6EAzZ3SBzs1e:b-h7wl0f) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L53)):*
> ```Markdown
> export interface BlazePoseModelConfig extends ModelConfig {
>   // Defaults to 'mediapipe' if not provided.
>   runtime?: 'mediapipe'|'tfjs';
> ```

remove the `?` if it is a required field now.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g9EP4-90BryPxnOmK:-M_g9EP4-90BryPxnOmL:b-7lvjlz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L73)):*
> ```Markdown
> 
> Now you can use the detector to detect poses. The `estimatePoses` method
> accepts both image and video in many formats, including: `tf.Tensor3D`,
> ```

either image or video

**Review by lina128 — COMMENTED** [review]
Thank you Ping for the detailed review, I addressed your comments, please take another look!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-:-M_gny0T1rBLokoADtWn:b-wi6xij)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mhays-google and @pyu10055)

___
*[pose-detection/src/blazepose_tfjs/README.md, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g87aZCRMBaV5bfBWm:-M_gnBdm7jnkOWOa1Joo:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Should it be separated into two works? BlazePose TFJS ?
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8HMU5it0lWW9DG5t:-M_gnQxnCZQ1Pa1sWd61:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L6)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

our smallest model that is less accurate but with minimal memory footprint
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 8 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8XjP0agdo5a5JD70:-M_gnW8w3ZVoSc3ErJ3n:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L8)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

A medium model that balances performance and accuracy. 
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g8rXr5jn9EeX1vuCA:-M_gna2u6GOhsqX7vBCU:b-74xpi0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L38)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

add comment like: if you prefer to use TFJS WASM backend please swap with the following line.
</blockquote></details>

Removed, because WASM doesn't work for BlazePose yet.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g94dX6EAzZ3SBzs1d:-M_gngrf0-BSV9D7PO45:b-effe2d) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

remove the `?` if it is a required field now.
</blockquote></details>

Nice catch! In the API, ? is removed already.
___
*[pose-detection/src/blazepose_tfjs/README.md, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/720#-M_g9EP4-90BryPxnOmK:-M_gnqNcDNXjpE5i1UxF:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3cebc73f98be528aa6c94244d7c259225b94726e/pose-detection/src/blazepose_tfjs/README.md#L73)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

either image or video
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]

**Pull request merged**
