### PR TITLE
[pose-detection] Add README

### PR DESCRIPTION
**Pull request by lina128**
This is a shared README for the pose-detection API. Model specific README should in their own folders.
See how it looks here: https://github.com/tensorflow/tfjs-models/blob/961d9294ab8c14f8c859fd86407f9508e3daccae/pose-detection/README.md

Note: This is the README that users will see when they enter the pose-detection page on GitHub. It provides general information about usage, provide demo links and showcase some animated GIFs (to add). In the future, we can add a gallery, which showcase applications created using this API.

The following information should go into the README in each model's folder: (1) Model specific usage such as configs (2) Model specific information such as model description (3) Other demo links, gallery, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)

### CODE REVIEW

**Review by ronnyvotel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, and @yuhuichen1015)

___
*[pose-detection/README.md, line 91 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKPRjy4sPSY7_o12Fa:-MZKPRjy4sPSY7_o12Fb:btmtus8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L91)):*
> ```
> parameter.
> ```
Currently, only PoseNet supports multi-pose estimation.
___
*[pose-detection/README.md, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKQKW6118ekScuhiIH:-MZKPkDz6erNIVg-QkLE:b-cl8off) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L98)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> `poses` contains a list of poses, how many poses is returned is controlled by
> the `maxPose` option of the `EstimationConfig` and the model's own limitation.
> Currently, only PoseNet supports multi-pose estimation. If the model cannot
detect any pose, it will return an empty array.
> ```
</details>

I would update all this to:
The returned `poses` list contains detected poses for each individual in the image. For single-person models, there will only be one element in the list. If the model cannot detect any people, the list will be empty.
___
*[pose-detection/README.md, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKQsRN5zTm2ilECxu0:-MZKQsRN5zTm2ilECxu1:bf8ribz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L109)):*
> ```
> rendered
> ```
rendered -> used
___
*[pose-detection/README.md, line 110 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKQwBLEzYH9VEcMz5K:-MZKQwBLEzYH9VEcMz5L:byyzxma) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L110)):*
> ```
> You may test where is the threshold based on your application.
> ```
Each application may require a custom confidence threshold. For applications that require high precision, we recommend a larger confidence value. Conversely, applications that require high recall may choose to lower the threshold. The confidence values are not calibrated between models, and therefore setting a proper confidence threshold may involve some experimentation.
___
*[pose-detection/README.md, line 137 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKRjCe3BG0YWAmAgFV:-MZKRjCe3BG0YWAmAgFW:bmrh0x) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L137)):*
> ```
>   \
> ```
remove
___
*[pose-detection/README.md, line 175 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKRmqrARLdrNRKFJ24:-MZKRmqrARLdrNRKFJ25:bbgd7t7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L175)):*
> ```
>  \
> ```
remove
___
*[pose-detection/README.md, line 182 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKRykf9nUcuHEZZ3gD:-MZKRykf9nUcuHEZZ3gE:b-2uq5ng) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L182)):*
> ```
> https://github.com/tensorflow/tfjs-models/tree/master/pose-detection
> ```
want to link to the demo folder directly?

**Review by yuhuichen1015 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, and @pyu10055)

___
*[pose-detection/README.md, line 78 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKXjx-2yiwQNi_Zzg2:-MZKXjx-2yiwQNi_Zzg3:bize9qd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L78)):*
> ```Markdown
> 
> ```javascript
> const detector = await poseDetection.createDetector(model);
> ```

Would it be easier for the readers to understand if we provide the code showing what "model" is? I understand it's in the description above, but just thinking it'll be more straightforward to provide a "copy-pastible" example.
___
*[pose-detection/README.md, line 105 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZK_AsK4zYFd_Vz_lLB:-MZK_AsK4zYFd_Vz_lLC:b8ne5am) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L105)):*
> ```Markdown
> For each pose, it contains a confidence score of the pose and an array of
> keypoints. The PoseNet and MoveNet both return 17 keypoints. The
> MediapipeBlazepose returns 33 keypoints. Each keypoint contains `x`, `y`,
> ```

Should we explain what 'x' and 'y' represent? e.g. "normalized" vs "absolute" cooredinates?

**Review by lina128 — COMMENTED** [review]
Hi @yuhuichen1015 and @ronnyvotel , thank you for your great and detailed review! I've addressed your comments, please take another look.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-:-MZKeiEG4gZogjw9JyJN:b-oqvxku)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, @ronnyvotel, and @yuhuichen1015)

___
*[pose-detection/README.md, line 91 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKPRjy4sPSY7_o12Fa:-MZKYGKRBItPiMqLQMos:bfhoj1a) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L91)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> parameter.
> ```
Currently, only PoseNet supports multi-pose estimation.
</blockquote></details>

Moved the description to the next paragraph.
___
*[pose-detection/README.md, line 105 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZK_AsK4zYFd_Vz_lLB:-MZKdxU_1fezD0yUFd9M:bcvjgzp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L105)):*
<details><summary><i>Previously, yuhuichen1015 (Yu-Hui Chen) wrote…</i></summary><blockquote>

Should we explain what 'x' and 'y' represent? e.g. "normalized" vs "absolute" cooredinates?
</blockquote></details>

Good idea. Done.
___
*[pose-detection/README.md, line 110 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKQwBLEzYH9VEcMz5K:-MZKeLBp7tv0jM1AUQ_t:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L110)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> You may test where is the threshold based on your application.
> ```
Each application may require a custom confidence threshold. For applications that require high precision, we recommend a larger confidence value. Conversely, applications that require high recall may choose to lower the threshold. The confidence values are not calibrated between models, and therefore setting a proper confidence threshold may involve some experimentation.
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 137 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKRjCe3BG0YWAmAgFV:-MZKeO-6Da2cGdjR0f9p:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L137)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
>   \
> ```
remove
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 175 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKRmqrARLdrNRKFJ24:-MZKeOak-SvXgMTpskAG:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L175)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
>  \
> ```
remove
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 182 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKRykf9nUcuHEZZ3gD:-MZKeVRy7eQ91YI3HOrV:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L182)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> https://github.com/tensorflow/tfjs-models/tree/master/pose-detection
> ```
want to link to the demo folder directly?
</blockquote></details>

Done.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @ronnyvotel, and @yuhuichen1015)

___
*[pose-detection/README.md, line 44 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKirlbC2F1J3rDOUKy:-MZKirlbC2F1J3rDOUKz:bew0sk9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L44)):*
> ```Markdown
> 
> <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
> 
> ```

have we verified all models run on wasm backend?
___
*[pose-detection/README.md, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKj7ka-yxR-8k3l1-x:-MZKj7ka-yxR-8k3l1-y:b-cxa7at) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L68)):*
> ```Markdown
> // Register one of the TF.js backends.
> import '@tensorflow/tfjs-backend-webgl';
> // import '@tensorflow/tfjs-backend-wasm';
> ```

does the user need to call `await tf.setBackend('wasm')`?
___
*[pose-detection/README.md, line 87 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKja-Y7jKj-uNR6FrA:-MZKja-Y7jKj-uNR6FrB:b7o70aq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L87)):*
> ```Markdown
> 
> ### Pose Estimation
> Once the detector is ready, you can start using it to detect poses. The
> ```

since you have used `await` in the earlier example, I don't think we need to stress that once the detector is ready, since you can start calling detector.estimatePoses right after.
___
*[pose-detection/README.md, line 95 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKkXWZ4XVKRuLl52KB:-MZKkXWZ4XVKRuLl52KC:b-4o674k) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L95)):*
> ```Markdown
> 
> ```javascript
> const poses = await detector.estimatePoses(image);
> ```

maybe good to provide an example of the output, so users has a visual on the things discussed in the following paragraph.

**Review by ardoerlemans — APPROVED** [review]
Looks good! Just a few minor comments.

**Review by lina128 — COMMENTED** [review]
Hi @pyu10055 and @ardoerlemans , thank you for your great feedback! I've addressed your comments, please take another look. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-:-MZKqt0L73cKLIR5TWqJ:bijzcrp)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, @ronnyvotel, and @yuhuichen1015)

___
*[pose-detection/README.md, line 78 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKXjx-2yiwQNi_Zzg2:-MZKp1Rl5bWnwxmNkl0Z:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L78)):*
<details><summary><i>Previously, yuhuichen1015 (Yu-Hui Chen) wrote…</i></summary><blockquote>

Would it be easier for the readers to understand if we provide the code showing what "model" is? I understand it's in the description above, but just thinking it'll be more straightforward to provide a "copy-pastible" example.
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKQsRN5zTm2ilECxu0:-MZKqYlb3OIraNlexNPt:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ed986de348c4680eee867ed679277a482d760a86/pose-detection/README.md#L109)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> rendered
> ```
rendered -> used
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 44 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKirlbC2F1J3rDOUKy:-MZKnz8e9idbaQqkYM8T:bt8jvxz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L44)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

have we verified all models run on wasm backend?
</blockquote></details>

Not yet. Removed for now.
___
*[pose-detection/README.md, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKj7ka-yxR-8k3l1-x:-MZKoYEm2_kVnA1iiS2J:b-csll6c) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L68)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does the user need to call `await tf.setBackend('wasm')`?
</blockquote></details>

I think the backend registers automatically. But removed wasm for now.
___
*[pose-detection/README.md, line 84 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKDo-W_brJAp617Kcv-r2-84:-MZKp4qU4TX5Ke2-PgRC:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L84)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

you are interested in.
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 87 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKja-Y7jKj-uNR6FrA:-MZKpAPc4dFOPkpv9R1q:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L87)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

since you have used `await` in the earlier example, I don't think we need to stress that once the detector is ready, since you can start calling detector.estimatePoses right after.
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 95 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKkXWZ4XVKRuLl52KB:-MZKpxjb6nwJ4f3Lk_Lv:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L95)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

maybe good to provide an example of the output, so users has a visual on the things discussed in the following paragraph.
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 103 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKDo-W_brJAp617Kcv-r2-103:-MZKq1PACjw6SbgFnhxu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L103)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

how many poses are returned
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 104 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKDo-W_brJAp617Kcv-r2-104:-MZKq9-N7nOH6Sa3veOl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L104)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

maxPoses
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 106 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKDo-W_brJAp617Kcv-r2-106:-MZKqLA7DSDhjXtkJBWU:bss4a2b) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L106)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

It looks like this paragraph is a copy of the one above?
</blockquote></details>

Removed.
___
*[pose-detection/README.md, line 109 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKDo-W_brJAp617Kcv-r2-109:-MZKqTXL-N2VbjD4CWCB:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L109)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

I would use either 'The PoseNet model' or just 'PoseNet' (similar for MoveNet and MediapipeBlazepose).
</blockquote></details>

Done.
___
*[pose-detection/README.md, line 113 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-MZKDo-W_brJAp617Kcv-r2-113:-MZKqXbx-YHgkkauFqFK:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fd7b14bf3fdba0079bdb01043d2b09456fc5a00c/pose-detection/README.md#L113)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

the actual keypoint position
</blockquote></details>

Done.

**Review by yuhuichen1015 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, @ronnyvotel, and @yuhuichen1015)

**Review by yuhuichen1015 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, @ronnyvotel, and @yuhuichen1015)

**Review by pyu10055 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675#-:-MZL6uw-119W4Pi7Dk3r:bb6ywmx)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, @ronnyvotel, and @yuhuichen1015)

**Review by ronnyvotel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/675)* status: :shipit: complete! 4 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, @pyu10055, and @yuhuichen1015)

**Pull request merged**
