### PR TITLE
Pose-detection version update

### PR DESCRIPTION
**Pull request by fengwuyao**
Update TFJS version for pose-detection, live_videos and upload_videos.
Fix the tests.

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]
LGTM

**Review by Linchenn — APPROVED** [review]
LGTM, thanks!

**Comment by Kidus-berhanu** [comment]
after the new update we are getting this error on Pose detection, it was working just fine before the update
any suggestion on how to fix the error?
(index):26  Error during setup:  TypeError: Cannot read properties of undefined (reading 'loadGraphModel')
    at pose-detection@latest:17:39324
    at pose-detection@latest:17:2398
    at Object.next (pose-detection@latest:17:2503)
    at pose-detection@latest:17:1440
    at new Promise (<anonymous>)
    at u (pose-detection@latest:17:1185)
    at _t (pose-detection@latest:17:38275)
    at Object.<anonymous> (pose-detection@latest:17:71542)
    at pose-detection@latest:17:2398
    at Object.next (pose-detection@latest:17:2503)
    
    
    this are the scripts we are using
     <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@4.10.0"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@4.10.0"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl@4.10.0"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/pose-detection@latest"></script>

<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/handpose"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@4.10.0"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu@4.10.0"></script>

**Comment by fengwuyao** [comment]
Hi @Kidus-berhanu!
Thanks for pointing this out. Feel free to try with the newest npm package @version 2.1.2. And let us know if the error still persists.

**Pull request merged**
