### PR TITLE
Model playground initial checkin

### PR DESCRIPTION
**Pull request by jinjingforever**
This PR sets up the angular app and the basic code structure for model playground. It has the minimum implementations that hook up the basic interaction between ngrx store and UI components, url handling, deep linking, and responsive UI. Specifically:

- An angular app generated from the angular CLI with scss. A basic material theme is set up.
- Code structure under `src/app` (The rest are mostly generated by CLI):
  - `app`: the root app component.
  - `common`: common types and utilities.
  - `components`: UI components. For now, I added a minimum navigation tree.
  - `models`: all `ModelItem` related classes. Each `TaskModel` in the task API will have a class here that extends `ModelItem`. For now, I added 3 classes with id only.
  -  `services`: injectable angular services. Each service is in charge of one aspect of the app. For now, I added a `ModelItemService` that handles model item related tasks.
  - `store`: ngrx store related, including the main app state and its related actions and reducers. The store manages all data/states in the app, such as model items, routing data (url and query string), and media queries (for responsive UI). See how things are set up in `app.module.ts`.
- This PR produces a working app ([demo](https://storage.googleapis.com/model-playground-demo/2021-07-08-15-13-53/index.html))
  - Three model items are shown in the tree (not grouped yet):
  - You can select an item from the tree and the selected item's id will be shown in the main panel.
  - The browser's history controls should work as expected. You can test this by selecting some items and click "go back" or "go forward" in browser.  
  - Deep linking should work as expected as well. For example, [this link](https://storage.googleapis.com/model-playground-demo/2021-07-08-15-13-53/index.html?id=cocossd_tfjs) should select "cocossd_tfjs". (note: due to the limitation of Google storage bucket, you cannot copy the link directly from the browser and use it as the deep link. You will have to add "index.html" manually to the link. This will be fixed in a real web hosting environment)
  - Responsive UI is also set up through the store. See the usage of `NgrxMediaqueriesModule` in `app.module.ts` for setup, and the usage of `NgrxMediaQueriesFacade` in `app.component.ts` to get updates for whether the current device is mobile-phone or not. 
- This PR also hooks up model-playground with cloud build. Since angular uses `ng test` for testing and it doesn't allow to pass options directly to karma config, I had to create a separate karma-ci.conf.js for running tests in browserstack from CI. 

Please take your time and feel free to let me know if you need to have a chat to go through the code. Thank you!

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/759)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you Jing, nice setup and clean design. For mobile device detection, is it typical to use just the screen size, can it use user-agent string?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-:-MeXLUZ67WlRIUEasJ9n:b-76uw7y)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[model-playground/karma-ci.conf.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXGfNu16yHi_Xq-kEy:-MeXGfNv-hJDxJBi6wSo:b-qszjta) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/karma-ci.conf.js#L1)):*
> ```JavaScript
> // Karma configuration file, see link for more information
> ```

should this file contain the license header? 
___
*[model-playground/karma.conf.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXGrYa9SYx6b9GETlh:-MeXGrYa9SYx6b9GETli:b-u79ueq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/karma.conf.js#L1)):*
> ```JavaScript
> // Karma configuration file, see link for more information
> ```

license header?
___
*[model-playground/tsconfig.json, line 5 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXH9Ec4_tWrAntiTgl:-MeXH9Ec4_tWrAntiTgm:bumonmd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.json#L5)):*
> ```jsonc
>   "compilerOptions": {
>     "baseUrl": "./",
>     "outDir": "./dist/out-tsc",
> ```

should we stick with ./dist convention?
___
*[model-playground/tsconfig.app.json, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXHLwI546us6LIztCx:-MeXHLwI546us6LIztCy:b-9g840u) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.app.json#L4)):*
> ```JSON
>   "extends": "./tsconfig.json",
>   "compilerOptions": {
>     "outDir": "./out-tsc/app",
> ```

dist/app?
___
*[model-playground/tsconfig.spec.json, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXHSaNCx6mmWpHZLhA:-MeXHSaNCx6mmWpHZLhB:bt60lst) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.spec.json#L4)):*
> ```JSON
>   "extends": "./tsconfig.json",
>   "compilerOptions": {
>     "outDir": "./out-tsc/spec",
> ```

./dist/spec ?
___
*[model-playground/scripts/deploy-dev.sh, line 8 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXHbmg5wotV1SJQLpt:-MeXHbmg5wotV1SJQLpu:by0x6n4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/scripts/deploy-dev.sh#L8)):*
> ```Shell
> 
> # Use date+time as an unique identifier for the current demo.
> datetime=$(date '+%Y-%m-%d-%H-%M-%S')
> ```

is this temporary and for development purpose? It might need to be based on the package version for production deployment.
___
*[model-playground/src/polyfills.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXI9k0-2YcxFp__tjk:-MeXI9k0-2YcxFp__tjl:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/src/polyfills.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2019 Google LLC. All Rights Reserved.
> ```

2021
___
*[model-playground/src/app/app/app.component.html, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXIY0U1w818Ub-VSRu:-MeXIY0U1w818Ub-VSRv:b-ijhsg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/src/app/app/app.component.html#L18)):*
> ```HTML
> 
> <div class="container">
>   <navigation-tree *ngIf="!(isMobilePhone$ | async)"></navigation-tree>
> ```

mobile phone will not contain the nav tree, will it become a drop down menu button?

**Review by jinjingforever — COMMENTED** [review]
Thanks! The screen size seems to be a more direct way to target when doing responsive design. We don't need to figure out what *devices* users are using. We only care about the size of the screen. So it can handle situations where users resize a browser window to a small area even on a desktop machine. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-:-MeaWEZB1IB0ZXW1krP1:b-3i87gc)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[model-playground/karma-ci.conf.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXGfNu16yHi_Xq-kEy:-Mea4Mh73UOML_UpGdNm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/karma-ci.conf.js#L1)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this file contain the license header? 
</blockquote></details>

Done.
___
*[model-playground/karma.conf.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXGrYa9SYx6b9GETlh:-Mea4N5H6HmFl6lr07cr:bs7wup9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/karma.conf.js#L1)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

license header?
</blockquote></details>

Done.t
___
*[model-playground/tsconfig.json, line 5 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXH9Ec4_tWrAntiTgl:-Mea5GjpCrRZvX-3eM91:b-rl3jk7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.json#L5)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we stick with ./dist convention?
</blockquote></details>

Nice catch. Looks like `outDir` here is not actually used (see [here](https://stackoverflow.com/questions/49621628/what-happens-to-the-outdir-in-tsconfig-json-for-angular-projects/49621767)). The output location is specified in angular.json. I changed that to `dist` now. Before it was `dist/model-playground`. Thanks! 
___
*[model-playground/tsconfig.app.json, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXHLwI546us6LIztCx:-Mea5pKO0ZOncHqsoMyc:b-otilcs) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.app.json#L4)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

dist/app?
</blockquote></details>

See comment above.
___
*[model-playground/tsconfig.spec.json, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXHSaNCx6mmWpHZLhA:-Mea5wLV1q0XZCgd_zuG:bsvoyq3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.spec.json#L4)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

./dist/spec ?
</blockquote></details>

See comments above.
___
*[model-playground/scripts/deploy-dev.sh, line 8 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXHbmg5wotV1SJQLpt:-Mea5zsp4c6GCiQOpmjv:b-ikmncu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/scripts/deploy-dev.sh#L8)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is this temporary and for development purpose? It might need to be based on the package version for production deployment.
</blockquote></details>

Yes this is only for development (deploy-dev.sh). I will have another set of scripts for production/staging. 
___
*[model-playground/src/polyfills.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXI9k0-2YcxFp__tjk:-Mea6YWp09FMltn0qnoU:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/src/polyfills.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[model-playground/src/app/app/app.component.html, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXIY0U1w818Ub-VSRu:-Mea6Zwe5ZcIZgLaO9BA:b23o1gi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/src/app/app/app.component.html#L18)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

mobile phone will not contain the nav tree, will it become a drop down menu button?
</blockquote></details>

Yes. I forgot to mention that this is just showing how the media query system could be used. The final version will definitely be different.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/759)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[model-playground/karma-ci.conf.js, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmNwnu4qevm8d0GeOx:-MgmNwnu4qevm8d0GeOy:bdo5kkp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/karma-ci.conf.js#L66)):*
> ```JavaScript
>       timeout: 1800,
>       tunnelIdentifier:
>           `tfjs_backend_webgl_${Date.now()}_${Math.floor(Math.random() * 1000)}`
> ```

model_playground?
___
*[model-playground/package.json, line 5 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmONL2-r89tEJhlEUE:-MgmONL2-r89tEJhlEUF:b6di60v) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/package.json#L5)):*
> ```JSON
>   "version": "0.0.1",
>   "license": "Apache-2.0",
>   "private": true,
> ```

should this be private?
___
*[model-playground/tsconfig.json, line 5 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXH9Ec4_tWrAntiTgl:-MgmOjioEwIbPNOqQbd6:b-jieir8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.json#L5)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Nice catch. Looks like `outDir` here is not actually used (see [here](https://stackoverflow.com/questions/49621628/what-happens-to-the-outdir-in-tsconfig-json-for-angular-projects/49621767)). The output location is specified in angular.json. I changed that to `dist` now. Before it was `dist/model-playground`. Thanks! 
</blockquote></details>

if it is not needed, can it be removed?
___
*[model-playground/src/theme.scss, line 32 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmKGiA38p7-hIm8r9I:-MgmKGiB4QizD8HTIblJ:bkgxlzp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/src/theme.scss#L32)):*
> ```SCSS
> 
> // Theme colors and font.
> $my-primary: mat.define-palette(mat.$amber-palette, 500);
> ```

should these styles prefixed with $playground instead of $my?
___
*[model-playground/src/app/components/navigation_tree/navigation_tree.component.ts, line 45 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmPpIj2PKSXwmpfQqT:-MgmPpIj2PKSXwmpfQqU:b-w02swu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/src/app/components/navigation_tree/navigation_tree.component.ts#L45)):*
> ```XML
> 
>   handleClick(item: ModelItem) {
>     this.router.navigate([this.router.url.split('?')[0]], {
> ```

this route manipulation is bit weird? should it be a fixed route?

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/759)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[model-playground/karma-ci.conf.js, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmNwnu4qevm8d0GeOx:-MgqJBdg7XJH4jX1ctUr:b-645ite) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/karma-ci.conf.js#L66)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

model_playground?
</blockquote></details>

nice catch! Done
___
*[model-playground/package.json, line 5 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmONL2-r89tEJhlEUE:-MgqJMsW7eJ-W09lI_vr:buh39hu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/package.json#L5)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this be private?
</blockquote></details>

This should be OK since model playground is not going to be published as a npm package? (this field was automatically populated by angular command line tool). 
___
*[model-playground/tsconfig.json, line 5 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MeXH9Ec4_tWrAntiTgl:-MgqLJBL-he1-4zkIAYg:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a9fa56d9af66ef8a317aec03fde872604e75de61/model-playground/tsconfig.json#L5)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

if it is not needed, can it be removed?
</blockquote></details>

Done
___
*[model-playground/src/theme.scss, line 32 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmKGiA38p7-hIm8r9I:-MgqLegrCZ6u-fglzJWp:b-qd0qdm) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/src/theme.scss#L32)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should these styles prefixed with $playground instead of $my?
</blockquote></details>

Good idea! Done
___
*[model-playground/src/app/components/navigation_tree/navigation_tree.component.ts, line 45 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/759#-MgmPpIj2PKSXwmpfQqT:-MgqMUyP-tcTGFJUcLSu:brkmyre) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fbd5895b75e6a5278605343762e58f346f6e15d3/model-playground/src/app/components/navigation_tree/navigation_tree.component.ts#L45)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this route manipulation is bit weird? should it be a fixed route?
</blockquote></details>

Turns out that I can just use "[]" which means the current base URL. I will probably create a helper function to make this a little nicer in future PRs. Thanks!

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/759)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
