### PR TITLE
Include two FPS counters to track inference as well as end to end FPS

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/921)

### CODE REVIEW

**Review by jinjingforever — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/921)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[body-segmentation/demos/live_video/src/index.js, line 308 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/921#-MtyTEKGBerJuv-Ztl_D:-MtyTEKGBerJuv-Ztl_E:b-dg9gma) ([raw file](https://github.com/tensorflow/tfjs-models/blob/97adae300b15c33f715c3349f7475833b9a4a4a5/body-segmentation/demos/live_video/src/index.js#L308)):*
> ```JavaScript
>   await setupDatGui(urlParams, cameras);
> 
>   statsModel = setupStats('stats1', '(Model FPS)      ');
> ```

nit: why extra spaces here?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/921)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[body-segmentation/demos/live_video/src/index.js, line 308 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/921#-MtyTEKGBerJuv-Ztl_D:-Mtymd2C5szN7yRQwYgD:b-kp9j46) ([raw file](https://github.com/tensorflow/tfjs-models/blob/97adae300b15c33f715c3349f7475833b9a4a4a5/body-segmentation/demos/live_video/src/index.js#L308)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

nit: why extra spaces here?
</blockquote></details>

The stats library unfortunately uses fixed percent widths which makes the min/max fps stat cut off so the spaces pad out that info

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/921)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

___
*[body-segmentation/demos/live_video/src/index.js, line 214 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/921#-MuCXhmN8bYGt27uaVvb:-MuCXhmN8bYGt27uaVvc:b-sdl4l3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/97adae300b15c33f715c3349f7475833b9a4a4a5/body-segmentation/demos/live_video/src/index.js#L214)):*
> ```JavaScript
>         const webGLBackend = tf.backend();
>         const buffer =
>             webGLBackend.gpgpu.createBufferFromTexture(res.texture, 1, 1);
> ```

This breaks the GPU pipeline, it affects e2e time. We only want to do this for modelTime.



_Code quote:_
```JavaScript
        const buffer =
            webGLBackend.gpgpu.createBufferFromTexture(res.texture, 1, 1);
        webGLBackend.gpgpu.downloadFloat32MatrixFromBuffer(buffer, 1);
```

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/921)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[body-segmentation/demos/live_video/src/index.js, line 214 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/921#-MuCXhmN8bYGt27uaVvb:-MuHdgrODkaBFAtLQGvX:bjkgbwk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/97adae300b15c33f715c3349f7475833b9a4a4a5/body-segmentation/demos/live_video/src/index.js#L214)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This breaks the GPU pipeline, it affects e2e time. We only want to do this for modelTime.
</blockquote></details>

Should I show only one FPS at a time then and you can select between them?

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/921)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

___
*[body-segmentation/demos/live_video/src/index.js, line 214 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/921#-MuCXhmN8bYGt27uaVvb:-MuI3bFQCKugnNkAI1nJ:b32w49) ([raw file](https://github.com/tensorflow/tfjs-models/blob/97adae300b15c33f715c3349f7475833b9a4a4a5/body-segmentation/demos/live_video/src/index.js#L214)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

Should I show only one FPS at a time then and you can select between them? 
</blockquote></details>

SG

**Pull request merged**
