### PR TITLE
skip unneeded operation for posenet single-pose

### PR DESCRIPTION
**Pull request by jrbasso**
The buffer variables are only necessary for multi-person decoding method and it's also not used for after decoding processing. So it can be self contained on the multi-person block and avoiding this processing for single-pose decoding operation.

On my local tests using the new 2.0 posenet version it's about 15% fps improvement for single pose.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/230)

### CODE REVIEW

**Comment by tafsiri** [comment]
@tylerzhu-github any chance you could give PR this a quick once over?

**Comment by tylerzhu-github** [comment]
Yes definitely! Feel free to add me as reviewer. I will try finish it by end of today.

**Comment by tafsiri** [comment]
@tylerzhu-github Thanks, I think github should have sent you a collaborator invite (I can't add you as a reviewer until you accept). However even without that you should be able to start a 'reviewable' review. Let me know if you run into any problems.

**Comment by tylerzhu-github** [comment]
@tafsiri I have accepted the collaborator invite. I did a review for the PR and approved it.

**Pull request merged**
