### PR TITLE
Add pose segmentation output to MediaPipe BlazePose API

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/871)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Great work!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-:-MouFXGE7kvvtF0KuqpH:b-9dwnzc)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[pose-detection/src/types.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouB-l51th3_WXZ96E8:-MouB-l51th3_WXZ96E9:bcpatlx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/pose-detection/src/types.ts#L67)):*
> ```
>  segmentation?: Segmentation;
> ```
Add annotation to the field
___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 94 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouB_n-5rSDnnJ9QCrL:-MouB_n-5rSDnnJ9QCrM:b-dqk6sr) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/pose-detection/src/blazepose_mediapipe/detector.ts#L94)):*
> ```
>       smoothLandmarks: config.enableSmoothing || true,
>       enableSegmentation: config.enableSegmentation || false,
>       smoothSegmentation: config.smoothSegmentation || true,
> ```
Put the default values in validateModelConfig(), if it's already validated, then no need to provide default here.
___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 154 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouCR397PKVGGot6ACO:-MouCR3A0ZXRfe9OFVgu:baa81d7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/pose-detection/src/blazepose_mediapipe/detector.ts#L154)):*
> ```
> more efficient
> ```
format doccomment.
___
*[pose-detection/src/blazepose_mediapipe/mediapipe_test.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouChHN7rtvX7t6bgdW:-MouChHN7rtvX7t6bgdX:b-84syj6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/81ae61a0d96808a4940cdf8ed5b39f583142e74b/pose-detection/src/blazepose_mediapipe/mediapipe_test.ts#L47)):*
<details><summary><i alt="summary">Quoted 23 lines of code…</i></summary>

> ```
> // ref:
> // https://github.com/google/mediapipe/blob/7c331ad58b2cca0dca468e342768900041d65adc/mediapipe/python/solutions/pose_test.py#L31-L51
> const EXPECTED_LANDMARKS = [
>   [463, 284], [470, 275], [473, 274], [476, 273], [464, 275], [464, 275],
>   [463, 275], [494, 275], [473, 276], [470, 293], [464, 293], [544, 322],
>   [450, 325], [626, 321], [371, 316], [697, 314], [300, 305], [717, 313],
>   [279, 305], [719, 311], [279, 302], [711, 313], [285, 304], [521, 471],
>   [465, 466], [608, 548], [357, 492], [701, 614], [350, 608], [707, 624],
>   [362, 628], [732, 632], [306, 630]
> ];
> const EXPECTED_WORLD_LANDMARKS = [
>   [-0.12, -0.58, -0.19], [-0.1, -0.62, -0.19],  [-0.1, -0.62, -0.19],
>   [-0.1, -0.63, -0.19],  [-0.12, -0.62, -0.17], [-0.12, -0.62, -0.17],
>   [-0.12, -0.62, -0.17], [0., -0.63, -0.16],    [-0.08, -0.63, -0.08],
>   [-0.07, -0.57, -0.17], [-0.1, -0.56, -0.15],  [0.16, -0.49, -0.1],
>   [-0.15, -0.49, -0.03], [0.41, -0.49, -0.15],  [-0.42, -0.52, -0.04],
>   [0.65, -0.48, -0.2],   [-0.64, -0.52, -0.14], [0.71, -0.5, -0.21],
>   [-0.71, -0.54, -0.16], [0.72, -0.51, -0.24],  [-0.7, -0.55, -0.19],
>   [0.66, -0.49, -0.21],  [-0.65, -0.53, -0.16], [0.1, 0.01, -0.04],
>   [-0.1, -0.01, 0.04],   [0.36, 0.21, -0.1],    [-0.45, 0.05, -0.1],
>   [0.68, 0.44, 0.01],    [-0.49, 0.43, -0.],    [0.72, 0.46, 0.01],
>   [-0.5, 0.47, 0.01],    [0.78, 0.46, -0.1],    [-0.61, 0.51, -0.05],
> ];
> ```
</details>

Leave the test ground truth here, because only BlazePose uses this ground truth. MoveNet will use another video.
___
*[shared/test_util.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouEHNJ2ZQ1oAT5wk42:-MouEHNJ2ZQ1oAT5wk43:b5wfer3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L37)):*
> ```
> export function imageToBooleanMask
> ```
Add doccomment
___
*[shared/test_util.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouEq7n955bbf8ktsQF:-MouEq7n955bbf8ktsQG:b6gufvi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L46)):*
> ```
> export function segmentationIOU
> ```
Add doccomment
___
*[shared/test_util.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouF9omC-PuruF45tmO:-MouF9omC-PuruF45tmP:bfz3mf6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L55)):*
> ```
>  (sum(expectedMask) + sum(actualMask) - sum(intersectionMask)
> ```
Can this be 0?
___
*[shared/test_util.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouFFLz8NdWe_Rd-QcM:-MouFFLz8NdWe_Rd-QcN:bnjj1od) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L56)):*
> ```
> Number.EPSILON
> ```
Just for my understanding, why do we need this?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/871)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/types.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouB-l51th3_WXZ96E8:-MouTmDmCxCVpBgP6rIh:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/pose-detection/src/types.ts#L67)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>  segmentation?: Segmentation;
> ```
Add annotation to the field
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 94 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouB_n-5rSDnnJ9QCrL:-MouTmz1C-7dvNsmbKWg:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/pose-detection/src/blazepose_mediapipe/detector.ts#L94)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>       smoothLandmarks: config.enableSmoothing || true,
>       enableSegmentation: config.enableSegmentation || false,
>       smoothSegmentation: config.smoothSegmentation || true,
> ```
Put the default values in validateModelConfig(), if it's already validated, then no need to provide default here.
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 154 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouCR397PKVGGot6ACO:-MouTn_--dEQiAFVLjOO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/pose-detection/src/blazepose_mediapipe/detector.ts#L154)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> more efficient
> ```
format doccomment.
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_mediapipe/mediapipe_test.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouChHN7rtvX7t6bgdW:-MouToGW5kA6_rcVCPcq:b-lharcz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/81ae61a0d96808a4940cdf8ed5b39f583142e74b/pose-detection/src/blazepose_mediapipe/mediapipe_test.ts#L47)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> // ref:
> // https://github.com/google/mediapipe/blob/7c331ad58b2cca0dca468e342768900041d65adc/mediapipe/python/solutions/pose_test.py#L31-L51
> const EXPECTED_LANDMARKS = [
>   [463, 284], [470, 275], [473, 274], [476, 273], [464, 275], [464, 275],
>   [463, 275], [494, 275], [473, 276], [470, 293], [464, 293], [544, 322],
>   [450, 325], [626, 321], [371, 316], [697, 314], [300, 305], [717, 313],
>   [279, 305], [719, 311], [279, 302], [711, 313], [285, 304], [521, 471],
>   [465, 466], [608, 548], [357, 492], [701, 614], [350, 608], [707, 624],
>   [362, 628], [732, 632], [306, 630]
> ];
> const EXPECTED_WORLD_LANDMARKS = [
>   [-0.12, -0.58, -0.19], [-0.1, -0.62, -0.19],  [-0.1, -0.62, -0.19],
>   [-0.1, -0.63, -0.19],  [-0.12, -0.62, -0.17], [-0.12, -0.62, -0.17],
>   [-0.12, -0.62, -0.17], [0., -0.63, -0.16],    [-0.08, -0.63, -0.08],
>   [-0.07, -0.57, -0.17], [-0.1, -0.56, -0.15],  [0.16, -0.49, -0.1],
>   [-0.15, -0.49, -0.03], [0.41, -0.49, -0.15],  [-0.42, -0.52, -0.04],
>   [0.65, -0.48, -0.2],   [-0.64, -0.52, -0.14], [0.71, -0.5, -0.21],
>   [-0.71, -0.54, -0.16], [0.72, -0.51, -0.24],  [-0.7, -0.55, -0.19],
>   [0.66, -0.49, -0.21],  [-0.65, -0.53, -0.16], [0.1, 0.01, -0.04],
>   [-0.1, -0.01, 0.04],   [0.36, 0.21, -0.1],    [-0.45, 0.05, -0.1],
>   [0.68, 0.44, 0.01],    [-0.49, 0.43, -0.],    [0.72, 0.46, 0.01],
>   [-0.5, 0.47, 0.01],    [0.78, 0.46, -0.1],    [-0.61, 0.51, -0.05],
> ];
> ```
Leave the test ground truth here, because only BlazePose uses this ground truth. MoveNet will use another video.
</blockquote></details>

I moved it so we don't have to maintain two copies for mediapipe as well as tfjs implementation. I will remove the tfjs one in the next PR.
___
*[shared/test_util.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouEHNJ2ZQ1oAT5wk42:-MouTwv53RxdQvpilpsm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L37)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> export function imageToBooleanMask
> ```
Add doccomment
</blockquote></details>

Done.
___
*[shared/test_util.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouEq7n955bbf8ktsQF:-MouTxXOAdyZDg1Gon5i:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L46)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> export function segmentationIOU
> ```
Add doccomment
</blockquote></details>

Done.
___
*[shared/test_util.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouF9omC-PuruF45tmO:-MouTyPX5IlTRw48mk2U:bvheu2b) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>  (sum(expectedMask) + sum(actualMask) - sum(intersectionMask)
> ```
Can this be 0?
</blockquote></details>

Not with the epsilon
___
*[shared/test_util.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouFFLz8NdWe_Rd-QcM:-MouU-NA3W0jncRxbsIW:br5t9zz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/938326f8f9a472a014d43c9e7d39d8ea732088bf/shared/test_util.ts#L56)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> Number.EPSILON
> ```
Just for my understanding, why do we need this?
</blockquote></details>

so divison by zero is avoided, it's part of the denominator sum as well

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/871)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[pose-detection/src/blazepose_mediapipe/mediapipe_test.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouChHN7rtvX7t6bgdW:-MouUyLx6IJJNiGR8SU3:b-3eepfx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/81ae61a0d96808a4940cdf8ed5b39f583142e74b/pose-detection/src/blazepose_mediapipe/mediapipe_test.ts#L47)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

I moved it so we don't have to maintain two copies for mediapipe as well as tfjs implementation. I will remove the tfjs one in the next PR.
</blockquote></details>

But this is BlazePose specific, MoveNet will have a different set of expected_landmarks. Either change the name to be more specific, or in tfjs test import from here. Both approach is fine with me.
___
*[shared/test_util.ts, line 72 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouVXAO0sWTRHU8Fmo1:-MouVXAO0sWTRHU8Fmo2:bz2vz6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/04d01f689368682ee169469c6e79ccb39f41dc78/shared/test_util.ts#L72)):*
> ```
> +b
> ```
Why do you have to force number?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/871)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/blazepose_mediapipe/mediapipe_test.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouChHN7rtvX7t6bgdW:-Mou_zHC7vPWa4ttRmDu:b-g7ej9e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/81ae61a0d96808a4940cdf8ed5b39f583142e74b/pose-detection/src/blazepose_mediapipe/mediapipe_test.ts#L47)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

But this is BlazePose specific, MoveNet will have a different set of expected_landmarks. Either change the name to be more specific, or in tfjs test import from here. Both approach is fine with me.
</blockquote></details>

Oh I see, sounds good I'll import it from here then
___
*[shared/test_util.ts, line 72 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouVXAO0sWTRHU8Fmo1:-MouaD0d8dAEVWBZpXsD:b-xyw6ya) ([raw file](https://github.com/tensorflow/tfjs-models/blob/04d01f689368682ee169469c6e79ccb39f41dc78/shared/test_util.ts#L72)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> +b
> ```
Why do you have to force number?
</blockquote></details>

You can't add a boolean to a number

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/871)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[shared/test_util.ts, line 72 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/871#-MouVXAO0sWTRHU8Fmo1:-MoubGym13iHXow2bkFh:bcn3o5u) ([raw file](https://github.com/tensorflow/tfjs-models/blob/04d01f689368682ee169469c6e79ccb39f41dc78/shared/test_util.ts#L72)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

You can't add a boolean to a number
</blockquote></details>

Ah, right.

**Pull request merged**
