### PR TITLE
fix security vulnerabilities

### PR DESCRIPTION
**Pull request by pyu10055**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/620)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/620)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[facemesh/package.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-MWjoDujDp8YpqEaL9_d:-MWjoDujDp8YpqEaL9_e:b15no7c) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f8f47da067e7b12671882da84d6bf3f76bd82d00/facemesh/package.json#L16)):*
> ```JSON
>   },
>   "peerDependencies": {
>     "@tensorflow/tfjs-converter": "^3.3.0",
> ```

This package is deprecated, should we just delete it?
___
*[handpose/demo/package.json, line 12 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-MWjoMJsAhkqFjWJrfzC:-MWjoMJsAhkqFjWJrfzD:b1c45ad) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f8f47da067e7b12671882da84d6bf3f76bd82d00/handpose/demo/package.json#L12)):*
> ```JSON
>   },
>   "dependencies": {
>     "@tensorflow-models/handpose": "0.0.7",
> ```

Why not use file:../dist?

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/620)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[facemesh/package.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-MWjoDujDp8YpqEaL9_d:-MWjt95T69IYh6L0e-ga:b-p8txkr) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f8f47da067e7b12671882da84d6bf3f76bd82d00/facemesh/package.json#L16)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This package is deprecated, should we just delete it?
</blockquote></details>

We can delete the package in a separate PR, just try to eliminate sec warning.
___
*[handpose/demo/package.json, line 12 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-MWjoMJsAhkqFjWJrfzC:-MWjtFya6z2ttXLqmU1I:bynbxy2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f8f47da067e7b12671882da84d6bf3f76bd82d00/handpose/demo/package.json#L12)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Why not use file:../dist?
</blockquote></details>

I have changed some of this links since it is not compatible with npm audit fix command. I will revert them back.

**Review by lina128 — APPROVED** [review]
Thank you Ping!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-:-MWz2-wuDVeIS5OaUaSq:b-t1trzh)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[update_yarn_lock.sh, line 1 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-MWz1IhCDyRaB_F3MI3u:-MWz1IhCDyRaB_F3MI3v:bcqgsqy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb53a3e8f62c3c1a1ff199c253df56e0a720472d/update_yarn_lock.sh#L1)):*
> ```Shell
> update() {
> ```

Does it need a license head?

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/620)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[update_yarn_lock.sh, line 1 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/620#-MWz1IhCDyRaB_F3MI3u:-MWz32HyEnVUl1Kq68iU:brr0f3i) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb53a3e8f62c3c1a1ff199c253df56e0a720472d/update_yarn_lock.sh#L1)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Does it need a license head?
</blockquote></details>

added thanks

**Pull request merged**
