### PR TITLE
Introducing KeypointTracker, which associated people between frames using keypoint similarity.

### PR DESCRIPTION
**Pull request by ronnyvotel**
Added tests to show proper functionality of tracker.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/769)

### CODE REVIEW

**Review by ardoerlemans — APPROVED** [review]
Looks great!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-:-Mg7Awuo6yQUUhtAMfxq:b9bkkp1)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg77I6M42XSzqS6ImeD:-Mg77I6N-PVmaFCNt9Vj:baka9fy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L38)):*
> ```XML
>   /**
>    * Computes similarity based on Object Keypoint Similarity (OKS). See
>    * `Tracker` for more details.
> ```

See `oks`? Or did you mean more details on how computeSimilarity is used?
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 43 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg77v2J5B7p7z2TRQiH:-Mg77v2J5B7p7z2TRQiI:b-ftw9rz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L43)):*
> ```XML
>     const numPoses = poses.length;
>     const numTracks = this.tracks.length;
>     if (!(numPoses && numTracks)) {
> ```

I would personally just write

if (poses.length == 0 || this.tracks.length == 0)

But feel free to keep as it is now.
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg78fCa7NFGsLJj71OH:-Mg78fCa7NFGsLJj71OI:b-bibyl9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L47)):*
> ```XML
>     }
> 
>     const simMatrix = [];
> ```

I somehow thought this double loop would be part of the base class. Any reason it shouldn't be there?
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 92 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7AQyq2EXb_NXj8NoH:-Mg7AQyr3DP5jNVFd99F:b-s6d1s5) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L92)):*
> ```XML
>           Math.pow(poseKpt.y - trackKpt.y, 2);
>       const x = 2 * this.keypointFalloff[i];
>       oksTotal += Math.exp(-1*dSquared/(2*boxArea*x**2));
> ```

Nit: could you lint this file so that it introduces a few spaces in this formula?
___
*[pose-detection/src/calculators/interfaces/config_interfaces.ts, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7AkIu1vMFuv9nWGQ1:-Mg7AkIv1crMwnBlxEXh:b-qajlgq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/interfaces/config_interfaces.ts#L98)):*
> ```XML
>                                         // compared in the OKS calculation if
>                                         // both the new detected keypoint and
>                                         // the corresponding track keyoint have
> ```

keypoint

**Review by ronnyvotel — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-:-Mg7VU7qBWx9AaYjvXDO:b-ucfknh)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg77I6M42XSzqS6ImeD:-Mg7UgIO76WD8KAjMJ4J:b5fplz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L38)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

See `oks`? Or did you mean more details on how computeSimilarity is used?
</blockquote></details>

The latter. If people want to get more info, they can check out the abstract method and documentation.
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 43 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg77v2J5B7p7z2TRQiH:-Mg7UwtmAOi-LTorQfSu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L43)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

I would personally just write

if (poses.length == 0 || this.tracks.length == 0)

But feel free to keep as it is now.
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg78fCa7NFGsLJj71OH:-Mg7UxtzCwv4Aawz5m9V:bvb32mw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L47)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

I somehow thought this double loop would be part of the base class. Any reason it shouldn't be there?
</blockquote></details>

I originally had it as part of the base class (and only similarityFn was abstract) but Na envisions that people might want to batch their operations in their own implementations.
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 92 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7AQyq2EXb_NXj8NoH:-Mg7VIA3DF21TfuzDssz:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/keypoint_tracker.ts#L92)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Nit: could you lint this file so that it introduces a few spaces in this formula?
</blockquote></details>

Done
___
*[pose-detection/src/calculators/interfaces/config_interfaces.ts, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7AkIu1vMFuv9nWGQ1:-Mg7VP9h89i-XblAco8e:b-k2rwtz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e776b47cd71c74f8f94e43156acfb9f9742c85ac/pose-detection/src/calculators/interfaces/config_interfaces.ts#L98)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

keypoint
</blockquote></details>

Good catch. Fixed.

**Review by lina128 — APPROVED** [review]
This looks great, especially the test, very extensive and readable, thank you for the contribution, Ronny! Overall LGTM, I only left some nit comments below. Feel free to merge once you addressed them.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-:-Mg7lDen0hKDpW-oaxqU:b-u9k219)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans and @ronnyvotel)

___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 57 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7f1zQ1nGRivNuHUbP:-Mg7f1zQ1nGRivNuHUbQ:b-snw7k3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5d1b4e1c661809bf67f8c2b479dfa119ff5926d/pose-detection/src/calculators/keypoint_tracker.ts#L57)):*
> ```
> OKS)
> ```
nit: Can you provide a ref to this function?  Maybe this link? https://cocodataset.org/#keypoints-eval
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 103 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7ftaICj6c-Y0qECdD:-Mg7ftaICj6c-Y0qECdE:b-7tsyd7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5d1b4e1c661809bf67f8c2b479dfa119ff5926d/pose-detection/src/calculators/keypoint_tracker.ts#L103)):*
> ```
> area
> ```
nit: private?
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7gAwc1RDn48Fr90N-:-Mg7gAwc1RDn48Fr90N0:b-k6zdi4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5d1b4e1c661809bf67f8c2b479dfa119ff5926d/pose-detection/src/calculators/keypoint_tracker.ts#L106)):*
> ```
> 1.0
> ```
nit: This assumes keypoint is normalized? Can you add this assumption/requirement to the doccomment?

**Review by ronnyvotel — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-:-Mg7uWA_Ax7SCTcpGk7h:b-ucfknh)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 57 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7f1zQ1nGRivNuHUbP:-Mg7v2xsC9asBlRRnwFI:bs7wumb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5d1b4e1c661809bf67f8c2b479dfa119ff5926d/pose-detection/src/calculators/keypoint_tracker.ts#L57)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> OKS)
> ```
nit: Can you provide a ref to this function?  Maybe this link? https://cocodataset.org/#keypoints-eval
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 103 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7ftaICj6c-Y0qECdD:-Mg83GSu4DJe0eMU2xZk:bdmt8ym) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5d1b4e1c661809bf67f8c2b479dfa119ff5926d/pose-detection/src/calculators/keypoint_tracker.ts#L103)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> area
> ```
nit: private?
</blockquote></details>

Done. Also made oks() private.
___
*[pose-detection/src/calculators/keypoint_tracker.ts, line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/769#-Mg7gAwc1RDn48Fr90N-:-Mg7vxenEIafAmP0pgrk:b-6m48ae) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5d1b4e1c661809bf67f8c2b479dfa119ff5926d/pose-detection/src/calculators/keypoint_tracker.ts#L106)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 1.0
> ```
nit: This assumes keypoint is normalized? Can you add this assumption/requirement to the doccomment?
</blockquote></details>

Yep, great call.

**Pull request merged**
