### PR TITLE
[body-segmentation] Update README to make it up-to-date.

### PR DESCRIPTION
**Pull request by jinjingforever**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/923)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/923)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

___
*[body-segmentation/README.md, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/923#-MuCfNFK4qdrLJmkrBug:-MuCfNFK4qdrLJmkrBuh:bp4np7n) ([raw file](https://github.com/tensorflow/tfjs-models/blob/0f2e03dad4b49b874aaf1038797507b0b451a521/body-segmentation/README.md#L291)):*
> ```Markdown
> * **foregroundThreshold** The minimum probability to color a pixel as foreground
> rather than background. The alpha channel integer values will be taken as the
> probabilities.  Default to 0.5. Should be a number between 0 and 1.
> ```

'The alpha channel integer values will be taken as the
probabilities.' This is implementation detail, remove?



_Code quote:_
```Markdown
rather than background. The alpha channel integer values will be taken as the
probabilities.  Default to 0.5. Should be a number between 0 and 1.
```
___
*[body-segmentation/README.md, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/923#-MuCfXPK1cbA3reOiB1p:-MuCfXPK1cbA3reOiB1q:b-n431c9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/0f2e03dad4b49b874aaf1038797507b0b451a521/body-segmentation/README.md#L291)):*
> ```Markdown
> * **foregroundThreshold** The minimum probability to color a pixel as foreground
> rather than background. The alpha channel integer values will be taken as the
> probabilities.  Default to 0.5. Should be a number between 0 and 1.
> ```

Defaults



_Code quote:_
```Markdown
Default
```

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/923)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[body-segmentation/README.md, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/923#-MuCfNFK4qdrLJmkrBug:-MuChSls5JA0bAKr6rkp:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/0f2e03dad4b49b874aaf1038797507b0b451a521/body-segmentation/README.md#L291)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

'The alpha channel integer values will be taken as the
probabilities.' This is implementation detail, remove?
</blockquote></details>

Done.
___
*[body-segmentation/README.md, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/923#-MuCfXPK1cbA3reOiB1p:-MuChTjW0jMZVEIRgjkb:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/0f2e03dad4b49b874aaf1038797507b0b451a521/body-segmentation/README.md#L291)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Defaults
</blockquote></details>

Done.

**Review by ahmedsabie — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/923)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — APPROVED** [review]
LGTM. Thank you Jing!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/923#-:-MuDbt0OAoWMSwXsoNF6:b6uhhd3)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
