### PR TITLE
Update knn-classifier to 3.0.0

### PR DESCRIPTION
**Pull request by mattsoulanille**
Includes refactoring to avoid chained ops. ~Should I update the package.json version as well or leave it at 1.2.2?~ Updated to 1.2.3.

Closes https://github.com/tensorflow/tfjs/issues/4550

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/575)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
Converted back to draft since I forgot to update the demo.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/575)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[knn-classifier/src/index.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MRv8czgEOhD4JI8U-zU:-MRv8czhEcN7T0c3EuBp:b-mesqbg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/af745c7514a53c13175fae930aa99bc1bc119cd5/knn-classifier/src/index.ts#L18)):*
> ```XML
>  */
> import * as tf from '@tensorflow/tfjs-core';
> import '@tensorflow/tfjs-layers';
> ```

Do you need layers?

**Comment by mattsoulanille** [comment]
Fixed the demo. It was importing the knn module from ../ instead of node_modules, which was causing the http router to be registered multiple times in the router registry, which is unsupported.

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/575)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[knn-classifier/src/index.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MRv8czgEOhD4JI8U-zU:-MRzFmqLAvogzyLX5u-_:b-kh2fiy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/af745c7514a53c13175fae930aa99bc1bc119cd5/knn-classifier/src/index.ts#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Do you need layers?
</blockquote></details>

Nope. Good catch. Thanks! Removed in a prior commit.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/575)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

___
*[knn-classifier/package.json, line 16 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MS9C4lR85oCCqAVryFb:-MS9C4lR85oCCqAVryFc:b-yz8opj) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4d0cae551acb6a4867d0d92bac43ac80e72729c/knn-classifier/package.json#L16)):*
> ```JSON
>   },
>   "peerDependencies": {
>     "@tensorflow/tfjs-backend-cpu": "^3.0.0-rc.1",
> ```

Should it be ^3.0.0
___
*[knn-classifier/package.json, line 17 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MS9C8OdDxmIcemi173B:-MS9C8OdDxmIcemi173C:b-yz8opj) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4d0cae551acb6a4867d0d92bac43ac80e72729c/knn-classifier/package.json#L17)):*
> ```JSON
>   "peerDependencies": {
>     "@tensorflow/tfjs-backend-cpu": "^3.0.0-rc.1",
>     "@tensorflow/tfjs-core": "^3.0.0-rc.1"
> ```

Should it be ^3.0.0
___
*[knn-classifier/rollup.config.js, line 55 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MS9DXRn2HkN6wuxQVVT:-MS9DXRn2HkN6wuxQVVU:b5yvflk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4d0cae551acb6a4867d0d92bac43ac80e72729c/knn-classifier/rollup.config.js#L55)):*
> ```JavaScript
>       globals: {
> 	'@tensorflow/tfjs-core': 'tf',
>         '@tensorflow/tfjs-converter': 'tf',
> ```

Do you need converter?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/575)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[knn-classifier/package.json, line 16 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MS9C4lR85oCCqAVryFb:-MS9NZKr8wgadW4Ye4FS:b-oozf0s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4d0cae551acb6a4867d0d92bac43ac80e72729c/knn-classifier/package.json#L16)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should it be ^3.0.0
</blockquote></details>

I was going to leave the peerdeps at the rc.1 because it works there, but yeah, it's probably best to bump them to 3.0.0
___
*[knn-classifier/package.json, line 17 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MS9C8OdDxmIcemi173B:-MS9Nh9i2iq_nXCe1tLE:bjg6x97) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4d0cae551acb6a4867d0d92bac43ac80e72729c/knn-classifier/package.json#L17)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should it be ^3.0.0
</blockquote></details>

Yep. Done.
___
*[knn-classifier/rollup.config.js, line 55 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-MS9DXRn2HkN6wuxQVVT:-MS9NiqS2iLlAlMDbydk:bv8faxx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4d0cae551acb6a4867d0d92bac43ac80e72729c/knn-classifier/rollup.config.js#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Do you need converter?
</blockquote></details>

Missed that one. Removed. Thanks!

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/575#-:-MS9P2Ot5s0xn7q1UZXR:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
