### PR TITLE
Added assertions to the dimensions of the input to the neural net.

### PR DESCRIPTION
**Pull request by FenrirWillow**
Previously if you passed an input with width or height 0, TensorFlow fromPixels would error because the requested size would be an invalid texture. This wasn't intuitive to the user of the API. These asserts help with catching the error earlier and present it to the end user in a better fashion.

This issue was raised and discussed here: https://github.com/tensorflow/tfjs/issues/322

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/23)

### CODE REVIEW

**Comment by FenrirWillow** [comment]
Signed

**Comment by oveddan** [comment]
Thanks for doing this!  Just do the minor variable name change then this would LGTM.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[posenet/src/mobilenet.ts, line 107 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/23#-LDg4poT-U4dKHCgRHUC:-LDg4poT-U4dKHCgRHUD:b-bjhe1s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/49dfa55934bb640c3ded1af8fc6c814a839dd578/posenet/src/mobilenet.ts#L107)):*
> ```XML
> }
> 
> export function assertValidDimensions(inputType: InputType) {
> ```

Change the variable name `inputType` to `input`

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/23#-:-LDg4wAhCbmq2no4Hk50:bp2eam5)*

**Comment by FenrirWillow** [comment]
Cheers for reviewing this, I have addressed your comment.

**Comment by FenrirWillow** [comment]
There seem to be some conflicts after @nsthorat merged the latest master branch into this one. Do you want me to resolve them or will you guys take care of that. Just making sure that I note this so that the PR doesn't hang in limbo forever.

**Comment by ManrajGrover** [comment]
@FenrirWillow Thanks for this PR. I think you would need to resolve the conflicts. Let me know if you need any help with that.

**Comment by FenrirWillow** [comment]
Cheers @ManrajGrover . I have resolved the conflicts can you take a look again and see if it is ready for merging now. Thanks

**Comment by nsthorat** [comment]
Oops, small merge conflicts then I will merge this. So sorry for the delay!

**Comment by FenrirWillow** [comment]
I am closing this because there are now significant divergence between the central master branch and mine. I will re-open once I have resolved them.

**Pull request closed without merging**
