### PR TITLE
[pose-detection] Use GPU for the top-k op in MoveNet

### PR DESCRIPTION
**Pull request by ardoerlemans**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans)

___
*[pose-detection/src/movenet/detector.ts, line 530 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/813#-MhG6dNd6HIuVvZIf7bk:-MhG6dNd6HIuVvZIf7bl:b-lwgg6j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1f4a0e2ba345ede8ce838847a9372c81bc04891f/pose-detection/src/movenet/detector.ts#L530)):*
> ```
> tf.env().setFlags({'TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD': 0});
> ```
This will remove all the other flags, meaning those flags will be evaluated to falsy. Please only alter this flag using the set api: tf.env().set('TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD', 0);

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[pose-detection/src/movenet/detector.ts, line 530 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/813#-MhG6dNd6HIuVvZIf7bk:-MhG9N5F2EgXHlBbzVRL:b-um64jw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1f4a0e2ba345ede8ce838847a9372c81bc04891f/pose-detection/src/movenet/detector.ts#L530)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> tf.env().setFlags({'TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD': 0});
> ```
This will remove all the other flags, meaning those flags will be evaluated to falsy. Please only alter this flag using the set api: tf.env().set('TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD', 0);
</blockquote></details>

Ahh, got it. Updated.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 530 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/813#-MhG6dNd6HIuVvZIf7bk:-MhGB5Cy48k30Sg71Grb:bo690qi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1f4a0e2ba345ede8ce838847a9372c81bc04891f/pose-detection/src/movenet/detector.ts#L530)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Ahh, got it. Updated.
</blockquote></details>

will this flag ensure no cpu forwarding for topK?
the logic seems to indicate otherwise:

```
  if (backend.shouldExecuteOnCPU([x]) ||
      lastDim < TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD ||
      k > TOPK_K_CPU_HANDOFF_THRESHOLD)
```

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 530 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/813#-MhG6dNd6HIuVvZIf7bk:-MhGDd3613vUPi5HhHm4:bysoddh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1f4a0e2ba345ede8ce838847a9372c81bc04891f/pose-detection/src/movenet/detector.ts#L530)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

will this flag ensure no cpu forwarding for topK?
the logic seems to indicate otherwise:

```
  if (backend.shouldExecuteOnCPU([x]) ||
      lastDim < TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD ||
      k > TOPK_K_CPU_HANDOFF_THRESHOLD)
```
</blockquote></details>

You're right, if k is larger than TOPK_K_CPU_HANDOFF_THRESHOLD, it will still run on CPU. Our k is set to 6 and the default value for TOPK_K_CPU_HANDOFF_THRESHOLD is 128, but I guess you mean I should not rely on the default and set it explicitly to a value larger than 6?

Our lastDim is 6400, which is less than the default value of 100000 for TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD, so by setting that value to 0 it will not cause top-k to be executed on CPU anymore.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 530 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/813#-MhG6dNd6HIuVvZIf7bk:-MhGeP6Z0fG4_JvX9CcM:b-qvq19d) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1f4a0e2ba345ede8ce838847a9372c81bc04891f/pose-detection/src/movenet/detector.ts#L530)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

You're right, if k is larger than TOPK_K_CPU_HANDOFF_THRESHOLD, it will still run on CPU. Our k is set to 6 and the default value for TOPK_K_CPU_HANDOFF_THRESHOLD is 128, but I guess you mean I should not rely on the default and set it explicitly to a value larger than 6?

Our lastDim is 6400, which is less than the default value of 100000 for TOPK_LAST_DIM_CPU_HANDOFF_SIZE_THRESHOLD, so by setting that value to 0 it will not cause top-k to be executed on CPU anymore.
</blockquote></details>

I think it would be good document why TOPK_K_CPU_HANDOFF_THRESHOLD = 0 would disable the cpu forwarding, since there are three possibilities
1) all input shape < 128
2) lastDim < TOPK_K_CPU_HANDOFF_THRESHOLD
3) k > TOPK_K_CPU_HANDOFF_THRESHOLD

thanks!

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/813#-:-MhGm1o641meKl8kk5i5:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
