### PR TITLE
Add MediaPipe hand detection API

### PR DESCRIPTION
**Pull request by ahmedsabie**
This PR adds the api that will deprecate the handpose api for hand detection. It contains interfaces that will be used for all future hand tracking models, actual implementations of the model will happen in later PRs. 

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
Hi Ahmed, please add PR description. Please squash the commits. Then I'll do another round of review.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-:-MjjUVSlCXyb55j2vHGX:b46396s)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[hand-detection/package.json, line 17 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjRkp-1dmCqMTB9HM0:-MjjRkp09udfgUUnVXBr:bl9y6p4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L17)):*
> ```
> 3.0.0"
> ```
3.9.0
___
*[hand-detection/package.json, line 18 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjRnNS1BAVwZl6Da4E:-MjjRnNS1BAVwZl6Da4F:b-j2nlka) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L18)):*
> ```
> 3.8.0
> ```
3.9.0
___
*[hand-detection/package.json, line 19 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjRpt3DVDm_ylgFOcg:-MjjRpt3DVDm_ylgFOch:b-5frz02) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L19)):*
> ```
> 3.0.0
> ```
3.9.0
___
*[hand-detection/package.json, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjS8Nr1P4MgOl2-ciw:-MjjS8Nr1P4MgOl2-cix:bgs7ma) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L23)):*
> ```
> 0.3.1630010197
> ```
Why do you need to pin the version?
___
*[hand-detection/README.md, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjSSIM8ay5ra2M-E8P:-MjjSSIM8ay5ra2M-E8Q:bkktyuk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/README.md#L3)):*
> ```
> This package aims to deprecate the `handpose` package, with an updated API similar to the pose-detection API.
> ```
Suggest remove. README is for end-users, what is said here doesn't help end-users learning/using this API. After this API is launched, we can add deprecation warning in handpose folder.
___
*[hand-detection/README.md, line 5 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjT5H_46PvndmomeT6:-MjjT5H_46PvndmomeT7:bxlbrw8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/README.md#L5)):*
> ```
> MediaPipe Handpose is a lightweight ML pipeline consisting of two models: A palm detector and a hand-skeleton finger tracking model. It predicts 21 3D hand keypoints per detected hand. For more details, please read our Google AI [blogpost](https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html).
> ```
This API will not be MediaPipe handpose only. Please provide a description of the hand-detection API, not specific model. The modele description should be in it's own README in the model folder. Sugg: copy the structure from pose-detection README.
___
*[hand-detection/rollup.config.js, line 57 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjTu7ZCV89VAMEiYj3:-MjjTu7ZCV89VAMEiYj4:b-a601m0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/rollup.config.js#L57)):*
> ```
> Hands
> ```
Have you double checked? Is @mediapipe/hands namespace `Hands`?
___
*[hand-detection/rollup.config.js, line 70 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjUAAdEJu4UZq-dVq4:-MjjUAAdEJu4UZq-dVq5:b-uga63y) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/rollup.config.js#L70)):*
> ```
> hand-detection
> ```
This is going to be the API's namespace, right? Because it can be used in JS code directly, suggest use camelCase.

**Review by lina128 — COMMENTED** [review]
Also, I suggest remove README, rollup, test etc. in this PR. This first PR should just have the skeleton (API) definition of hand-detection. README should be in its own PR, so does rollup setup. Otherwise, it's too large for reviewers to review. Ideally, a PR should just focus on one thing.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-:-MjjVLIY9VGNzONjbCV7:b-bkpbq7)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie)

**Review by ahmedsabie — COMMENTED** [review]
Sounds good I added a description and removed the setup files, and squashed. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-:-Mjk1NIyDXyn9W8SZb7O:b-jfrwrh)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[hand-detection/package.json, line 17 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjRkp-1dmCqMTB9HM0:-Mjk2BWH4JGwpbvfV2j7:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L17)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 3.0.0"
> ```
3.9.0
</blockquote></details>

Done.
___
*[hand-detection/package.json, line 18 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjRnNS1BAVwZl6Da4E:-Mjk2Bkq-Shqo9vkWk9I:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 3.8.0
> ```
3.9.0
</blockquote></details>

Done.
___
*[hand-detection/package.json, line 19 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjRpt3DVDm_ylgFOcg:-Mjk2C0d2cM1rNC_9mTj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L19)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 3.0.0
> ```
3.9.0
</blockquote></details>

Done.
___
*[hand-detection/package.json, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjS8Nr1P4MgOl2-ciw:-Mjk2CGc-eTrGQ8r5vDI:b-np1te3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/package.json#L23)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 0.3.1630010197
> ```
Why do you need to pin the version?
</blockquote></details>

Fixed, I was checking which version worked since the older ones had issues with the callback function.
___
*[hand-detection/README.md, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjSSIM8ay5ra2M-E8P:-Mjk2Ot2B8sTO7j_2fOn:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/README.md#L3)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> This package aims to deprecate the `handpose` package, with an updated API similar to the pose-detection API.
> ```
Suggest remove. README is for end-users, what is said here doesn't help end-users learning/using this API. After this API is launched, we can add deprecation warning in handpose folder.
</blockquote></details>

Done.
___
*[hand-detection/README.md, line 5 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjT5H_46PvndmomeT6:-Mjk2PIc49FaZLGD4-KE:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/README.md#L5)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> MediaPipe Handpose is a lightweight ML pipeline consisting of two models: A palm detector and a hand-skeleton finger tracking model. It predicts 21 3D hand keypoints per detected hand. For more details, please read our Google AI [blogpost](https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html).
> ```
This API will not be MediaPipe handpose only. Please provide a description of the hand-detection API, not specific model. The modele description should be in it's own README in the model folder. Sugg: copy the structure from pose-detection README.
</blockquote></details>

Done.
___
*[hand-detection/rollup.config.js, line 57 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjTu7ZCV89VAMEiYj3:-Mjk2Po80Mgz8Vwbr76I:b-a2lr5e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/rollup.config.js#L57)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> Hands
> ```
Have you double checked? Is @mediapipe/hands namespace `Hands`?
</blockquote></details>

Yes its Hands
___
*[hand-detection/rollup.config.js, line 70 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjjUAAdEJu4UZq-dVq4:-Mjk2R2yBQJhhjN7CwRs:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3f8ab01271c5aac7ead6f50099522cc3cf8364b3/hand-detection/rollup.config.js#L70)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> hand-detection
> ```
This is going to be the API's namespace, right? Because it can be used in JS code directly, suggest use camelCase.
</blockquote></details>

Done.

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[hand-detection/src/constants.ts, line 3 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpiT5K0Lv-9Jvxz8ti:-MjpiT5K0Lv-9Jvxz8tj:b4d3l3v) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/constants.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2020 Google LLC. All Rights Reserved.
> ```

Remove this file. This constant is not used anywhere in this PR. Add it when it is needed.
___
*[hand-detection/src/index.ts, line 3 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpive57x15JWW0ljj4:-Mjpive57x15JWW0ljj5:b-c42xa4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/index.ts#L3)):*
> ```
> 2020
> ```
2021
___
*[hand-detection/src/types.ts, line 24 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpj1Mn19KQbrjJ1Pop:-Mjpj1Mn19KQbrjJ1Poq:binzvgw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L24)):*
> ```
> export type DetectorInput 
> ```
Can this type definition be lifted to shared/types?
___
*[hand-detection/src/types.ts, line 27 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjA5H3tphONf76bhN:-MjpjA5H3tphONf76bhO:b9hl0ll) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L27)):*
> ```
> export interface InputResolution
> ```
Same for InputResolution.
___
*[hand-detection/src/types.ts, line 33 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjEZLCYR2OEJBiIRu:-MjpjEZLCYR2OEJBiIRv:bfj2w6a) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L33)):*
> ```
> MPHands = 'MPHands'
> ```
Check with MediaPipe team what should be the model name.
___
*[hand-detection/src/types.ts, line 44 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjQ1Y9Rsx8YHaDwsM:-MjpjQ1Y9Rsx8YHaDwsN:b-zaxsxd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L44)):*
> ```
> maxNumHands
> ```
sugg: maxHands
___
*[hand-detection/src/types.ts, line 68 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpjh_o7Qvq-1V2BDUg:-Mjpjh_o7Qvq-1V2BDUh:b-hy82ja) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L68)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> /**
>  * Allowed input format for the `estimateHands` method.
>  */
> export type HandDetectorInput =
>     tf.Tensor3D|ImageData|HTMLVideoElement|HTMLImageElement|HTMLCanvasElement;
> ```
</details>

Duplicate?
___
*[hand-detection/src/types.ts, line 74 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjpNK5rggAnpHl2LR:-MjpjpNK5rggAnpHl2LS:bwd9sjz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L74)):*
> ```
> handedness: 'Left'|'Right';
> ```
Add annotation of the semantics.
___
*[hand-detection/src/mediapipe/constants.ts, line 20 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpk-uU-CH6wqlo_woV:-Mjpk-uU-CH6wqlo_woW:b-w60clv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/mediapipe/constants.ts#L20)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> import {MPHandsMediaPipeEstimationConfig, MPHandsMediaPipeModelConfig} from './types';
> 
> export const DEFAULT_MPHANDS_MODEL_CONFIG: MPHandsMediaPipeModelConfig = {
>   runtime: 'mediapipe',
>   maxNumHands: 2,
>   minDetectionConfidence: 0.5,
> };
> 
> export const DEFAULT_MPHANDS_ESTIMATION_CONFIG:
>     MPHandsMediaPipeEstimationConfig = {
>       flipHorizontal: false,
>       staticImageMode: true,
>     };
> ```
</details>

This file is implementation detail, can be in a follow up PR.
___
*[hand-detection/src/mediapipe/types.ts, line 3 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpkkK_AtdVwsQJlDY-:-MjpkkK_AtdVwsQJlDY0:bl128oh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/mediapipe/types.ts#L3)):*
> ```
> /**
>  * @license
>  * Copyright 2021 Google LLC. All Rights Reserved.
> ```
Remove this file and all the mediapipe folder. This PR should only focus on the hand-detection API. Then we can review ourselves. For MediaPipe related code, we need to get MediaPipe team to review.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[hand-detection/src/index.ts, line 3 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpive57x15JWW0ljj4:-MjzVc_sBNol6FjuKSa0:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/index.ts#L3)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2021
</blockquote></details>

Done.
___
*[hand-detection/src/types.ts, line 24 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpj1Mn19KQbrjJ1Pop:-MjzVfIE7q2RVO-ISlz-:b-hev2fs) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L24)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> export type DetectorInput 
> ```
Can this type definition be lifted to shared/types?
</blockquote></details>

I'll add that in a separate PR which factors out common things from pose-detection, but I'll remove it from this file.
___
*[hand-detection/src/types.ts, line 27 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjA5H3tphONf76bhN:-MjzVno4ELFdHn7lrTQE:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L27)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> export interface InputResolution
> ```
Same for InputResolution.
</blockquote></details>

Done.
___
*[hand-detection/src/types.ts, line 33 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjEZLCYR2OEJBiIRu:-MjzVo9s2WmqaoTvxsXm:bhvehgk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L33)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> MPHands = 'MPHands'
> ```
Check with MediaPipe team what should be the model name.
</blockquote></details>

They said just MediaPipe Hands but I'll ask them if this spelling is fine, because otherwise it might get confusing having a "mediapipe" mediapipe and a "tfjs" mediapipe
___
*[hand-detection/src/types.ts, line 44 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjQ1Y9Rsx8YHaDwsM:-MjzW-Nw7u3eQQrnrliG:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L44)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> maxNumHands
> ```
sugg: maxHands
</blockquote></details>

Done.
___
*[hand-detection/src/types.ts, line 68 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpjh_o7Qvq-1V2BDUg:-MjzW1gnE4WLCKKTHSeq:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L68)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> /**
>  * Allowed input format for the `estimateHands` method.
>  */
> export type HandDetectorInput =
>     tf.Tensor3D|ImageData|HTMLVideoElement|HTMLImageElement|HTMLCanvasElement;
> ```
Duplicate?
</blockquote></details>

Done.
___
*[hand-detection/src/types.ts, line 74 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjpNK5rggAnpHl2LR:-MjzW1RjCXJQDjkFCx48:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L74)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> handedness: 'Left'|'Right';
> ```
Add annotation of the semantics.
</blockquote></details>

Done.
___
*[hand-detection/src/constants.ts, line 3 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpiT5K0Lv-9Jvxz8ti:-MjzW2vC16SC_m92xAp_:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/constants.ts#L3)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Remove this file. This constant is not used anywhere in this PR. Add it when it is needed.
</blockquote></details>

Done.
___
*[hand-detection/src/mediapipe/constants.ts, line 20 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-Mjpk-uU-CH6wqlo_woV:-MjzW3CtANBo8eI5v8mJ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/mediapipe/constants.ts#L20)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> import {MPHandsMediaPipeEstimationConfig, MPHandsMediaPipeModelConfig} from './types';
> 
> export const DEFAULT_MPHANDS_MODEL_CONFIG: MPHandsMediaPipeModelConfig = {
>   runtime: 'mediapipe',
>   maxNumHands: 2,
>   minDetectionConfidence: 0.5,
> };
> 
> export const DEFAULT_MPHANDS_ESTIMATION_CONFIG:
>     MPHandsMediaPipeEstimationConfig = {
>       flipHorizontal: false,
>       staticImageMode: true,
>     };
> ```
This file is implementation detail, can be in a follow up PR.
</blockquote></details>

Done.
___
*[hand-detection/src/mediapipe/types.ts, line 3 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpkkK_AtdVwsQJlDY-:-MjzW5LA8ndM3176Uh-G:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/mediapipe/types.ts#L3)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> /**
>  * @license
>  * Copyright 2021 Google LLC. All Rights Reserved.
> ```
Remove this file and all the mediapipe folder. This PR should only focus on the hand-detection API. Then we can review ourselves. For MediaPipe related code, we need to get MediaPipe team to review.
</blockquote></details>

Done.

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[hand-detection/src/types.ts, line 33 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjEZLCYR2OEJBiIRu:-Mk39T3V5Smx9NtWVnWP:b-batja) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L33)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

They said just MediaPipe Hands but I'll ask them if this spelling is fine, because otherwise it might get confusing having a "mediapipe" mediapipe and a "tfjs" mediapipe
</blockquote></details>

MediaPipe is the model's brand name, we should use full spelling: MediaPipeHands
___
*[hand-detection/src/types.ts, line 74 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjpNK5rggAnpHl2LR:-Mk3A8cz9m1Int3zEOUf:b-vw3x51) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L74)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add this senntence: If it is not the case, please swap the handedness output in the application.
Also follow convention in our codebase, add annotation at the end of the line, not above. Something like: `handedness: 'Left'|'Right'; //handedness ...

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[hand-detection/src/types.ts, line 33 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjEZLCYR2OEJBiIRu:-Mk3Ysp85Krbx24ZV9Rr:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L33)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

MediaPipe is the model's brand name, we should use full spelling: MediaPipeHands
</blockquote></details>

Done.
___
*[hand-detection/src/types.ts, line 74 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-MjpjpNK5rggAnpHl2LR:-Mk3YtO_BYRDjeGxEIQW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3e2427c334201ac69b6e2c2ed2430876c698b9b6/hand-detection/src/types.ts#L74)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Add this senntence: If it is not the case, please swap the handedness output in the application.
Also follow convention in our codebase, add annotation at the end of the line, not above. Something like: `handedness: 'Left'|'Right'; //handedness ...
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/833#-:-Mk3jrWAESWvioutQBqf:b-85i648)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
