### PR TITLE
Remove detectPoseButton 

### PR DESCRIPTION
**Pull request by hpssjellis**
I removed the "detectPoseButton" from Gui.dat and automated "outputStride" and "image" to work directly. 
I was going to get "resolution" or "imageScaleFactor" working with this pull request but that will be a bit more complex set of changes. Would like to separate things into two pull requests.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/18)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/18#-:-LCeMNpK-IRmdLq8VwAE:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thanks @hpssjellis!

**Comment by hpssjellis** [comment]
Quick question. Is there a plan to make releases for Posenet? I see nothing at 
[releases](https://github.com/tensorflow/tfjs-models/releases) but I notice the script src shows version 0.0.1 (probably a default)  when loading https://unpkg.com/@tensorflow-models/posenet

**Comment by oveddan** [comment]
@nsthorat what do you think about a version bump and new release to include this change?

**Comment by nsthorat** [comment]
I will do that soon! I need to first convert models over to rollup and then we'll do a minor version release (then they can be used inside observable and have a much saner story around <script src> usages).

**Comment by oveddan** [comment]
@nsthorat not sure what happened, but now when navigating to `https://unpkg.com/@tensorflow-models/posenet` you get an error:
"Cannot find module "dist/bundle.js" in package @tensorflow-models/posenet@0.0.1"

**Comment by nsthorat** [comment]
Maybe unpkg was down -- do you still see it? That link works for me.

**Pull request merged**
