### PR TITLE
Update face model links to tfhub

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1002)

### CODE REVIEW

**Review by jinjingforever — APPROVED** [review]

**Comment by mahlm** [comment]
Sorry to reach out again, but it's been two months since I asked about a face-landmark npm release. We're hoping to get the recent changes in our application as soon as possible. Is there a timeline for release? If it's still awhile out, we'll either need to switch to MediaPipe, or fork the repo and do our own npm release. Thanks!

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1002#-:-N-dxd4x974cWpR8W5Ut:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Comment by ahmedsabie** [comment]
@mahlm It is published now

**Comment by vladmandic** [comment]
"new" facemesh-detection models are called "short" and "full" and they are based on blazeface "front" and "back" models, but what are the differences? what is "new" about them?

and new facemesh-landmarks-attention model is produced how? original mediapipe model uses custom ops, so this is ported to tfjs somehow, but no notes whatever.

not to mention little notes there are not correct as model does not produce 478 points as stated in the model notes, but instead produces many many more as each attention step produces separate output tensor which then needs to be mapped over original points, but again no docs.

**Pull request merged**
