### PR TITLE
Initial TFJS tasks API

### PR DESCRIPTION
**Pull request by jinjingforever**
Based on Ping and Matt's idea, this PR defines a new model type "Task Model". For each "low level" model (e.g. tfjs model, or tflite task library), a TaskModelTransformer is defined to load and transform the low level model to task model. 

I did this in `tasks/image_classification.ts` and `tasks/nl_classification.ts`. Please see how they look like. The idea is to put models with the same task type in a single file like this (In the future PRs, for example, I will add `tasks/image_segmentation.ts`, etc).  `tasks/all_tasks.ts` serves as a central "index" for all the tasks and models.

I also simplified the API interface to have only two parameters. The first one is the "model name path", something like `MLTask.ImageClassification.TFJSMobileNet`. Basically users can specify model+task together. The second parameter is options. 

See the main README.md file for more detailed descriptions and examples.

Please also check out the demo about how things are used in practice. I included a screenshot in the PR.

Thanks!

(I will add tests in the next PR. Trying to get this ready before recording the demo video:) Thanks!)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/639)

### CODE REVIEW

**Comment by jinjingforever** [comment]
Just realized that the interface design has some flaws. Will update and let you know when it is ready for review. Thanks!

**Comment by jinjingforever** [comment]
Hi Ping, I updated the code and PR description. It is now ready for review. Thank you!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/639)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @mattsoulanille)

___
*[tasks/package.json, line 29 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsMXV33VxAWPeUfp9p:-MXsMXV33VxAWPeUfp9q:b-y3fz66) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/package.json#L29)):*
> ```JSON
>     "@rollup/plugin-typescript": "^3.0.0",
>     "@tensorflow/tfjs-core": "link:../../tfjs/tfjs-core",
>     "@tensorflow/tfjs-tflite": "0.0.1-alpha.0",
> ```

this is duplicated
___
*[tasks/package.json, line 58 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsMgXR4cDcBAq7N0jE:-MXsMgXR4cDcBAq7N0jF:bj51o2e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/package.json#L58)):*
> ```JSON
>   "scripts": {
>     "build": "tsc",
>     "build-backend-cpu": "cd ../tfjs-backend-cpu && yarn && yarn build",
> ```

why it needs to build cpu? should it be tfjs-core?
___
*[tasks/README.md, line 16 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsMyyq4RteM1kH2n8P:-MXsMyyq4RteM1kH2n8Q:b-voiesl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/README.md#L16)):*
> ```Markdown
> is built on top of the [TFLite Task Library][tflite task library] and
> WebAssembly. As a result, all TFLite custom models should comply with the
> metadata requirements of the corresonding task in the TFLite task library.
> ```

it would good to have link to the metadata requirement
___
*[tasks/README.md, line 20 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsN9oe-ll_SbpMGgna:-MXsN9oe-ll_SbpMGgnb:b-qnd6k3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/README.md#L20)):*
> ```Markdown
> # Usage
> 
> ## Import the packages
> ```

should this package automatically deps on all the support tfjs model libraries?
___
*[tasks/demos/image_classification/src/index.html, line 17 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsNlfJ-eJeK1hC01rI:-MXsNlfJ-eJeK1hC01rJ:b-zihd4n) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/demos/image_classification/src/index.html#L17)):*
> ```HTML
> <!DOCTYPE html>
> <meta charset="utf-8">
> <title>Image Classification Tasks Demo</title>
> ```

should we use the visionkit visualization code here for our task library demos?
This would also encourage us to improve the visualization tools with new model types.

**Review by pyu10055 — COMMENTED** [review]
Thank you Jing, on high level I think this is a great direction for us, enable web model to enjoy varieties of runtimes. I think this is highly correlated with Na's work on the pose API, let us have a design review and refine the API further. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-:-MXsObMY6wqMzFyazvGU:bx9w1jh)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @mattsoulanille)

**Review by jinjingforever — COMMENTED** [review]
Agree! A review meeting with the team is a great idea. Please help schedule one maybe next week? Thank you

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-:-MXsSPfBC6ZqfXt-Epqq:bry7h6y)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[tasks/package.json, line 29 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsMXV33VxAWPeUfp9p:-MXsOyRkESGFflg4zAWf:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/package.json#L29)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this is duplicated
</blockquote></details>

Done.
___
*[tasks/package.json, line 58 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsMgXR4cDcBAq7N0jE:-MXsPLbCDX3SN_uV9C61:bsy6iiz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/package.json#L58)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why it needs to build cpu? should it be tfjs-core?
</blockquote></details>

ah, this is actually the leftover of my earlier development. Removed.
___
*[tasks/README.md, line 16 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsMyyq4RteM1kH2n8P:-MXsQatsBSoF5UjwvcdP:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/README.md#L16)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it would good to have link to the metadata requirement
</blockquote></details>

Done.
___
*[tasks/README.md, line 20 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsN9oe-ll_SbpMGgna:-MXsQnDJBVC-DtOhBh5k:b-bzxpvs) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/README.md#L20)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this package automatically deps on all the support tfjs model libraries?
</blockquote></details>

Yeah, I thought about this as well, but couldn't 100% decide:) If we depend on all models, then the package size would be large.. If we don't, then we will have to ask them to manually import those models like this.. 

I think we can have a discussion with the team when having our design review.
___
*[tasks/demos/image_classification/src/index.html, line 17 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MXsNlfJ-eJeK1hC01rI:-MXsR_ZF4f3EFEAFgcX0:bunn7m) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a422cbdfeadd7878fb963b626cb063cf519c71bc/tasks/demos/image_classification/src/index.html#L17)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we use the visionkit visualization code here for our task library demos?
This would also encourage us to improve the visualization tools with new model types.
</blockquote></details>

Good idea! Or should we re-write that code in tfjs-examples to use our task API and link from here? Either way is fine.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Thanks, Jing! This should remove the need for a lot of the boilerplate code needed to perform tasks with the models we support. 

@pyu10055 I think another design review is a good idea. There are a few aspects of the design I came up with in the unification doc that don't seem to work in practice. I've detailed them in my comments.

> Reviewed 2 of 20 files at r1, 9 of 18 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-:-MY6smNdDeRZE-ypJ9LZ:b-veo09x)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[tasks/package.json, line 19 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6YE9rDdZAIUYXAARm:-MY6YE9rDdZAIUYXAARn:b-rz9d96) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/package.json#L19)):*
> ```JSON
>   },
>   "dependencies": {
>     "@tensorflow/tfjs-tflite": "0.0.1-alpha.0"
> ```

Should this use `link:...` instead of being pinned to a published version?
___
*[tasks/README.md, line 76 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6YgxO8fvJFsOYAjUF:-MY6YgxPD3WTzbYS8jL0:b-ydvfzc) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/README.md#L76)):*
> ```Markdown
> the same task model type: `ImageClassifier` in this case. Each task model
> defines an unique and easy-to-use inference method that fits its task the best.
> For example, the `ImageClassiier` task model defines a `classify` method that
> ```

Typo in ImageClassifier
___
*[tasks/rollup.config.js, line 24 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6ZGZh0y3PZZHrQJan:-MY6ZGZh0y3PZZHrQJao:bcr7dx9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/rollup.config.js#L24)):*
> ```
>  ${(new Date).getFullYear()} 
> ```
Nice!
___
*[tasks/src/task_model.ts, line 62 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6moyaBp5NZTwaSYiq:-MY6moyb3Zi3izARU8K0:bcpa8kg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/src/task_model.ts#L62)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> export async function loadTaskModel<M extends BaseTaskModel, O>(
>     taskModelTransformer: TaskModelTransformer<M, O>, options?: O): Promise<M> {
>   return taskModelTransformer.loadAndTransform(options);
> }
> ```
</details>


In my initial proposal in the unification doc, I thought we could separate model loading from model transforming. `loadTaskModel` would have loaded the model itself and would have _then_ applied the transformer to the model after it had been loaded. I now realize that design probably won't work since each model likely has specific requirements for how it's loaded, and it's unlikely for a transformer to work for two different models.

Given that this function now just calls `taskModelTransformer.loadAndTransform`, (instead of calling separate `loadModel` and `transform` functions), it might be redundant. However, if it's easier to use than calling `loadAndTransform` for each TaskModelTransformer, it may be worth keeping. What do people think?

We could remove this function, rename `TaskModelTransformer` to `TaskModel` (since it now handles all aspects [loading and transforming] of the model instead of just transforming), and rename `loadAndTransform` to `load` (since loading a TaskModel now implicitly applies its transform).  Users would then just call, for example, `MLTask.ImageClassification.TFJSMobileNet.load()` to load a model.

Alternatively, since `TaskModelTransformer` has only a single key who's value is a function that loads and applies the transform, we could turn the whole thing into a function and call it `LoadTaskModel`:
```
export type LoadTaskModel<M extends BaseTaskModel, O> = (options?: O): Promise<M>;
```
Then, users would call `MLTask.ImageClassification.TFJSMobileNet()` to load a model.
I think the `LoadTaskModel` approach is simplest.

We can discuss this more at the meeting.
___
*[tasks/src/tasks/common.ts, line 24 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6bl9ICDqCOHboPF5R:-MY6bl9ICDqCOHboPF5S:bwwynck) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/src/tasks/common.ts#L24)):*
> ```
> export interface TaskModelTransformer<M extends BaseTaskModel, O> {
>   loadAndTransform(options?: O): Promise<M>;
> }
> ```

This could maybe be a function instead of an object with a single value that is a function. e.g.

```
export type LoadTaskModel<M extends BaseTaskModel, O> = (options?: O): Promise<M>;
```
... unless we want to add more methods to it in the future, in which case it should stay an object.
___
*[tasks/src/tasks/image_classification.ts, line 141 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6sHrU63KIL1fWYXi_:-MY6sHrVBQQy7nneuJTX:b7daqno) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/src/tasks/image_classification.ts#L141)):*
> ```
>             return transformTFLiteImageClassifierModel(modelUrl, options);
> ```

This is an example of where separating the model load step from the model transformation step in `loadTaskModel` might help, but the solution here is likely better than the one I had in mind in the unification doc.
___
*[tasks/demos/image_classification/package.json, line 11 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6ZdaF9QFtEhNX2TTb:-MY6ZdaF9QFtEhNX2TTc:b-mne992) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/demos/image_classification/package.json#L11)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     "@tensorflow/tfjs-backend-cpu": "^3.1.0",
>     "@tensorflow/tfjs-backend-webgl": "^3.1.0",
>     "@tensorflow/tfjs-converter": "^3.1.0",
>     "@tensorflow/tfjs-core": "^3.1.0",
>     "@tensorflow/tfjs-tflite": "0.0.1-alpha.0",
>     "@tensorflow-models/tasks": "link:../../dist",
>     "@tensorflow-models/mobilenet": "^2.1.0"
> ```
</details>

In general, should we be pinning versions for demos? It might make it easier to debug if we use `link:...`.

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/639)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @mattsoulanille, and @pyu10055)

___
*[tasks/src/task_model.ts, line 62 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/639#-MY6moyaBp5NZTwaSYiq:-MY7jkP861bsq79skvHw:betn7re) ([raw file](https://github.com/tensorflow/tfjs-models/blob/834c76d8222044978459eadd330332cc5c2e9f81/tasks/src/task_model.ts#L62)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> export async function loadTaskModel<M extends BaseTaskModel, O>(
>     taskModelTransformer: TaskModelTransformer<M, O>, options?: O): Promise<M> {
>   return taskModelTransformer.loadAndTransform(options);
> }
> ```

In my initial proposal in the unification doc, I thought we could separate model loading from model transforming. `loadTaskModel` would have loaded the model itself and would have _then_ applied the transformer to the model after it had been loaded. I now realize that design probably won't work since each model likely has specific requirements for how it's loaded, and it's unlikely for a transformer to work for two different models.

Given that this function now just calls `taskModelTransformer.loadAndTransform`, (instead of calling separate `loadModel` and `transform` functions), it might be redundant. However, if it's easier to use than calling `loadAndTransform` for each TaskModelTransformer, it may be worth keeping. What do people think?

We could remove this function, rename `TaskModelTransformer` to `TaskModel` (since it now handles all aspects [loading and transforming] of the model instead of just transforming), and rename `loadAndTransform` to `load` (since loading a TaskModel now implicitly applies its transform).  Users would then just call, for example, `MLTask.ImageClassification.TFJSMobileNet.load()` to load a model.

Alternatively, since `TaskModelTransformer` has only a single key who's value is a function that loads and applies the transform, we could turn the whole thing into a function and call it `LoadTaskModel`:
```
export type LoadTaskModel<M extends BaseTaskModel, O> = (options?: O): Promise<M>;
```
Then, users would call `MLTask.ImageClassification.TFJSMobileNet()` to load a model.
I think the `LoadTaskModel` approach is simplest.

We can discuss this more at the meeting.
</blockquote></details>

Thank you Matt for the detailed thoughts! I really like the idea of using `MLTask.ImageClassification.TFJSMobileNet.load()`. I think it matches our current convention the best (e.g. mobilenet.load), and it is slightly more extensible then using the function approach (the last one you mentioned).

I will give a try, and we can discuss more in our review. Thanks!

**Comment by jenperson** [comment]
This PR is being closed because the project is on hold.

**Pull request closed without merging**
