### PR TITLE
Modifying number of rows in README.md

### PR DESCRIPTION
**Pull request by jenperson**
Modifying number of rows in README.md to fix misalignment in the table
of models. This makes the table more readable.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1026)

### CODE REVIEW

**Review by jasonmayes — APPROVED** [review]

**Review by mattsoulanille — APPROVED** [review]
LGTM. Thanks!

**Review by mattsoulanille — APPROVED** [review]

**Review by jasonmayes — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1026)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by mattsoulanille** [comment]
@jasonmayes your approval should now be counted in PRs to tfjs-models (same for @jenperson). Maybe you need to re-approve? If it's not working, ask Ping for help.

**Review by jasonmayes — APPROVED** [review]

**Comment by jasonmayes** [comment]
I re approved but does not seem to like it :-/

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1026)* status: :shipit: complete! 3 of 1 approvals obtained

**Pull request merged**
