### PR TITLE
[pose-detection] Allow users to specify the MoveNet tracker configuration

### PR DESCRIPTION
**Pull request by ardoerlemans**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans)

___
*[pose-detection/src/calculators/interfaces/config_interfaces.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2Rt49wZ4uQGs9J9E:-MgX2Rt49wZ4uQGs9J9F:b-73ayht) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/calculators/interfaces/config_interfaces.ts#L73)):*
> ```XML
> }
> export interface TrackerConfig {
>   [index: string]: unknown;
> ```

What is this field for?
___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2ath-Rr_7UolPgZz:-MgX2ath-Rr_7UolPg_-:baych4j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector.ts#L90)):*
> ```XML
>         // copy of the default config merged with the user specified config.
>         const trackerConfig =
>             mergeDeep(DEFAULT_TRACKER_CONFIG, config.trackerConfig) as
> ```

nit: You probably want to control what attributes you want to merge.
___
*[pose-detection/src/movenet/detector_utils.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX-k1A6d384EMjcRhW:-MgX-k1A6d384EMjcRhX:b-rmvb1b) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L42)):*
> ```XML
>   }
> 
>   // Tracker will validate the trackingConfig.
> ```

Start the annotation with TODO
___
*[pose-detection/src/movenet/detector_utils.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX-rk985t02q9AKSWB:-MgX-rk985t02q9AKSWC:b-hbiizh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L56)):*
> ```XML
> 
> function isObject(item: unknown) {
>   return (item && typeof item === 'object' && !Array.isArray(item));
> ```

item != null
___
*[pose-detection/src/movenet/detector_utils.ts, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX07z068EHAj7jdu93:-MgX07z068EHAj7jdu94:b-pdc094) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L72)):*
> ```XML
>  */
> export function mergeDeep(
>     target: {[index: string]: unknown},
> ```

sugg: name
___
*[pose-detection/src/movenet/detector_utils.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX0AGp7_1BGK2RJpLl:-MgX0AGp7_1BGK2RJpLm:b-pdc094) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L73)):*
> ```XML
> export function mergeDeep(
>     target: {[index: string]: unknown},
>     source: {[index: string]: unknown}): {[index: string]: unknown} {
> ```

sugg: name
___
*[pose-detection/src/movenet/detector_utils.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX0BxE7E6AkIBFxT3l:-MgX0BxE7E6AkIBFxT3m:b-kqhpvl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L73)):*
> ```XML
> export function mergeDeep(
>     target: {[index: string]: unknown},
>     source: {[index: string]: unknown}): {[index: string]: unknown} {
> ```

sugg: index -> name
___
*[pose-detection/src/movenet/types.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX0tTEEr4MaERqj26Z:-MgX0tTEEr4MaERqj26_:bix3jqp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/types.ts#L46)):*
> ```XML
>  * to be considered a valid pose detection.
>  *
>  * `enableTracking': Optional. A boolean indicating whether a tracking algorithm
> ```

Sugg: Optional. A boolean indicating whether human bodies should be tracked across frames. If true, then each pose will have an id that uniquely identifies a human body. Only used in multi-pose models.

**Review by ardoerlemans — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-:-MgXFRm_0p6aY-S_ifNb:b-9qdoz3)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/calculators/interfaces/config_interfaces.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2Rt49wZ4uQGs9J9E:-MgXCjaZ4qGpMj8G2ALS:blo65qv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/calculators/interfaces/config_interfaces.ts#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

What is this field for?
</blockquote></details>

To keep the linter happy when it parses mergeDeep in detector_util.ts. I have added a comment.
___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2ath-Rr_7UolPgZz:-MgXCq0m1a5vsQuPwvKW:b-bply52) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector.ts#L90)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

nit: You probably want to control what attributes you want to merge.
</blockquote></details>

The user can override all of the tracker configuration fields if they want.
___
*[pose-detection/src/movenet/detector_utils.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX-k1A6d384EMjcRhW:-MgXD-QR3QfDk7kYwB5D:bb8qkxg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L42)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Start the annotation with TODO
</blockquote></details>

It's not a TODO, but just a comment that we don't need to validate the tracker config in this method. The tracker constructor will take care of that. I have updated the comment to be clearer.

There is a TODO here by the way:
https://github.com/tensorflow/tfjs-models/blob/2e6810e68676a65e0a0ac4ec935cca9e7e58ddc6/pose-detection/src/calculators/keypoint_tracker.ts#L35
___
*[pose-detection/src/movenet/detector_utils.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX-rk985t02q9AKSWB:-MgXE6goEMqdA1KWDUCQ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L56)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

item != null
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX07z068EHAj7jdu93:-MgXD_ddCwuzAQxt64Bu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L72)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

sugg: name
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX0AGp7_1BGK2RJpLl:-MgXD_te1Q24dTDHIMGM:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

sugg: name
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX0BxE7E6AkIBFxT3l:-MgXDa6w4sH2tIxBhfqC:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector_utils.ts#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

sugg: index -> name
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/types.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX0tTEEr4MaERqj26Z:-MgXE4YA3ffxTcj1hanb:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/types.ts#L46)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Sugg: Optional. A boolean indicating whether human bodies should be tracked across frames. If true, then each pose will have an id that uniquely identifies a human body. Only used in multi-pose models.
</blockquote></details>

Done.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/interfaces/config_interfaces.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2Rt49wZ4uQGs9J9E:-MgfrGBxDQUJ6XOEmyyn:b-ntd2i7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/calculators/interfaces/config_interfaces.ts#L73)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

To keep the linter happy when it parses mergeDeep in detector_util.ts. I have added a comment.
</blockquote></details>

This interface is user facing, I wouldn't add this field for internal implementation reason.
___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2ath-Rr_7UolPgZz:-MgfrlNM1xcNYlon-w7k:b-r54qma) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector.ts#L90)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

The user can override all of the tracker configuration fields if they want.
</blockquote></details>

All of the tracker configuration fields is a finite set of fields, right?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2ath-Rr_7UolPgZz:-MgfwRAsEUAAAtoH3xwM:bxve6wv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector.ts#L90)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

All of the tracker configuration fields is a finite set of fields, right?
</blockquote></details>

Ah, I see your point, you are worried that trackerParams will be shallow copied. How about just validate the common fields here and leave the trackerParams to each tracker to validate in their constructor functions?

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/calculators/interfaces/config_interfaces.ts, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2Rt49wZ4uQGs9J9E:-Mgg054j9SEfLHumNBA0:bppqu6f) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/calculators/interfaces/config_interfaces.ts#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This interface is user facing, I wouldn't add this field for internal implementation reason.
</blockquote></details>

Good point. Removed it again (as well as the deepMerge function that needed this).
___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MgX2ath-Rr_7UolPgZz:-Mgg0BUv5v3SSJ3zpiaO:b-12z1io) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d3f1de7e4246647a44e7baf8ed7d59441c7607e/pose-detection/src/movenet/detector.ts#L90)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Ah, I see your point, you are worried that trackerParams will be shallow copied. How about just validate the common fields here and leave the trackerParams to each tracker to validate in their constructor functions?
</blockquote></details>

I have removed the mergeDeep function and now added a function that knows what type it's merging. Let me know if that works for you.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 86 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNiZnEe-MkRA30MyS:-MggNiZnEe-MkRA30MyT:bd4och8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector.ts#L86)):*
> ```XML
>     if (this.multiPoseModel && this.enableTracking) {
>       if (config.trackerConfig) {
>         const trackerConfig =
> ```

Can you move this part to the validateModelConfig function?
___
*[pose-detection/src/movenet/detector_utils.ts, line 60 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNJ3EExI7D1W2qxYn:-MggNJ3EExI7D1W2qxYo:bn1a092) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L60)):*
> ```XML
>     defaultConfig: TrackerConfig, userConfig: TrackerConfig): TrackerConfig {
>   const mergedConfig: TrackerConfig = {
>     maxTracks: userConfig.maxTracks || defaultConfig.maxTracks,
> ```

Please explicitly check != null, because 0 is falsy in JS.
___
*[pose-detection/src/movenet/detector_utils.ts, line 61 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNPue1Mp4n2vnfxW5:-MggNPue1Mp4n2vnfxW6:b2nreh6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L61)):*
> ```XML
>   const mergedConfig: TrackerConfig = {
>     maxTracks: userConfig.maxTracks || defaultConfig.maxTracks,
>     maxAge: userConfig.maxAge || defaultConfig.maxAge,
> ```

Same as above.
___
*[pose-detection/src/movenet/detector_utils.ts, line 62 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNRhC7J1uAecHYXF-:-MggNRhC7J1uAecHYXF0:b2nreh6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L62)):*
> ```XML
>     maxTracks: userConfig.maxTracks || defaultConfig.maxTracks,
>     maxAge: userConfig.maxAge || defaultConfig.maxAge,
>     minSimilarity: userConfig.minSimilarity || defaultConfig.minSimilarity,
> ```

Same as above.
___
*[pose-detection/src/movenet/detector_utils.ts, line 63 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNwUw92iaNh_LfMDi:-MggNwUw92iaNh_LfMDj:brp8xdg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L63)):*
> ```XML
>     maxAge: userConfig.maxAge || defaultConfig.maxAge,
>     minSimilarity: userConfig.minSimilarity || defaultConfig.minSimilarity,
>     trackerParams: {
> ```

Given that there can be different tracker config (can be keypointTrackerConfig or boundingBoxTrackerConfig), maybe just pass along here: `trackerParams: userConfig.trackerParams`. And leave the validation work to the tracker.

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 86 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNiZnEe-MkRA30MyS:-MgglJoiAAZY8S9u3daW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector.ts#L86)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can you move this part to the validateModelConfig function?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 60 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNJ3EExI7D1W2qxYn:-MggkgZzBWgyzGNMuPB8:b-jk2mir) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L60)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Please explicitly check != null, because 0 is falsy in JS.
</blockquote></details>

I keep forgetting that. Done. (Although this code has been rewritten now.)
___
*[pose-detection/src/movenet/detector_utils.ts, line 61 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNPue1Mp4n2vnfxW5:-MggkqV85qC9miZz6Q4D:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L61)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 62 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNRhC7J1uAecHYXF-:-MggkqiD5KZE8bGUJHSU:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L62)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 63 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-MggNwUw92iaNh_LfMDi:-MggksIx-ylKg5eetwy8:b-3kkona) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4cd5995dcb7c3cee37f508033d559a6e25d0e73a/pose-detection/src/movenet/detector_utils.ts#L63)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Given that there can be different tracker config (can be keypointTrackerConfig or boundingBoxTrackerConfig), maybe just pass along here: `trackerParams: userConfig.trackerParams`. And leave the validation work to the tracker.
</blockquote></details>

The idea here is not to validate any config settings, but to provide defaults if the user didn't supply them. The tracker expects all values in trackerParams to be set.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 86 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh7PEzB-DbeSpKNW1Q:-Mgh7PEzB-DbeSpKNW1R:b6oc1gu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L86)):*
> ```
> defaultConfig.maxTracks
> ```
Can defaultConfig always just have the three common fields and not set trackerParams? This way, you can always start by just spread the defaultConfig: `const mergedConfig = {...defaultConfig}`
___
*[pose-detection/src/movenet/detector_utils.ts, line 105 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh5xUu6bIeQL8TSPa4:-Mgh5xUu6bIeQL8TSPa5:bfpq4h8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L105)):*
> ```
> defaultConfig: TrackerConfig, 
> ```
Why pass in defaultConfig, the keypointTracker merger should know where to get the default config, right?
___
*[pose-detection/src/movenet/detector_utils.ts, line 111 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh6EM7AdpvCXxeGG4q:-Mgh6EM7AdpvCXxeGG4r:b-nsqk28) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L111)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>   mergedConfig.keypointTrackerParams = {
>     keypointConfidenceThreshold:
>         defaultConfig.keypointTrackerParams.keypointConfidenceThreshold,
>     keypointFalloff: defaultConfig.keypointTrackerParams.keypointFalloff,
>     minNumberOfKeypoints:
>         defaultConfig.keypointTrackerParams.minNumberOfKeypoints
>   };
> ```
</details>

sugg:
```
mergedConfig.keypointTrackerParams = {...defaultConfig.keypointTrackerParams}
```
___
*[pose-detection/src/movenet/detector_utils.ts, line 135 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh6ZlFEFYG1YICrGAq:-Mgh6ZlFEFYG1YICrGAr:bocnc5h) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L135)):*
> ```
> defaultConfig: TrackerConfig,
> ```
Same, the boundingBox merger should know where to get the default config, no need to pass it in.
___
*[pose-detection/src/movenet/types.ts, line 25 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh71cx55WWZYUDjNTN:-Mgh71cx55WWZYUDjNTO:bb9cxp2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/types.ts#L25)):*
> ```
> bounding_box
> ```
Can this be boundingBox?

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 86 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh7PEzB-DbeSpKNW1Q:-Mgh8r7xBP9DzQrQBlSW:bfbtv1o) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L86)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> defaultConfig.maxTracks
> ```
Can defaultConfig always just have the three common fields and not set trackerParams? This way, you can always start by just spread the defaultConfig: `const mergedConfig = {...defaultConfig}`
</blockquote></details>

Unfortunately not, because these default parameters are likely not going to be the same for both trackers. Especially minSimilarity has a very different meaning for the keypoint tracker and the bounding box tracker.
___
*[pose-detection/src/movenet/detector_utils.ts, line 105 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh5xUu6bIeQL8TSPa4:-Mgh9_bE17weAyYiTQ1o:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L105)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> defaultConfig: TrackerConfig, 
> ```
Why pass in defaultConfig, the keypointTracker merger should know where to get the default config, right?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector_utils.ts, line 111 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh6EM7AdpvCXxeGG4q:-Mgh9laJ2nIwhXE7Okw2:b-q15s25) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L111)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>   mergedConfig.keypointTrackerParams = {
>     keypointConfidenceThreshold:
>         defaultConfig.keypointTrackerParams.keypointConfidenceThreshold,
>     keypointFalloff: defaultConfig.keypointTrackerParams.keypointFalloff,
>     minNumberOfKeypoints:
>         defaultConfig.keypointTrackerParams.minNumberOfKeypoints
>   };
> ```
sugg:
```
mergedConfig.keypointTrackerParams = {...defaultConfig.keypointTrackerParams}
```
</blockquote></details>

Thanks, that's much cleaner!
___
*[pose-detection/src/movenet/detector_utils.ts, line 135 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh6ZlFEFYG1YICrGAq:-Mgh9oS684n33KMhJtrS:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L135)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> defaultConfig: TrackerConfig,
> ```
Same, the boundingBox merger should know where to get the default config, no need to pass it in.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/types.ts, line 25 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh71cx55WWZYUDjNTN:-Mgh9tMlC7VjIeXNla-U:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/types.ts#L25)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> bounding_box
> ```
Can this be boundingBox?
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
Thank you Ard! LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-:-MghEq8KBMFrATlZ_VSf:b-11wnu1)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 86 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/780#-Mgh7PEzB-DbeSpKNW1Q:-MghEcSi7-g7elEbEZ9q:bx40ouy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/abc37ee6182a3926bb0087552ca348720e705471/pose-detection/src/movenet/detector_utils.ts#L86)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Unfortunately not, because these default parameters are likely not going to be the same for both trackers. Especially minSimilarity has a very different meaning for the keypoint tracker and the bounding box tracker.
</blockquote></details>

Got it, thanks for the explanation.

**Pull request merged**
