### PR TITLE
[pose-detection] Movenet multipose smoothing

### PR DESCRIPTION
**Pull request by ardoerlemans**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784)

### CODE REVIEW

**Review by ronnyvotel — CHANGES_REQUESTED** [review]
Looks great, thanks for doing this!

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-:-MgmBIrYDcP8NZWLPES1:b-86qbno)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/tracker.md, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mgm9sHh7BjCemTtlQ4q:-Mgm9sHiEDqCGtaVvHLe:b1vf4t1) ([raw file](https://github.com/tensorflow/tfjs-models/blob/5cadaa26472e8c084e20420281b3ace6838e28fd/pose-detection/src/calculators/tracker.md#L23)):*
> ```
> similarity\_fn
> ```
can you do me a favor and fix this to: similarity\_{fn}

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784)* status: 0 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/src/calculators/tracker.md, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mgm9sHh7BjCemTtlQ4q:-MgmCPi3CKObVCKpZywW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/5cadaa26472e8c084e20420281b3ace6838e28fd/pose-detection/src/calculators/tracker.md#L23)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> similarity\_fn
> ```
can you do me a favor and fix this to: similarity\_{fn}
</blockquote></details>

Done.

**Review by ronnyvotel — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-:-MgmEo2P4jjLDUtDL-RI:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

**Review by lina128 — APPROVED** [review]
Thank you for adding smoother, Ard, this is the last major piece to add. Overall LGTM, just have some nit comments below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-:-MgmFSs32o0udYlij6wi:b-iaq1c9)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans and @ronnyvotel)

___
*[pose-detection/src/calculators/tracker.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmEcRR1JemZpKoLCMP:-MgmEcRR1JemZpKoLCMQ:b-ftr19p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/calculators/tracker.ts#L84)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     const trackIDs: Set<number> = new Set();
>     for (const track of this.tracks) {
>       trackIDs.add(track.id);
>     }
>     return trackIDs;
> ```
</details>

```
return new Set(this.tracks.map(track => track.id));
```
___
*[pose-detection/src/movenet/detector.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmBl5X0u8VNehIfrta:-MgmBl5X0u8VNehIfrtb:bux5cwt) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L55)):*
> ```
> new KeypointsOneEuroFilter(KEYPOINT_FILTER_CONFIG)
> ```
Shall we only initialize it if single person model?
___
*[pose-detection/src/movenet/detector.ts, line 58 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmBuwLE0cx1km9u9Fi:-MgmBuwLE0cx1km9u9Fj:b99tfu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L58)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   private readonly cropRegionFilterYMin = new LowPassFilter(CROP_FILTER_ALPHA);
>   private readonly cropRegionFilterXMin = new LowPassFilter(CROP_FILTER_ALPHA);
>   private readonly cropRegionFilterYMax = new LowPassFilter(CROP_FILTER_ALPHA);
>   private readonly cropRegionFilterXMax = new LowPassFilter(CROP_FILTER_ALPHA);
> ```
</details>

Shall we only initialize it if single person model?
___
*[pose-detection/src/movenet/detector.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmC1In7y7RH5GD_pRH:-MgmC1In7y7RH5GD_pRI:b-xjuhsh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L65)):*
> ```
> keypointFilters
> ```
sugg: rename to keypointFilterMap and add annotation the key is trackerId.
___
*[pose-detection/src/movenet/detector.ts, line 87 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mglzq-x45LtDfKuPyQN:-Mglzq-x45LtDfKuPyQO:bw2b2lg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L87)):*
> ```
> this.multiPoseModel === true
> ```
multiPoseModel and enableTracking are both boolean types, so you can just write `this.multiPoseModel && this.enableTracking`
___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mgm-nRJ1k97lpGzqrqf:-Mgm-nRJ1k97lpGzqrqg:be0kmix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L90)):*
> ```
> MoveNetTrackerType
> ```
Is it better to move TrackerType definition to the shared folder?
___
*[pose-detection/src/movenet/detector.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mgm-zU52-LUQl48DPWI:-Mgm-zU52-LUQl48DPWJ:b-gezfqg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L93)):*
> ```
> if (this.enableSmoothing === true)
> ```
`if (this.enableSmoothing)`
___
*[pose-detection/src/movenet/detector.ts, line 431 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmDuN46kc7WAdKJLBC:-MgmDuN46kc7WAdKJLBD:bkkr9ty) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L431)):*
> ```
> filterID
> ```
sugg: filterID -> poseId

**Review by ardoerlemans — COMMENTED** [review]
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-:-MgmIo6h4ZjBxcyYqYCx:b-hlc8bm)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/src/calculators/tracker.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmEcRR1JemZpKoLCMP:-MgmGXnk9tRVJ1pZtUYK:b-kkqi67) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/calculators/tracker.ts#L84)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>     const trackIDs: Set<number> = new Set();
>     for (const track of this.tracks) {
>       trackIDs.add(track.id);
>     }
>     return trackIDs;
> ```
```
return new Set(this.tracks.map(track => track.id));
```
</blockquote></details>

Cool, much cleaner. Thanks!
___
*[pose-detection/src/movenet/detector.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmBl5X0u8VNehIfrta:-MgmH4hSC0Mx5afWBbQD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> new KeypointsOneEuroFilter(KEYPOINT_FILTER_CONFIG)
> ```
Shall we only initialize it if single person model?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 58 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmBuwLE0cx1km9u9Fi:-MgmH4xK6C1jx8VvlosY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L58)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>   private readonly cropRegionFilterYMin = new LowPassFilter(CROP_FILTER_ALPHA);
>   private readonly cropRegionFilterXMin = new LowPassFilter(CROP_FILTER_ALPHA);
>   private readonly cropRegionFilterYMax = new LowPassFilter(CROP_FILTER_ALPHA);
>   private readonly cropRegionFilterXMax = new LowPassFilter(CROP_FILTER_ALPHA);
> ```
Shall we only initialize it if single person model?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmC1In7y7RH5GD_pRH:-MgmHL2N-ZS1A5Ll886k:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L65)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> keypointFilters
> ```
sugg: rename to keypointFilterMap and add annotation the key is trackerId.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 87 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mglzq-x45LtDfKuPyQN:-MgmHWl69EdIaZLq3EWG:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L87)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> this.multiPoseModel === true
> ```
multiPoseModel and enableTracking are both boolean types, so you can just write `this.multiPoseModel && this.enableTracking`
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mgm-nRJ1k97lpGzqrqf:-MgmHXdy1rW3obdKr49P:biwps36) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L90)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> MoveNetTrackerType
> ```
Is it better to move TrackerType definition to the shared folder?
</blockquote></details>

This actually depends on which tracker is supported by the detector. MoveNet only supports these two trackers, so it needs its own local list of trackers that can be chosen from in the configuration.
___
*[pose-detection/src/movenet/detector.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-Mgm-zU52-LUQl48DPWI:-MgmHjnI7IM8lV5n6oic:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L93)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> if (this.enableSmoothing === true)
> ```
`if (this.enableSmoothing)`
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 431 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-MgmDuN46kc7WAdKJLBC:-MgmIAOx1pXTQX3Wsvpx:brwinwt) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3abfeae595c888fde5dca5096d629c21efb609b2/pose-detection/src/movenet/detector.ts#L431)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> filterID
> ```
sugg: filterID -> poseId
</blockquote></details>

Updated to trackID to match the comment for keypointFilterMap.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/784#-:-MgmJPG2EXTLEbkSV5T9:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

**Pull request merged**
