### PR TITLE
[posedetection] PoseNet single pose migration

### PR DESCRIPTION
**Pull request by lina128**
This PR includes below changes:
1. Add PoseNet single pose estimation.
2. Add convertImageToTensor, to be shared by all image processing models.
2. Setup test.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611)

### CODE REVIEW

**Review by mhays-google — COMMENTED** [review]
> Reviewed 4 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @pyu10055)

___
*[pose-detection/src/constants.ts, line 17 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxWMCbAXvWZYXilRAX:-MVxWMCbAXvWZYXilRAY:bazwyki) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/constants.ts#L17)):*
> ```XML
>  * =============================================================================
>  */
> export const COCO_KEYPOINTS_NUM = 17;
> ```

Consider using an object whose keys are the names of the keypoints and whose values are the indexes.  This will allow you to create multiple keypoint locators (maybe just the left verus the right).  And you can use Objects.keys(x).length to get the size of the collections (for example).  This would prevent any de-sync issues with KEYPOINTS_NUM and the size of the array.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @mhays-google)

___
*[pose-detection/src/create_detector.ts, line 35 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVx27u--9Y3JfSXNvBy:-MVx27u--9Y3JfSXNvBz:bggc82i) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/create_detector.ts#L35)):*
> ```XML
>       return PosenetDetector.load(modelConfig);
>     default:
>       throw new Error(`${model} is not a valid package name.`);
> ```

'not a supported model name'?
___
*[pose-detection/src/pose_detector.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVx2ly3EXJU00Ni8Xfy:-MVx2ly3EXJU00Ni8Xfz:b3fr328) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/pose_detector.ts#L48)):*
> ```XML
>   }
> 
>   abstract async estimatePoses(
> ```

this is a multiple pose estimation API? should the name be more clear on that (estimateMultiPoses)?
___
*[pose-detection/src/calculators/convert_image_to_tensor.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxRYrgEMnJjsDuNqSx:-MVxRYrgEMnJjsDuNqSy:byes43s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/convert_image_to_tensor.ts#L31)):*
> ```XML
>  *      inputResolution: The target height and width.
>  *      keepAspectRatio?: Whether target tensor should keep aspect ratio.
>  * @param normRect
> ```

doc for param normRect?
___
*[pose-detection/src/calculators/image_utils.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxXwnFEP4GFw_tLJr6:-MVxXwnFEP4GFw_tLJr7:b5pjnnk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/image_utils.ts#L50)):*
> ```XML
>   const fromRange = fromMax - fromMin;
>   const toRange = toMax - toMin;
>   const scale = toRange / fromRange;
> ```

validate fromRange is not 0?
___
*[pose-detection/src/calculators/image_utils.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxY2FN9xgSfOkj_58u:-MVxY2FN9xgSfOkj_58v:b2h337c) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/image_utils.ts#L90)):*
> ```XML
>   const targetW = targetSize.width;
> 
>   const tensorAspectRatio = targetH / targetW;
> ```

verify targetH, targetW, roi.h and roi.w are not 0
___
*[pose-detection/src/calculators/image_utils.ts, line 224 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxYEsN4lIjs7I_6BeZ:-MVxYEsN4lIjs7I_6Be_:b-6673qd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/image_utils.ts#L224)):*
> ```XML
>   // So we need to use factor imageSize.width for a0, a1 and a2, similarly
>   // we need to use factor imageSize.height for b0, b1 and b2.
>   const a0 = (1 / inputResolution.width) * a * c * flip * g * imageSize.width;
> ```

verify inputResolution.width and height are not 0
___
*[pose-detection/src/posenet/detector.ts, line 118 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxXIWz7bvaAXmdIxos:-MVxXIWz7bvaAXmdIxot:b62af0v) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/posenet/detector.ts#L118)):*
> ```XML
>    * @return An pose and its scores, containing keypoints and
>    * the corresponding keypoint scores.  The positions of the keypoints are
>    * in the same scale as the original image
> ```

missing .
___
*[pose-detection/src/posenet/detector.ts, line 135 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxWf9S9eeS20oQiPWS:-MVxWf9S9eeS20oQiPWT:bvv6e50) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/posenet/detector.ts#L135)):*
> ```XML
>     }
> 
>     // ==== ConvertImageToTensor =============================================
> ```

These comments with `===` looks like debugging info, does not seem to help to explain the code.

**Review by pyu10055 — COMMENTED** [review]
Nice and clean APIs, thanks you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-:-MVxYh-27aBSToua3J14:b5x974e)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @mhays-google)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/constants.ts, line 17 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxWMCbAXvWZYXilRAX:-MVxiDPB8gHbhEofpczN:b-7cawex) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/constants.ts#L17)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

Consider using an object whose keys are the names of the keypoints and whose values are the indexes.  This will allow you to create multiple keypoint locators (maybe just the left verus the right).  And you can use Objects.keys(x).length to get the size of the collections (for example).  This would prevent any de-sync issues with KEYPOINTS_NUM and the size of the array.
</blockquote></details>

Good idea. Use COCO_KEYPOINTS.length in the code and removed the hard-coded length here.
___
*[pose-detection/src/create_detector.ts, line 35 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVx27u--9Y3JfSXNvBy:-MVxiOo_5awRso54ZYWA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/create_detector.ts#L35)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

'not a supported model name'?
</blockquote></details>

Done.
___
*[pose-detection/src/pose_detector.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVx2ly3EXJU00Ni8Xfy:-MVxiPtB7awVa_egdYNp:bo6yz4j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/pose_detector.ts#L48)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this is a multiple pose estimation API? should the name be more clear on that (estimateMultiPoses)?
</blockquote></details>

Multiple pose and single pose will share the same API. Whether it returns 1 or more poses depend on the maxPoses option. Some model can handle multiple poses naturally, so it doesn't make sense to have two api entries. Also, as we have more config options, it's not viable to give one api for each permutation of options (imagine estimatePoseLiteModel, estimatePoseHeavyModel, estimatePoseMultiple, etc. etc.), imo it is better to provide a simple api and config options and hide the logic inside.
___
*[pose-detection/src/calculators/convert_image_to_tensor.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxRYrgEMnJjsDuNqSx:-MVxjXnKCeJxIGk293yc:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/convert_image_to_tensor.ts#L31)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

doc for param normRect?
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/image_utils.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxXwnFEP4GFw_tLJr6:-MVxk-EY4HGwajEQYTmQ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/image_utils.ts#L50)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

validate fromRange is not 0?
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/image_utils.ts, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxY2FN9xgSfOkj_58u:-MVxkQb_BgyaKJQj04QR:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/image_utils.ts#L90)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

verify targetH, targetW, roi.h and roi.w are not 0
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/image_utils.ts, line 224 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxYEsN4lIjs7I_6BeZ:-MVxlWai7PFbfZzHAmhu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/calculators/image_utils.ts#L224)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

verify inputResolution.width and height are not 0
</blockquote></details>

Done.
___
*[pose-detection/src/posenet/detector.ts, line 118 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxXIWz7bvaAXmdIxos:-MVxn8ncBw1ZvTXJLE_t:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/posenet/detector.ts#L118)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

missing .
</blockquote></details>

Done.
___
*[pose-detection/src/posenet/detector.ts, line 135 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVxWf9S9eeS20oQiPWS:-MVxnOE37tlM_EnEzaS4:bss4a2b) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/posenet/detector.ts#L135)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

These comments with `===` looks like debugging info, does not seem to help to explain the code.
</blockquote></details>

Removed.

**Review by lina128 — COMMENTED** [review]
Thank you for the review @pyu10055 and @mhays-google ! PTAL.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-:-MVxncdS2z82e9YIirXo:b-2qltvo)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

**Review by pyu10055 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-:-MW08ei00ugagb8EF7dw:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @mhays-google)

___
*[pose-detection/src/pose_detector.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/611#-MVx2ly3EXJU00Ni8Xfy:-MW07USr7dZ4keogRxId:bfb09az) ([raw file](https://github.com/tensorflow/tfjs-models/blob/bc070c9508e17e64772ad96b0f37b5c24c1b5de5/pose-detection/src/pose_detector.ts#L48)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Multiple pose and single pose will share the same API. Whether it returns 1 or more poses depend on the maxPoses option. Some model can handle multiple poses naturally, so it doesn't make sense to have two api entries. Also, as we have more config options, it's not viable to give one api for each permutation of options (imagine estimatePoseLiteModel, estimatePoseHeavyModel, estimatePoseMultiple, etc. etc.), imo it is better to provide a simple api and config options and hide the logic inside.
</blockquote></details>

There is benefit to have sugar API to hide the details of the options. If the common use case is to detect a single pose, having an API that pre-populate the options would be helpful to the users. But SG start with this generic API.

**Pull request merged**
