### PR TITLE
Alert user when getUserMedia throws an error

### PR DESCRIPTION
**Pull request by iloahz**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/21)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[posenet/demos/camera.js, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/21#-LD1wE_QDiCF6smUqA1m:-LD1wE_QDiCF6smUqA1n:b-6wluqm) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ad066e6eea73987e204b2db895fb9a00f4dfad3a/posenet/demos/camera.js#L291)):*
> ```JavaScript
>     video = await loadVideo();
>   } catch(e) {
>     const errorMessage = "This browser does not support video capture, or this device does not have a camera";
> ```

Instead of alerting here, would you put an element in the DOM that has this message? Typically we try to stay away from "alert" :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/21)*

**Comment by oveddan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[posenet/demos/camera.js, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/21#-LD1wE_QDiCF6smUqA1m:-LD4rzBQBZnQ14h3X4k8:b-2wzwns) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ad066e6eea73987e204b2db895fb9a00f4dfad3a/posenet/demos/camera.js#L291)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Instead of alerting here, would you put an element in the DOM that has this message? Typically we try to stay away from "alert" :)
</blockquote></details>

We actually already were alerting.  But I agree changing this to an error element would be preferable.

Looking at the existing code it is odd how it returns a rejected promise, but then the error is caught and the logged with `console.error` instead of just  bubbling up/being re-thrown.

So I think the right thing would be to show an error div, and then just re-throw the original error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/21)*

**Comment by iloahz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[posenet/demos/camera.js, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/21#-LD1wE_QDiCF6smUqA1m:-LDAPcAn5Odsu-u6VaTj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ad066e6eea73987e204b2db895fb9a00f4dfad3a/posenet/demos/camera.js#L291)):*
<details><summary><i>Previously, oveddan (Dan Oved) wrote…</i></summary><blockquote>

We actually already were alerting.  But I agree changing this to an error element would be preferable.

Looking at the existing code it is odd how it returns a rejected promise, but then the error is caught and the logged with `console.error` instead of just  bubbling up/being re-thrown.

So I think the right thing would be to show an error div, and then just re-throw the original error.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/21)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/21#-:-LDEDvEV7yiGIVBHSWUf:b-jbsf8z)*

**Pull request merged**
