### PR TITLE
Add ARPortraitDepth implementation

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1007)

### CODE REVIEW

**Review by ruofeidu — COMMENTED** [review]
Please replace [portrait.jpg](https://github.com/tensorflow/tfjs-models/pull/1007/files#diff-3b7480e002447758ec0c26bcfdc7f66bc41f2c08c4d886fc7790f4ff17e4a33f) with a segmented image, as we strongly recommend using depth after body segmentation model for robustness.

**Review by lina128 — CHANGES_REQUESTED** [review]
Thank you Ahmed! Great work! See my detailed comment below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-:-N1KFwyD8XCsECB0ZzEq:b-rop1wu)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBkz53XG7DptTske8:-N1KBkz53XG7DptTske9:be3t0qx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L96)):*
> ```XML
>     col = col.map((value, i) => value + RHS[i]);
>     if (col[0] > 1 || col[1] > 1 || col[2] > 1) {
>       console.log(col.map((value, i) => value - RHS[i]));
> ```

Remove debugging code?



_Code quote:_
```XML
    if (col[0] > 1 || col[1] > 1 || col[2] > 1) {
      console.log(col.map((value, i) => value - RHS[i]));
      console.log(scale + ' ' + 31 + ' ' + x);
    }
```
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 116 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBH0h3BSVDW42-4HP:-N1KBH0h3BSVDW42-4HQ:b2ni53j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L116)):*
> ```XML
>   });
> 
>   fit('estimateDepth does not leak memory.', async () => {
> ```

it?



_Code quote:_
```XML
fit
```
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 139 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBISn7_JUsqUfFiBv:-N1KBISoDfO81ioIG_3n:b32wog) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L139)):*
> ```XML
>   });
> 
>   fit('throws error when minDepth is not set.', async (done) => {
> ```

it



_Code quote:_
```XML
fit
```
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 151 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBKCO3rIDg9h4TYkq:-N1KBKCO3rIDg9h4TYkr:b32wog) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L151)):*
> ```XML
>   });
> 
>   fit('throws error when minDepth is greater than maxDepth.', async (done) => {
> ```

it



_Code quote:_
```XML
fit
```
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 201 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KC6dM3anGcWSiqbfM:-N1KC6dN4EzgzXZAKuTO:bbhosrk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L201)):*
> ```XML
>     const actualDepthValues = await result.toTensor();
>     const coloredDepthValues =
>         actualDepthValues.arraySync().flat().map(value => turboPlus(value));
> ```

Is dataSync() === arraySync().flat()?



_Code quote:_
```XML
arraySync().flat()
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 100 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KE9sX9jmuBSGvFnir:-N1KE9sX9jmuBSGvFnis:brb7v27) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L100)):*
> ```XML
>     const transformInput = transformValueRange(0, 255, 0, 1);
>     this.minDepth;
>     this.maxDepth;
> ```

Remove this two lines?



_Code quote:_
```XML
    this.minDepth;
    this.maxDepth;
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 103 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KCbSR5rNmFNllH3Nm:-N1KCbSR5rNmFNllH3Nn:bgtc9gd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L103)):*
> ```XML
> 
>     const depthTensor = tf.tidy(() => {
>       const imageResized = tf.image.resizeBilinear(image3d, [256, 192]);
> ```

I thought you had a body/face detector before the depth model so that you can crop a more accurate area for the model. Or is it not in v0.0.1? @ruofeidu What's the decision for initial launch?



_Code quote:_
```XML
tf.image.resizeBilinear(image3d, [256, 192]);
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 104 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KD0yd9d7wqo6iQCSs:-N1KD0yd9d7wqo6iQCSt:b-2ehf5j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L104)):*
> ```XML
>     const depthTensor = tf.tidy(() => {
>       const imageResized = tf.image.resizeBilinear(image3d, [256, 192]);
>       // Masks the image
> ```

This annotation doesn't look like describe the line of code below.



_Code quote:_
```XML
Masks the image
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KDBmG3yt244cwTsTM:-N1KDBmG3yt244cwTsTN:bpilol0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L108)):*
> ```XML
>           tf.mul(imageResized, transformInput.scale), transformInput.offset);
> 
>       // Runs the model.
> ```

Remove this annotation.



_Code quote:_
```XML
Runs the model.
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KEY9j9JhG8_rqXUjd:-N1KEY9j9JhG8_rqXUje:bw0g3i4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L111)):*
> ```XML
>       const batchInput = tf.expandDims(imageNormalized);
> 
>       // Depth prediction.
> ```

Can you add an annotation about the shape of depth4D? Is it [1, height, width, 1]?



_Code quote:_
```XML
// Depth prediction.
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 115 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KEkQMBRr5z16P0maS:-N1KEkQMBRr5z16P0maT:b-xdizxf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L115)):*
> ```XML
> 
>       // Remove batch dimension.
>       const depth3D = tf.squeeze(depth4D, [0]);
> ```

If we just need a 2D, does reshape work if depth4D shape is [1, height, width, 1]? Or squeeze(depth4D, [0, 2]). Internally, it does reshape.



_Code quote:_
```XML
tf.squeeze(depth4D, [0]);
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 118 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KDhPI5gEEgPrZB0Mj:-N1KDhPI5gEEgPrZB0Mk:b-9ur45z) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L118)):*
> ```XML
> 
>       // Output is roughly in [0,2] range, normalize to [0,1]
>       const depthNormalized = tf.div(depth3D, 2);
> ```

Do we need to do this if given the next line of code, why not directly transform to the [minDepth, maxDepth] range?



_Code quote:_
```XML
tf.div(depth3D, 2);
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 122 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KDbHt3yC_TZr0PcR4:-N1KDbHt3yC_TZr0PcR5:bd1fb8e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L122)):*
> ```XML
>       // Normalize to user requirements.
>       const result = tf.div(
>                          tf.sub(depthNormalized, this.minDepth),
> ```

Can we use transformValueRange(...)?



_Code quote:_
```XML
      const result = tf.div(
                         tf.sub(depthNormalized, this.minDepth),
                         this.maxDepth - this.minDepth) as tf.Tensor3D;
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 133 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KFA543iFv4QrJm8aI:-N1KFA55D5NZptyEM-qJ:b8z72p3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L133)):*
> ```XML
> 
>       // Remove channel dimension.
>       const resultSqueezed = tf.squeeze(resultResized, [2]);
> ```

Can we combine this squeeze with the squeeze above?



_Code quote:_
```XML
const resultSqueezed = tf.squeeze(resultResized, [2]);
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 168 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KFhMY1iv-opO7Ds-0:-N1KFhMY1iv-opO7Ds-1:bg6do64) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L168)):*
> ```XML
>       await tfconv.loadGraphModel(config.modelUrl, {fromTFHub: modelFromTFHub});
> 
>   return new ARPortraitDepthEstimator(model, config.minDepth, config.maxDepth);
> ```

If minDepth/maxDepth is only related to per prediction not the model, should it be a estimationConfig instead of modelConfig?



_Code quote:_
```XML
config.minDepth, config.maxDepth)
```

**Review by jinjingforever — APPROVED** [review]
LGTM after Na's comments are addressed

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1007)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @ruofeidu)

___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBkz53XG7DptTske8:-N1LFDjb8TcdzDvXUqJl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L96)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Remove debugging code?
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 116 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBH0h3BSVDW42-4HP:-N1LFFHa1_4jHYlXsGgO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L116)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

it?
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 139 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBISn7_JUsqUfFiBv:-N1LFFjiEmQIvAfodqhM:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L139)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

it
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 151 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KBKCO3rIDg9h4TYkq:-N1LFGJi9EvQcjPm7pjB:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L151)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

it
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 201 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KC6dM3anGcWSiqbfM:-N1LFGpX8bgbIcD7AMZr:b-g5mvrb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L201)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Is dataSync() === arraySync().flat()?
</blockquote></details>

No because dataSync returns a TypedArray and when you use map on a typed array you have to return a typed array, however turboPlus is expanding the dimension of the values so this is not possible
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 100 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KE9sX9jmuBSGvFnir:-N1LFTd50gca05GxwKR8:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L100)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Remove this two lines?
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 103 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KCbSR5rNmFNllH3Nm:-N1LFU4z5_BVn4tUF-Hb:bu6xyhx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L103)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

I thought you had a body/face detector before the depth model so that you can crop a more accurate area for the model. Or is it not in v0.0.1? @ruofeidu What's the decision for initial launch?
</blockquote></details>

I asked Ruofei and Yinda and they said with segmentation is better, added to PR
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 104 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KD0yd9d7wqo6iQCSs:-N1LFc8VDIgFhvOHXDC-:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L104)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This annotation doesn't look like describe the line of code below.
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KDBmG3yt244cwTsTM:-N1LFcMwBmoP0BJYfrgn:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L108)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Remove this annotation.
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 115 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KEkQMBRr5z16P0maS:-N1LFhXO0JR5MjxxY4jz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L115)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If we just need a 2D, does reshape work if depth4D shape is [1, height, width, 1]? Or squeeze(depth4D, [0, 2]). Internally, it does reshape.
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 118 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KDhPI5gEEgPrZB0Mj:-N1LFjQ61BnZoW0R6_0I:bci2hir) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L118)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Do we need to do this if given the next line of code, why not directly transform to the [minDepth, maxDepth] range?
</blockquote></details>

I switched to transform, although the transform is from [minDepth, maxDepth] rather than to.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 122 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KDbHt3yC_TZr0PcR4:-N1LFpua3pHeqCgRPamZ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L122)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we use transformValueRange(...)?
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 133 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KFA543iFv4QrJm8aI:-N1LFqQT0JJ_yorgOIc4:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L133)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we combine this squeeze with the squeeze above?
</blockquote></details>

Done.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 168 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KFhMY1iv-opO7Ds-0:-N1LFrFpEh7Sb8p99Kvu:bddi5io) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/estimator.ts#L168)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If minDepth/maxDepth is only related to per prediction not the model, should it be a estimationConfig instead of modelConfig?
</blockquote></details>

That's a good point I will ask Ruofei

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1007)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @ruofeidu)

___
*[`depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts` line 201 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1KC6dM3anGcWSiqbfM:-N1PLU-u2Z4_uSnPGMac:bcr5s31) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3db36493b6b57b13a6da16475f9c41ffb6544f24/depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts#L201)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

No because dataSync returns a TypedArray and when you use map on a typed array you have to return a typed array, however turboPlus is expanding the dimension of the values so this is not possible
</blockquote></details>

Got it, thanks.
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 105 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1PMYaY4kY1VgNTeCQ-:-N1PMYaZ1jePo3fK5Pdc:b-wy8a3e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d134ce5ebac8df28b5f24a2d8046ff85e28772d/depth-estimation/src/ar_portrait_depth/estimator.ts#L105)):*
> ```XML
>     masked.width = PORTRAIT_WIDTH;
>     masked.height = PORTRAIT_HEIGHT;
>     // Draw the mask onto the image on a canvas.  With opacity set to 0.7
> ```

This part is mainly prepare a masked image for the model, right? It seems it downloads data to cpu, also create a canvas, these are not very efficient. Is it possible to do this on GPU? The two inputs are imageTensor and segmentationTensor, both should have the same shape of texture, and you just write a custom shader to mix this two on a new texture. The custom shader's logic should be fairly straightforward, just check mask > 0.5 or not and use image's rgb value as output or black, basically the example shader in the gpu example (https://github.com/tensorflow/tfjs-examples/blob/master/gpu-pipeline/gl-shaders.js#L39-L50), or something similar if you want a soft mask (blur on edge). You can register the custom shader as how you do it for the segmentation (https://github.com/tensorflow/tfjs-models/blob/ccfcb2ab9b479b7e053f8eafaf68bd75a71c6551/shared/calculators/segmentation_smoothing.ts#L97-L136) What do you think?



_Code quote:_
```XML
    // Convert the segmentation into a mask to darken the background.
    const foregroundColor = {r: 0, g: 0, b: 0, a: 0};
    const backgroundColor = {r: 0, g: 0, b: 0, a: 255};
    const backgroundDarkeningMask = await bodySegmentation.toBinaryMask(
        segmentation, foregroundColor, backgroundColor);

    segmentation.forEach(
        singleSegmentation => singleSegmentation.mask.toTensor().then(
            tensor => tensor.dispose()));

    const opacity = 1.0;
    const maskBlurAmount = 0;
    const flipHorizontal = false;
    const masked = document.createElement('canvas');
    masked.width = PORTRAIT_WIDTH;
    masked.height = PORTRAIT_HEIGHT;
    // Draw the mask onto the image on a canvas.  With opacity set to 0.7
    // and maskBlurAmount set to 3, this will darken the background and blur
    // the darkened background's edge.
    await bodySegmentation.drawMask(
        masked, image, backgroundDarkeningMask, opacity, maskBlurAmount,
        flipHorizontal);
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 143 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1PM3XR9Ujlzt59Dvs7:-N1PM3XR9Ujlzt59Dvs8:b-kilimi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/4d134ce5ebac8df28b5f24a2d8046ff85e28772d/depth-estimation/src/ar_portrait_depth/estimator.ts#L143)):*
> ```XML
>       // Output is roughly in [0,2] range, so half the scale factor to put it in
>       // [0,1] range first.
>       const scale = depthTransform.scale / 2;
> ```

How come depthTransform is in range [0, 2], isn't it transformed to range 0 to 1?



_Code quote:_
```XML
depthTransform
```

**Review by ruofeidu — APPROVED** [review]

**Review by lina128 — APPROVED** [review]
I left some minor comments, overall LGTM. After address the comments, can merge. This is great, thank you Ahmed!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-:-N1eyrQV1BAAo3n42VQv:b-jdu8o)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @ruofeidu)

___
*[`depth-estimation/package.json` line 19 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1evGiEDakBvhqDtPTz:-N1evGiEDakBvhqDtPU-:b-8ktc8f) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/package.json#L19)):*
> ```JSON
>     "@tensorflow/tfjs-converter": "^3.15.0",
>     "@tensorflow/tfjs-core": "^3.15.0",
>     "@tensorflow-models/body-segmentation": "^1.0.0"
> ```

1.0.1



_Code quote:_
```JSON
1.0.0
```
___
*[`depth-estimation/src/ar_portrait_depth/estimator.ts` line 104 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1evs9d85_yY2a1vH7n:-N1evs9d85_yY2a1vH7o:bj6ei44) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/src/ar_portrait_depth/estimator.ts#L104)):*
> ```XML
> 
>     const segmentation = segmentations[0];
>     const segmentationTensor = await segmentation.mask.toTensor();
> ```

This can be null, check null first.



_Code quote:_
```XML
segmentation
```
___
*[`depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts` line 26 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1exGE09qrymuCuC4Qf:-N1exGE09qrymuCuC4Qg:b-o3vct9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts#L26)):*
> ```XML
>  * @param segmentation Segmentation mask of foreground/background.
>  *
>  * @returns Segmented mask.
> ```

Masked image.



_Code quote:_
```XML
Segmented mask
```
___
*[`depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts` line 29 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1exOvP0oIKiDm6-Wuz:-N1exOvP0oIKiDm6-Wv-:b-mnr48y) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts#L29)):*
> ```XML
>  */
> // ref:
> // https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/segmentation_smoothing_calculator.cc
> ```

Shall we use this method for to BinaryMask in bodySegmentation? This can be done in a separate PR. Just some thoughts.



_Code quote:_
```XML
segmentation_smoothing_calculator
```
___
*[`depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts` line 34 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1ey3qP7SAM0ZWtMvzy:-N1ey3qP7SAM0ZWtMvzz:bxyjlg5) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts#L34)):*
> ```XML
>   if (tf.getBackend() === 'webgl') {
>     // Same as implementation in the else case but reduces number of shader
>     // calls to 1 instead of 17.
> ```

// Same as implementation in the else case but in one custom shader on GPU.



_Code quote:_
```XML
    // Same as implementation in the else case but reduces number of shader
    // calls to 1 instead of 17.
```
___
*[`depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts` line 37 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1exzZa6ycR5fwphtbt:-N1exzZa6ycR5fwphtbu:bmgc61t) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts#L37)):*
> ```XML
>     return segmentForegroundWebGL(image, segmentation);
>   }
>   const [height, width, channels] = image.shape;
> ```

Should these be wrapped in tf.tidy?



_Code quote:_
```XML
  const [height, width, channels] = image.shape;
  // Extract red channel which stores probability
  const probability = tf.slice(segmentation, 0, [height, width, 1]);
  // Round to make a binary mask that can be multiplied with image.
  const binaryMask = tf.round(probability);
  // Make the same shape as input image.
  const imageBinaryMask = tf.tile(binaryMask, [1, 1, channels]);
  return tf.mul(image, imageBinaryMask);
```
___
*[`depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts` line 69 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/1007#-N1eybnH39V0WvmT5xnk:-N1eybnH39V0WvmT5xnl:bwmqofd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f3cf8c6219b4cb7011f619d0b4fdf047533cefec/depth-estimation/src/ar_portrait_depth/calculators/segment_foreground.ts#L69)):*
> ```XML
>     const outputTensorInfo =
>         webglBackend.compileAndRun(program, [image, segmentation]);
>     return tf.engine().makeTensorFromDataId(
> ```

After the latest release from tfjs, we need to update this: https://github.com/tensorflow/tfjs/pull/6355 (not released yet).



_Code quote:_
```XML
makeTensorFromDataId
```

**Review by ruofeidu — APPROVED** [review]

**Pull request merged**
