### PR TITLE
[pose-detection] Use tracker from MoveNet code

### PR DESCRIPTION
**Pull request by ardoerlemans**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776)

### CODE REVIEW

**Review by ronnyvotel — APPROVED** [review]
Thanks for doing this. Looks great!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-:-MgS3hRp8C0iSUnt7VX1:b-wipabi)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — COMMENTED** [review]
Thank you Ard! See my comments below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-:-MgSKEz03jRDTsc78J9-:bdvh3ug)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans)

___
*[pose-detection/src/calculators/tracker.ts, line 123 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSK4-kExvYNsUUlcEW:-MgSK4-kExvYNsUUlcEX:bft0f0m) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/calculators/tracker.ts#L123)):*
> ```XML
>         // Make sure to copy the Keypoint objects.
>         this.tracks[maxTrackIndex].keypoints =
>             [...poses[detectionIndex].keypoints].map(i => ({...i}));
> ```

Why do you need a deep copy?
___
*[pose-detection/src/movenet/detector.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSHcgPDAMCUZrErTn1:-MgSHcgPDAMCUZrErTn2:b-4px4cl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector.ts#L62)):*
> ```XML
>   // Global states for multi-person model.
>   private readonly keypointTracker: KeypointTracker =
>       new KeypointTracker(DEFAULT_TRACKER_CONFIG);
> ```

Should you only set the tracker if it's multipose?
___
*[pose-detection/src/movenet/detector.ts, line 401 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSInXEExixVQ9nZVc0:-MgSInXEExixVQ9nZVc1:b47cp66) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector.ts#L401)):*
> ```XML
>     }
> 
>     // Tracker wants a timestamp in milliseconds.
> ```

Should we be consistent so that all our internal time is based on microseconds? It will be less error prone. 
___
*[pose-detection/src/movenet/detector_utils.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSJ9Og8aV7tk7Z6Y6v:-MgSJ9Og8aV7tk7Z6Y6w:b9stacw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector_utils.ts#L37)):*
> ```XML
>   }
> 
>   if (config.minPoseScore &&
> ```

!= null, 0 will be falsy.

**Review by ardoerlemans — COMMENTED** [review]
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-:-MgSOGGY4eXshob86ZUU:b-hlc8bm)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/tracker.ts, line 123 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSK4-kExvYNsUUlcEW:-MgSKwaC29phcHAQ3tEP:bdppv8p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/calculators/tracker.ts#L123)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Why do you need a deep copy?
</blockquote></details>

Because if the tracker stores references, the keypoints can be modified after the tracker has stored the references (and in our case, they will be converted from normalized to image coordinates).
___
*[pose-detection/src/movenet/detector.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSHcgPDAMCUZrErTn1:-MgSLjPGD3AgUKNmfQ_f:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector.ts#L62)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should you only set the tracker if it's multipose?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 401 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSInXEExixVQ9nZVc0:-MgSMWcC8PzN6E8UNBKP:b2haqt8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector.ts#L401)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should we be consistent so that all our internal time is based on microseconds? It will be less error prone. 
</blockquote></details>

That's actually not as easy as it sounds. The tracker (and its tests) are millisecond-based, so it would require quite a bit of work to rewrite it to use microseconds.

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSJ9Og8aV7tk7Z6Y6v:-MgSRFLv9_5BYttsRhRl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector_utils.ts#L37)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

!= null, 0 will be falsy.
</blockquote></details>

Done.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/tracker.ts, line 123 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSK4-kExvYNsUUlcEW:-MgSRlDQ4ccUEOgG14Gh:bfztxk0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/calculators/tracker.ts#L123)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Because if the tracker stores references, the keypoints can be modified after the tracker has stored the references (and in our case, they will be converted from normalized to image coordinates).
</blockquote></details>

Can you pass a `normalized` flag to tracker, and then in tracker, you always de-normalize if normalized is true, and then do the computation, before return, you always normalize if normalized is true. Similar to what this smoother does: https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/src/calculators/keypoints_smoothing.ts#L78
___
*[pose-detection/src/movenet/detector.ts, line 401 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSInXEExixVQ9nZVc0:-MgSSMfd91JBclcVwPcn:bpp9onf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector.ts#L401)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

That's actually not as easy as it sounds. The tracker (and its tests) are millisecond-based, so it would require quite a bit of work to rewrite it to use microseconds.
</blockquote></details>

We can do the refactor in another PR.

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/calculators/tracker.ts, line 123 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSK4-kExvYNsUUlcEW:-MgSSjTh2Z0CEitSbtiK:b-3bq7iv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/calculators/tracker.ts#L123)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can you pass a `normalized` flag to tracker, and then in tracker, you always de-normalize if normalized is true, and then do the computation, before return, you always normalize if normalized is true. Similar to what this smoother does: https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/src/calculators/keypoints_smoothing.ts#L78
</blockquote></details>

It's actually not about the tracker using normalized coordinates or image coordinates (it can handle both), it's about values that change after the tracker has stored them. The values that the tracker stores shouldn't change anymore, otherwise the tracker can't know what it is comparing against the next time it is called.
___
*[pose-detection/src/movenet/detector.ts, line 401 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSInXEExixVQ9nZVc0:-MgSShnbA6usYxvgbCdg:b-3g2cni) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/movenet/detector.ts#L401)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

We can do the refactor in another PR.
</blockquote></details>

Ok, we can chat about this with the tracker's author.

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/776)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/calculators/tracker.ts, line 123 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSK4-kExvYNsUUlcEW:-MgSsQze5V4gwwxYn6Bk:bu7i25p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d75e2ca23295d256620781125c8807690fb41884/pose-detection/src/calculators/tracker.ts#L123)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

It's actually not about the tracker using normalized coordinates or image coordinates (it can handle both), it's about values that change after the tracker has stored them. The values that the tracker stores shouldn't change anymore, otherwise the tracker can't know what it is comparing against the next time it is called.
</blockquote></details>

Make sense.
___
*[pose-detection/src/calculators/tracker.ts, line 124 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSsNGeCma_NE7RIyH9:-MgSsNGeCma_NE7RIyHA:b-kcnfit) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7add870a51482b53aee8c11be029169f1c97e32a/pose-detection/src/calculators/tracker.ts#L124)):*
> ```XML
>         // anymore.
>         this.tracks[maxTrackIndex].keypoints =
>             [...poses[detectionIndex].keypoints].map(i => ({...i}));
> ```

nit: keypoint
___
*[pose-detection/src/calculators/tracker.ts, line 141 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/776#-MgSsVjZ4AK3BK0NDnXZ:-MgSsVjZ4AK3BK0NDnX_:b-kcnfit) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7add870a51482b53aee8c11be029169f1c97e32a/pose-detection/src/calculators/tracker.ts#L141)):*
> ```XML
>         // Make sure to copy the Keypoint objects so they can't be modified
>         // anymore.
>         keypoints: [...poses[detectionIndex].keypoints].map(i => ({...i}))
> ```

nit: keypoint

**Pull request merged**
