### PR TITLE
Add NL related tasks and models

### PR DESCRIPTION
**Pull request by jinjingforever**
- Added `sentiment detection` task and toxicity (tfjs) and movie review (tflite) model.
- Added `NL classification` task with custom tflite model. (note that I didn't add the sentiment detection models here because the output of sentiment detection is different from the output of NL classification. Sentiment detection output is more specific, and nl classification output is more general.).
- Added `question and answer` task with both tfjs and tflite model.
- Demo for sentiment detection: https://codepen.io/jinjingforever/pen/xxqVMy. Demo for QA: https://codepen.io/jinjingforever/pen/poeyYqo
- Other minor fixes for existing models (forgot to pass options to the underlying task library)

Thank you!

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/723)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> https://codepen.io/jinjingforever/pen/xxqVMy
the sentiment detection demo link seems to be broken.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/723#-:-M_m5nbF6T8RhXEN9SBT:b-yy4cj3)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tasks/src/tasks/sentiment_detection/movie_review_tflite.ts, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/723#-M_w2kIz7hR02odw9yLL:-M_w2kIz7hR02odw9yLM:b-6gpj3s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c6bf6d61aaa027489c4f0591acb0e669986473c4/tasks/src/tasks/sentiment_detection/movie_review_tflite.ts#L127)):*
> ```XML
>     return {
>       sentimentLabels: {
>         'positive': {
> ```

only positive labels?

**Review by jinjingforever — COMMENTED** [review]
Sorry, here is the link: https://codepen.io/jinjingforever/pen/xxqVMyK

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/723#-:-M_w4IByBNeIxd2KGiuN:b-bymbdg)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tasks/src/tasks/sentiment_detection/movie_review_tflite.ts, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/723#-M_w2kIz7hR02odw9yLL:-M_w4Q_GBwcUXCj5rssX:bsvbpx0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c6bf6d61aaa027489c4f0591acb0e669986473c4/tasks/src/tasks/sentiment_detection/movie_review_tflite.ts#L127)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

only positive labels?
</blockquote></details>

This label basically means what "sentiment" this model is going to predict. For example, for toxicity, labels might be "insult", "threat", etc. For each label, our task model will predict whether the sentiment is true, false, or null (below the threshold). 

Here, the "positive" means whether the movie review is positive or not. It can be true (positive review), false (negative review), or null (below the threshold). In other words, there is no "negative" label because it is the same as "positive=false". Similarly, there is no "not insult" or "not threat" label either. Hope it makes sense.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/723)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[tasks/src/tasks/sentiment_detection/movie_review_tflite.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/723#-M_w8wUR7Ca1POKlnWaU:-M_w8wUR7Ca1POKlnWaV:b-yqlijg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c6bf6d61aaa027489c4f0591acb0e669986473c4/tasks/src/tasks/sentiment_detection/movie_review_tflite.ts#L46)):*
> ```XML
>     name: 'TFLite movie review model',
>     description: 'Run a movie review model with TFLite and output ' +
>         'the probabilities of whether the review is positive or negetive.',
> ```

if only output positive, here should say whether "the review is positive" ?

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/723)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tasks/src/tasks/sentiment_detection/movie_review_tflite.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/723#-M_w8wUR7Ca1POKlnWaU:-M_wIhD47lD1fB2_tDuw:b-tf5fh3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c6bf6d61aaa027489c4f0591acb0e669986473c4/tasks/src/tasks/sentiment_detection/movie_review_tflite.ts#L46)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

if only output positive, here should say whether "the review is positive" ? 
</blockquote></details>

Added the "negative" label as we discussed. Will update the demo after this PR is merged. Thanks!

**Pull request merged**
