### PR TITLE
Add deprecation message for body-pix model

### PR DESCRIPTION
**Pull request by rthadur**
Fixes https://github.com/tensorflow/tfjs/issues/6419

Add deprecation message for body-pix model

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1020)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1020)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @rthadur)

___
*[`body-pix/README.md` line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/1020#-N2NP13IEZy5rRHXv3C1:-N2NP13IEZy5rRHXv3C2:b-lq7ek2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d553681260b2adee963eba60c604e8e2b4a4f747/body-pix/README.md#L1)):*
> ```Markdown
> ## Note: This package is deprecated in favor of the new [face-detection package]([https://github.com/tensorflow/tfjs-models/blob/master/pose-detection](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection)).
> ```

pose-detection



_Code quote:_
```Markdown
face-detection
```

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1020#-:-N2NWA-O0JtWwySC3GRi:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @rthadur)

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1020)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @pyu10055, and @rthadur)

___
*[`README.md` line 80 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/1020#-N2NxUhT1QFs1xNVBrBl:-N2NxUhT1QFs1xNVBrBm:bzg2pje) ([raw file](https://github.com/tensorflow/tfjs-models/blob/20c4c47220a9fca324f60ab1189e1501f701cd69/README.md#L80)):*
> ```Markdown
>   <tr>
>     <td rowspan="2"><b><a style="white-space:nowrap; display:inline-block;" href="./face-landmarks-detection"><div style='vertical-align:middle; display:inline;'>Face Landmark Detection</div></a></b></td>
>     <td><a href="https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html">live</a></td>
> ```

This link does not seem to work for me. It says "Cannot find model in the query string." I think it should be `https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh`

The [readme](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/demos#how-to-run-a-demo) says to add the query string `?model=mediapipe_face_mesh` to select the model. [It looks like this is the only allowed value for the query string at the moment](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/demos/shared/option_panel.js#L37-L45).



_Code quote:_
```Markdown
https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html
```

**Comment by rthadur** [comment]
@mattsoulanille done , thank you

**Review by mattsoulanille — APPROVED** [review]
LGTM. Thanks!

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1020#-:-N2O33kr2L0rU2dpBII2:b-tx3rjn)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie, @pyu10055, and @rthadur)

**Pull request merged**
