### PR TITLE
WIP Handtracking

### PR DESCRIPTION
**Pull request by annxingyuan**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/366)

### CODE REVIEW

**Comment by startupgurukul** [comment]
Hello Ann, 
Thank you for the model, i tried to run the demo but it failed to load(it has a link to a tf-core_with_rotate.js file from google corp intranet )

Can you explain( or do you mind adding a readme) what it does, like does it detect the palm part or as the name suggests does it identify hand anchors up until the elbow or shoulder. I am guessing it would be only palm, please help me understand. 

Thank You.

**Comment by annxingyuan** [comment]
@startupgurukul 

Hello, I've modified the link so it should work now. 

It is a port of this model: https://github.com/google/mediapipe/blob/master/mediapipe/docs/web.md - which includes anchor points on the hand, but not the arm / shoulder.

**Comment by startupgurukul** [comment]
Thank you for the clarification and the effort to get the model to web. 

More power to everyone

**Comment by startupgurukul** [comment]
Hello Ann,
Just to let you know, the demo at https://storage.googleapis.com/tfjs-models/demos/handtrack/index.html keeps complaining 
tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead
Screenshot from 2020-01-22 13-44-02

**Pull request closed without merging**
