### PR TITLE
[pose-detection] MoveNet returns pose score and keypoint names

### PR DESCRIPTION
**Pull request by ardoerlemans**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/654)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/654)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans)

___
*[pose-detection/src/movenet/detector.ts, line 119 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMeBOq6zdJ7fEnVF2f:-MYMeBOq6zdJ7fEnVF2g:b2roksw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L119)):*
> ```XML
> 
>     // We expect an output array of shape [1, 1, 17, 3] (batch, person,
>     // keypoint, coordinate + score).
> ```

Instead of coordinate + score, can you change to 2D coordinate + score or `x, y, score`? When there's no pose in the image, what will the coordinates be?
___
*[pose-detection/src/movenet/detector.ts, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMdy6v3iSGBa5laduK:-MYMdy6v3iSGBa5laduL:bt3qkyb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L127)):*
> ```XML
>     }
> 
>     const inferenceResult = outputTensor.dataSync();
> ```

Should this be `await outputTensor.data()`;
___
*[pose-detection/src/movenet/detector.ts, line 172 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMekJ1DqM-CZ8tNEni:-MYMekJ1DqM-CZ8tNEnj:bu5q882) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L172)):*
> ```XML
>     estimationConfig = validateEstimationConfig(estimationConfig);
> 
>     if (image == null) {
> ```

Should it be `this.reset(); return [];`
___
*[pose-detection/src/movenet/detector.ts, line 255 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMg1yJ4yKauZ5cbx-z:-MYMg1yJ4yKauZ5cbx0-:b-71j0mp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L255)):*
> ```XML
> 
>     // Convert keypoints from crop coordinates to image coordinates.
>     for (let i = 0; i < keypoints.length; ++i) {
> ```

keypoints can be null from detectKeypoints, right?
___
*[pose-detection/src/movenet/detector.ts, line 280 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMgtxR4XkbG7g7psIj:-MYMgtxR4XkbG7g7psIk:bcjr599) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L280)):*
> ```XML
>     let numValidKeypoints = 0.0;
>     let poseScore = 0.0;
>     for (let i = 0; i < keypoints.length; ++i) {
> ```

keypoints can be null.
___
*[pose-detection/src/movenet/detector.ts, line 294 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMhaNO8YVB1AdxaC-7:-MYMhaNO8YVB1AdxaC-8:b-pf62sa) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L294)):*
> ```XML
>       // No pose detected, so make sure we don't use an old pose to smooth
>       // keypoints with.
>       this.keypointsFilter.reset();
> ```

If no pose detected, should we reset cropFilter too? Can we just call this.reset()?
___
*[pose-detection/src/movenet/detector.ts, line 330 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMhFtN0CMZWxrYUebn:-MYMhFtN0CMZWxrYUebo:b9xk9wh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L330)):*
> ```XML
> 
>   reset() {
>     this.cropRegion = null;
> ```

You should set all filters to null here.
___
*[pose-detection/src/movenet/detector.ts, line 400 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMgZqm7UrE4rlejtMd:-MYMgZqm7UrE4rlejtMe:bcjr599) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L400)):*
> ```XML
>    */
>   determineCropRegion(
>       keypoints: Keypoint[], imageHeight: number,
> ```

keypoints can be null.

**Review by ardoerlemans — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/654)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 119 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMeBOq6zdJ7fEnVF2f:-MYQU1rT4iKnjsRFmqMH:bbz8rwl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L119)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Instead of coordinate + score, can you change to 2D coordinate + score or `x, y, score`? When there's no pose in the image, what will the coordinates be?
</blockquote></details>

Updated the comment. When there's no pose, there will still be a return value from the model with somewhat random coordinates and very low confidence scores.
___
*[pose-detection/src/movenet/detector.ts, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMdy6v3iSGBa5laduK:-MYQWwgIBLNb9fqncqiw:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L127)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should this be `await outputTensor.data()`;
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 172 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMekJ1DqM-CZ8tNEni:-MYQX2D04kHnhhrFD4K5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L172)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should it be `this.reset(); return [];`
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 255 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMg1yJ4yKauZ5cbx-z:-MYQXAS-13cJRVZkMaUr:bkx9pl0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L255)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

keypoints can be null from detectKeypoints, right?
</blockquote></details>

Yes. Added a check to test the result from detectKeypoints().
___
*[pose-detection/src/movenet/detector.ts, line 280 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMgtxR4XkbG7g7psIj:-MYQXLKJA3A-CU9qYFC5:bunrfud) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L280)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

keypoints can be null.
</blockquote></details>

Added a check to test the result from detectKeypoints().
___
*[pose-detection/src/movenet/detector.ts, line 294 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMhaNO8YVB1AdxaC-7:-MYQXM5vEeQOu7h6lkDf:b-8n327p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L294)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If no pose detected, should we reset cropFilter too? Can we just call this.reset()?
</blockquote></details>

Yes, good point.
___
*[pose-detection/src/movenet/detector.ts, line 330 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMhFtN0CMZWxrYUebn:-MYQXYUi6DbhAjqKPGBp:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L330)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

You should set all filters to null here.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 400 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYMgZqm7UrE4rlejtMd:-MYQXm6b6Z7nJZkBMZPM:bunrfud) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e4be0050f08eb244eef4f431188d07c80acc6949/pose-detection/src/movenet/detector.ts#L400)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

keypoints can be null.
</blockquote></details>

Added a check to test the result from detectKeypoints().

**Review by lina128 — APPROVED** [review]
Thank you Ard!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-:-MYf38E_3NSvVzQd_Nz_:b87yah6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 255 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYf2nck-R0Jta7xYYtw:-MYf2nck-R0Jta7xYYtx:b-r0cqjk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9b7b2243f2eb966e9659e27b1410c29e4a0038cb/pose-detection/src/movenet/detector.ts#L255)):*
> ```XML
>     croppedImage.dispose();
> 
>     if (!keypoints) {
> ```

`if (keypoints == null)`

**Review by ardoerlemans — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-:-MYfGRJG0owjRcD6UrLS:b-9qdoz3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/movenet/detector.ts, line 255 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/654#-MYf2nck-R0Jta7xYYtw:-MYfGOZoDND6oyVl_uOV:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9b7b2243f2eb966e9659e27b1410c29e4a0038cb/pose-detection/src/movenet/detector.ts#L255)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

`if (keypoints == null)`
</blockquote></details>

Done.

**Pull request merged**
