### PR TITLE
Use fetch polyfill for node in universal sentence encoder.

### PR DESCRIPTION
**Pull request by annxingyuan**
This PR fixes https://github.com/tensorflow/tfjs/issues/1427

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/175)

### CODE REVIEW

**Comment by alexandrduduka** [comment]
Hello guys, thanks for your great effort on this library!

I would like to ask if there is a potential of progress on this issue in close future? I see that you did some work to use node-fetch library in tfjs package and updated dependencies recently, however I am currently facing following issues when trying to work with package in node.js environment:
a) fetch is not defined in USE (tfjs 1.1.0, @tensorflow-models/toxicity 1.0.2)
b) typescript is barking during compilation, as it can't find browser apis from dependencies (I guess this can be resolved with ts-ignore on my side.

I am also not sure if it is optimal to use this package on server side, as it is based on tfjs-core, which is not optimised for such use, as far as I understood. Do you think it is better solution to prepare alternative version of library based on tfjs-node, or is it possible to do something with current library on my side?
I am quite new to tensorflow, so if I am not taking anything right, please let me know.

**Comment by alexandrduduka** [comment]
@tafsiri, @annxingyuan, hello, thank you for your great effort on this library!

I would like to ask if there is a potential of progress on this issue in close future? I see that you did some work to use node-fetch library in tfjs package and updated dependencies recently, however I am currently facing following issues when trying to work with package in node.js environment:
a) fetch is not defined in USE (tfjs 1.1.0, @tensorflow-models/toxicity 1.0.2)
b) typescript is barking during compilation, as it can't find browser apis from dependencies (I guess this can be resolved with ts-ignore on my side.

I am also not sure if it is optimal to use this package on server side, as it is based on tfjs-core, which is not optimised for such use, as far as I understood. Do you think it is better solution to prepare alternative version of library based on tfjs-node, or is it possible to do something with current library on my side?
I am quite new to tensorflow, so if I am not taking anything right, please let me know.

**Comment by annxingyuan** [comment]
Hi @alexandrduduka - apologies for the delay on this PR - I will try to move this forward today.

**Comment by annxingyuan** [comment]
@alexandrduduka actually we're about to republish the models with our new fetch utility which solves this problem: https://github.com/tensorflow/tfjs-models/pull/194

**Comment by alexandrduduka** [comment]
Thanks for the fast reply @annxingyuan! I feel like I am using new version which should have it resolved (if I take it correctly PR you mentioned was merged yesterday), but it still doesn't make a trick for me :-( 

Also, could you elaborate a bit on my question about running the package on server side - do you think it is viable solution or do I have to make some fork with tfjs-node used? Maybe there is a way to tell the library to use tfjs-node instead of tfjs-core?

**Comment by annxingyuan** [comment]
ah you're right - that PR updated the dependency to a version of core with the fetch utility but we still need to invoke it - I submitted a follow up PR: https://github.com/tensorflow/tfjs-models/pull/196

you should be able to just run the package server-side (once this new PR is merged)

**Comment by alexandrduduka** [comment]
Thank you! 👍

**Pull request closed without merging**
