### PR TITLE
[blazeface] Build and serve demo with esbuild

### PR DESCRIPTION
**Pull request by mattsoulanille**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/851)

### CODE REVIEW

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/851)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[blazeface/demo/package.json, line 20 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/851#-MnCuUta1wsY6Zs5yoF8:-MnCuUta1wsY6Zs5yoF9:bnvz2h3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1016d43cb6ca3c92f795a83575464288d6ab453e/blazeface/demo/package.json#L20)):*
> ```
> --minify
> ```
Should we minify the demo? It gets published. 
___
*[blazeface/demo/package.json, line 20 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/851#-MnCuYn--d_6ErCT7qyE:-MnCuYn--d_6ErCT7qyF:b-eonn42) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1016d43cb6ca3c92f795a83575464288d6ab453e/blazeface/demo/package.json#L20)):*
> ```
> --preserve-symlinks
> ```
This is required to make sourcemaps work for the `link:../` dependency on @tensorflow-models/blazeface.

**Review by lina128 — COMMENTED** [review]
Hi Matt, what is this PR for? Why do we switch to esbuild? Does it support hot reloading?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/851#-:-MnD255m9auW8aYhS8sI:bdoqyjt)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/851)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[blazeface/demo/package.json, line 20 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/851#-MnCuUta1wsY6Zs5yoF8:-MnD23A14-E70UiLXUJZ:b4km146) ([raw file](https://github.com/tensorflow/tfjs-models/blob/1016d43cb6ca3c92f795a83575464288d6ab453e/blazeface/demo/package.json#L20)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> --minify
> ```
Should we minify the demo? It gets published. 
</blockquote></details>

Sg, the source map still works right?

**Review by pyu10055 — COMMENTED** [review]
We see some of the security vulnerability issue rooted in parcel dependencies, Matt is try to modernize the demos with esbuild.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/851#-:-MnD2zsU8CDVZqhezX4i:b8bw10b)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille)

**Review by lina128 — APPROVED** [review]
Got it, thanks Matt and Ping!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/851#-:-MnD4ylD0YJzMjL16c26:bffosjd)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)

**Pull request merged**
