### PR TITLE
[pose-detection]Setup demo.

### PR DESCRIPTION
**Pull request by lina128**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/614)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/614)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/rollup.config.js, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5bwgzCbaVIw0afv2X:-MW5bwgzCbaVIw0afv2Y:bji1a4k) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/rollup.config.js#L3)):*
> ```JavaScript
> /**
>  * @license
>  * Copyright 2020 Google LLC. All Rights Reserved.
> ```

2021? same for the other files.
___
*[pose-detection/demo/index.js, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5cAQj12ouJVGi3qG3:-MW5cAQj12ouJVGi3qG4:b-2e9y29) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L24)):*
> ```JavaScript
> import * as tf from '@tensorflow/tfjs-core';
> 
> tfjsWasm.setWasmPaths({
> ```

 those are the default url, right? do we need to set the wasm path specifically?
___
*[pose-detection/demo/index.js, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5d57FDQS0OMvTtNlc:-MW5d57FDQS0OMvTtNld:b-q8095j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L39)):*
> ```JavaScript
> let detector, ctx, videoWidth, videoHeight, video, canvas;
> 
> const state = {
> ```

seems we only support WebGL, do we need to include wasm backend?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/614)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[pose-detection/rollup.config.js, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5bwgzCbaVIw0afv2X:-MW5qRrKAVbmWB7oB4j5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/rollup.config.js#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2021? same for the other files.
</blockquote></details>

Done.
___
*[pose-detection/demo/index.js, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5cAQj12ouJVGi3qG3:-MW61XII3ZMYMbB4rY7e:b-u6xj7x) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L24)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

 those are the default url, right? do we need to set the wasm path specifically?
</blockquote></details>

We either set it here or set it in staticFiles in package.json (should work, but haven't tried) so that Parcel can find the wasm file to serve.
___
*[pose-detection/demo/index.js, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5d57FDQS0OMvTtNlc:-MW625up8bGRAHP7oWm4:b-1mmdd2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

seems we only support WebGL, do we need to include wasm backend?
</blockquote></details>

We should support wasm in the future, for now, the transform function hasn't been added to wasm yet.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/614)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[pose-detection/demo/index.js, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW62hE083E5YRh88FjB:-MW62hE083E5YRh88FjC:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L3)):*
> ```JavaScript
> /**
>  * @license
>  * Copyright 2020 Google LLC. All Rights Reserved.
> ```

2021
___
*[pose-detection/demo/index.js, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5d57FDQS0OMvTtNlc:-MW64Zlv7H7Ocb_yT8QF:bups4kr) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L39)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

We should support wasm in the future, for now, the transform function hasn't been added to wasm yet.
</blockquote></details>

should we skip the setting for wasm til that is available?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/614)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[pose-detection/demo/index.js, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW62hE083E5YRh88FjB:-MW663dbE3BA-BSvDemP:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[pose-detection/demo/index.js, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/614#-MW5d57FDQS0OMvTtNlc:-MW66JQJ7DDbPBEsB7fC:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d037b62acb0a928dc9f1843c6d1f4dd5f1366c36/pose-detection/demo/index.js#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we skip the setting for wasm til that is available?
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/614)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
