### PR TITLE
[pose-detection] Upgrade tfjs-backend-webgpu to official release version

### PR DESCRIPTION
**Pull request by gyagp**

### CODE REVIEW

**Comment by gyagp** [comment]
@mattsoulanille @Linchenn Our internal team reports that pose-detection is still using alpha release of WebGPU, so this PR upgrades the version. Please review the change.

**Review by Linchenn — APPROVED** [review]
The latest TFJS is 4.10, but 4.9 also looks good to me. Thanks!

**Comment by Linchenn** [comment]
@gyagp Thanks for reporting! I think we need to update yarn.lock also and we could update all related packages in pose-detection. @fengwuyao completed them based on this PR, https://github.com/tensorflow/tfjs-models/pull/1197. So we could close this PR.

**Comment by gyagp** [comment]
> @gyagp Thanks for reporting! I think we need to update yarn.lock also and we could update all related packages in pose-detection. @fengwuyao completed them based on this PR, #1197. So we could close this PR.

Really appreciate your quick help!

**Pull request closed without merging**
