### PR TITLE
Add ResNet50 for the PoseNet model

### PR DESCRIPTION
**Pull request by tylerzhu-github**
The pull request includes the following updates to PoseNet:
* Adds ResNet50 (stride=32) based PoseNet models: 513x513 and 257x257 checkpoints
* Switches to use the new TensorFlow.js 1.0 way of model loading and running inference
* Integrates the ResNet50 model into the demo (camera.js)
* Unifies the MobileNet and ResNet50 PoseNet interface.
* Exposes both the MobileNet and ResNet50 arch in the demo (camera.js)
* Makes the `outputStride` argument an optional argument in the model inference call
* Deprecates the `imageScaleFactor` argument in `estimateSinglePose` and `estimateMultiplePoses` API and replaces it with the explicit `imageResolution` argument

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/199)

### CODE REVIEW

**Comment by tylerzhu-github** [comment]
I confirmed that all commits in the PR were authored by me and Dan.

**Comment by tylerzhu-github** [comment]
The PR is ready to be reviewed. Cheers

**Comment by tylerzhu-github** [comment]
The PR is ready to be reviewed again. I have addressed most of the comments. 

Except the comment about dynamically determine parameters when the demo page is first loaded (e.g. MobileNet vs ResNet, stride=16 vs 32). I would say let's default to ResNet if the user is using non-mobile device.

**Comment by nsthorat** [comment]
Please add @dsmilkov or myself as reviewers once you're ready for us to review!

**Comment by tylerzhu-github** [comment]
@nsthorat @dsmilkov yes I would like to add you both as the reviewer of the PR.
Is there any preferred way of adding you as reviewers?

**Comment by tylerzhu-github** [comment]
Thanks for the detailed reviews! 
Currently I am working on test and docs.
Other than that the PR should be ready to be reviewed.

**Comment by tylerzhu-github** [comment]
The documentation and the README.md are updated. Cheers

**Comment by dsmilkov** [comment]
FYI, you should merge/sync with master `git merge origin master` and push again, so the Cloud CI can re-run.

**Comment by dsmilkov** [comment]
Hi, would be great if you can submit this asap, since there are other PRs blocking on the API changes: https://github.com/tensorflow/tfjs-models/pull/209

**Comment by tylerzhu-github** [comment]
Hi Daniel,

Do you want to merge it in? I am currently don't have write access to the repository.
Thanks a lot.

**Pull request merged**
