### PR TITLE
[pose-detection]Add tracker option to demo page for MoveNet model.

### PR DESCRIPTION
**Pull request by lina128**
This PR has below changes:
1. Add enableTracker option to demo page. If value is true, it will visualize different person's skeleton with different colors.
2. Fix bugs in modelConfig validation.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802)

### CODE REVIEW

**Review by ardoerlemans — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802)* status: 0 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/demos/live_video/src/camera.js, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgvU60d7B3nQzRnUQas:-MgvU60d7B3nQzRnUQat:b-kbo72i) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L29)):*
> ```JavaScript
> // starts from 1 and gets increased by 1 for each new detected pose. We give
> // each id a different color. We support visualizing at most 20 poses. We map
> // the pose id uniformly into the color range, i.e. #000000 - #ffffff.
> ```

Doesn't this mean that IDs that are close to each other will get very similar colors?
___
*[pose-detection/demos/live_video/src/camera.js, line 193 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgvUS_JENvxxNeEb9Wq:-MgvUS_JENvxxNeEb9Wr:bzid8kp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L193)):*
> ```JavaScript
>     const color = params.STATE.modelConfig.enableTracking && poseId != null ?
>         `#${
>             (0xFFFFFF & (poseId * COLOR_INTERVAL))
> ```

Have you considered specifying the color as rgb() and then provide three values between 0 and 255? You could use something like (poseId % 20) * 20 / 255.

**Review by ardoerlemans — COMMENTED** [review]
Thanks for adding this! Just two comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-:-MgvW2L-BmfKWLvhg-TG:bw2ndph)* status: 0 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

**Review by ardoerlemans — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802)* status: 0 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/demos/live_video/src/camera.js, line 193 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgvUS_JENvxxNeEb9Wq:-MgwJK2U8K3rJONOcEmm:b-qo4psp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L193)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Have you considered specifying the color as rgb() and then provide three values between 0 and 255? You could use something like (poseId % 20) * 20 / 255.
</blockquote></details>

That should be
(poseId % 20) * 255 / 19

**Review by ronnyvotel — CHANGES_REQUESTED** [review]
Thanks Na!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-:-MgwhLmR-5bFXfKGleLt:b-7z3qys)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @lina128)

___
*[pose-detection/demos/live_video/src/camera.js, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgvU60d7B3nQzRnUQas:-Mgwg2Mm8KEzD203j0NE:b-mmdk6k) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L29)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Doesn't this mean that IDs that are close to each other will get very similar colors?
</blockquote></details>

Yeah I won't be able to tell until I see it, but I was thinking it might be easier to just have an array of 20 very diverse colors [red, blue, green, orange, cyan, ...] and then select color with trackID % 20.
___
*[pose-detection/demos/live_video/src/camera.js, line 188 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgwgJcYC2oWFEJ6J9L1:-MgwgJcYC2oWFEJ6J9L2:bjkk0oa) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L188)):*
> ```
> interger
> ```
nit: integer
___
*[pose-detection/demos/live_video/src/index.js, line 78 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgwglYhCSvdGrnDjJWk:-MgwglYhCSvdGrnDjJWl:bavcjgn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/index.js#L78)):*
> ```
> return posedetection.createDetector(STATE.model, modelConfig);
> ```
do you need this line?

**Review by lina128 — COMMENTED** [review]
Thank you for the reviews, Ronny and Ard, please take another look!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-:-Mh0v560BheKnPHvUT7q:b-7sd3wr)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans and @ronnyvotel)

___
*[pose-detection/demos/live_video/src/camera.js, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgvU60d7B3nQzRnUQas:-Mh0kNrWBLioUGBAdrLn:bso6awc) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L29)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

Yeah I won't be able to tell until I see it, but I was thinking it might be easier to just have an array of 20 very diverse colors [red, blue, green, orange, cyan, ...] and then select color with trackID % 20.
</blockquote></details>

SG, changed to the approach Ronny suggested.
___
*[pose-detection/demos/live_video/src/camera.js, line 188 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgwgJcYC2oWFEJ6J9L1:-Mh0pz7YEOEdhMf2Mgql:bm8geli) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L188)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> interger
> ```
nit: integer
</blockquote></details>

Revised annotation.
___
*[pose-detection/demos/live_video/src/camera.js, line 193 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgvUS_JENvxxNeEb9Wq:-Mh0q152AO52HE3j_PdW:b-spez51) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/camera.js#L193)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

That should be
(poseId % 20) * 255 / 19
</blockquote></details>

Discussed offline, changed to an array of predefined colors.
___
*[pose-detection/demos/live_video/src/index.js, line 78 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-MgwglYhCSvdGrnDjJWk:-Mh0qPnt7w7vJrVRxrM_:b-4grvzq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/fb0ddda99fc270647f1d172a3d999b3f5b2b26e6/pose-detection/demos/live_video/src/index.js#L78)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> return posedetection.createDetector(STATE.model, modelConfig);
> ```
do you need this line?
</blockquote></details>

Good catch! Removed.

**Review by ardoerlemans — APPROVED** [review]
Thanks, looks good to me!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-:-Mh49Lv87WJxRldyin1z:bct07vd)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans and @ronnyvotel)

**Review by ronnyvotel — APPROVED** [review]
Yeah looks great, thanks!

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-:-Mh5_5BqBxWAom45wCqZ:bqc2957)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans)

**Review by ronnyvotel — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/802#-:-Mh5_KDtAFLOww1lttiq:b-jbsf8z)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans)

**Pull request merged**
