### PR TITLE
[pose-detection] Add video demo

### PR DESCRIPTION
**Pull request by lina128**
This PR has below changes:
1. It changes 'demo/' folder to 'demos/', which will host several demos. The original demo folder is renamed to `live_video/`.
2. Added another demo, under `upload_video/`, this demo allows users to upload any demo to the page and run a pose detection model on it.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for adding the upload video demo, is it possible to share the utils?
I am wondering the two different html files can reference the same set js files.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-:-MZQGJKp8iDcHVtUIkhs:b-k7r8ut)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/demos/upload_video/src/camera.js, line 141 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZQGBld1imdWml7Uj9R:-MZQGBld1imdWml7Uj9S:b24z84k) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b34686986b259a1c333e0132d6b1a60b8cd2796c/pose-detection/demos/upload_video/src/camera.js#L141)):*
> ```JavaScript
>   handleDataAvailable(event) {
>     if (event.data.size > 0) {
>       console.log('preparing download');
> ```

should these console.log be removed?

**Review by lina128 — COMMENTED** [review]
I plan to do a refactor to reuse the utils. It's up to you which way is easier for you to review: Option 1. Do the refactor and new changes in one PR. Option 2. Only new changes in this PR, and then refactor in follow up PR. Just let me know which one is easier for you to review.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-:-MZQKGhtDTKBeHkvFXv1:b-6gjaq5)* status: 0 of 1 approvals obtained (waiting on @lina128)

**Review by pyu10055 — COMMENTED** [review]
If you have plan to refactor I am fine with option 2.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-:-MZQLlam8XqXyaqMmCgM:b-4i2xsj)* status: 0 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[pose-detection/demos/upload_video/src/camera.js, line 141 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZQGBld1imdWml7Uj9R:-MZTaWhJAskMIXjHupth:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b34686986b259a1c333e0132d6b1a60b8cd2796c/pose-detection/demos/upload_video/src/camera.js#L141)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should these console.log be removed?
</blockquote></details>

Done.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[pose-detection/demos/upload_video/index.html, line 22 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZTbTmY-fcQ6rGQtmnl:-MZTbTmZAdNJJ7KO7QHh:bs5pc5u) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f2afe690363fcdc97d404bd18c5de7c079e144ec/pose-detection/demos/upload_video/index.html#L22)):*
> ```HTML
>     }
>     #main {
>       position: relative;
> ```

sort the style attributes
___
*[pose-detection/demos/upload_video/index.html, line 41 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZTbuuX7oz6IgadK1ML:-MZTbuuX7oz6IgadK1MM:b-zoml9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f2afe690363fcdc97d404bd18c5de7c079e144ec/pose-detection/demos/upload_video/index.html#L41)):*
> ```HTML
> </head>
> <body>
>   <div id="stats"></div>
> ```

curious if we should use bootstrap to make the UI mobile friendly, probably applies to benchmark tools as well.
___
*[pose-detection/demos/upload_video/src/camera.js, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZTcBESAq6eSarf5uiM:-MZTcBESAq6eSarf5uiN:bk4ck7t) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f2afe690363fcdc97d404bd18c5de7c079e144ec/pose-detection/demos/upload_video/src/camera.js#L34)):*
> ```JavaScript
> 
>   drawCtx() {
>     this.ctx.drawImage(
> ```

can we draw a fix size of frame to reduce UI locking?

**Review by pyu10055 — APPROVED** [review]
> Reviewed 18 of 20 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/679)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[pose-detection/demos/upload_video/index.html, line 41 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZTbuuX7oz6IgadK1ML:-MZUryPQBDvUPbFFr75M:b-e1kgi5) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f2afe690363fcdc97d404bd18c5de7c079e144ec/pose-detection/demos/upload_video/index.html#L41)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

curious if we should use bootstrap to make the UI mobile friendly, probably applies to benchmark tools as well.
</blockquote></details>

Modern CSS with Flexbox should be sufficient to make the UI mobile friendly. I can make the improvement in a separate PR.
___
*[pose-detection/demos/upload_video/src/camera.js, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/679#-MZTcBESAq6eSarf5uiM:-MZUsGW6D3dRqo7ug7h-:bt8ip7r) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f2afe690363fcdc97d404bd18c5de7c079e144ec/pose-detection/demos/upload_video/src/camera.js#L34)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can we draw a fix size of frame to reduce UI locking?
</blockquote></details>

This is to draw every frame of a video, the size is consistent.

**Pull request merged**
