### PR TITLE
Add 3D keypoints to TFJS hand detection

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/850)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/850)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[hand-detection/demos/live_video/index.html, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnCPmZL1xW0J1lGhzrw:-MnCPmZL1xW0J1lGhzrx:b-mbusqc) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e62e0533763a1f390eff70c1cf6db1c26980b212/hand-detection/demos/live_video/index.html#L31)):*
> ```
> positive
> ```
position?
___
*[hand-detection/demos/live_video/index.html, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnCPtm4AS18AjlPNGPS:-MnCPtm4AS18AjlPNGPT:bltqkat) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e62e0533763a1f390eff70c1cf6db1c26980b212/hand-detection/demos/live_video/index.html#L54)):*
> ```
>       <div id="scatter-gl-container-left"></div>
>       </div>
>       <div id="scatter-gl-container-right"></div>
> ```
How do you handle three or more hands?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/850)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[hand-detection/demos/live_video/index.html, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnCPmZL1xW0J1lGhzrw:-MnD-ah40_0s6-vpDPYu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e62e0533763a1f390eff70c1cf6db1c26980b212/hand-detection/demos/live_video/index.html#L31)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> positive
> ```
position?
</blockquote></details>

Done.
___
*[hand-detection/demos/live_video/index.html, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnCPtm4AS18AjlPNGPS:-MnD-aul-j_p4bYABI0o:b-wik0ua) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e62e0533763a1f390eff70c1cf6db1c26980b212/hand-detection/demos/live_video/index.html#L54)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>       <div id="scatter-gl-container-left"></div>
>       </div>
>       <div id="scatter-gl-container-right"></div>
> ```
How do you handle three or more hands?
</blockquote></details>

maxNumHands is set to 2

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/850)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[hand-detection/demos/live_video/index.html, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnCPtm4AS18AjlPNGPS:-MnD2OSC39x5uXLWXGBE:brsovfr) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e62e0533763a1f390eff70c1cf6db1c26980b212/hand-detection/demos/live_video/index.html#L54)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

maxNumHands is set to 2
</blockquote></details>

Can we have an option to change maxHands? It's fine to only visualize one hand in 3d, if scatterGL needs to be initialized at page load. I think demonstrating the model can track arbitrary number of hands is more important.
___
*[hand-detection/demos/live_video/src/camera.js, line 146 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnD32Mv5KNdQFjNXvMK:-MnD32Mv5KNdQFjNXvML:b67q9ml) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5be9a577e1e8aa4ccd04160abbe1408f3023eb2/hand-detection/demos/live_video/src/camera.js#L146)):*
> ```
> Sort by right to left hands.
> ```
Can you apply different color to left and right hands?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/850)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[hand-detection/demos/live_video/index.html, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnCPtm4AS18AjlPNGPS:-MnDJypCC-Xx39vCI7up:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e62e0533763a1f390eff70c1cf6db1c26980b212/hand-detection/demos/live_video/index.html#L54)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we have an option to change maxHands? It's fine to only visualize one hand in 3d, if scatterGL needs to be initialized at page load. I think demonstrating the model can track arbitrary number of hands is more important.
</blockquote></details>

Done.
___
*[hand-detection/demos/live_video/src/camera.js, line 146 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-MnD32Mv5KNdQFjNXvMK:-MnDJzmU8Zry0kHeCAmo:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/e5be9a577e1e8aa4ccd04160abbe1408f3023eb2/hand-detection/demos/live_video/src/camera.js#L146)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> Sort by right to left hands.
> ```
Can you apply different color to left and right hands?
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
Great work!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/850#-:-MnDLpVd1wUduA7Jf4-e:b-9dwnzc)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
