### PR TITLE
Add deprecation message to blaze face

### PR DESCRIPTION
**Pull request by rthadur**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1006)

### CODE REVIEW

**Comment by ahmedsabie** [comment]
@rthadur Can you remove blazeface from README.md, and replace blazeface/README.md with the deprecation message. Similar to the deprecation done by this PR: https://github.com/tensorflow/tfjs-models/commit/dbdd8ec0bd658bceb40a621961a4f36705e72f2e

Thanks!

**Comment by rthadur** [comment]
@ahmedsabie done thank you

**Comment by ahmedsabie** [comment]
@rthadur Can you remove lines 80 to 89 as well in the top level repo's README.md which lists blazeface as one of the packages

**Comment by rthadur** [comment]
@ahmedsabie done.

**Review by ahmedsabie — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1006)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1006#-:-N2Iah434uIjwNBGeZJj:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)

**Pull request merged**
