### PR TITLE
Depth inference for tfjs

### PR DESCRIPTION
**Pull request by grasskin**
Depth Map inference for tfjs ported from FastDepth @sandeepngupta @jasonmayes @annxingyuan

Still have to publish to npm.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/491)

### CODE REVIEW

**Comment by wehriam** [comment]
We're very excited to try this out, thanks for all the work here! 

When building I get a type error:

```ts
$ rimraf dist && tsc
src/index.ts:97:15 - error TS2322: Type 'Tensor<Rank> | Tensor<Rank>[] | NamedTensorMap' is not assignable to type 'Tensor<Rank>'.
  Type 'Tensor<Rank>[]' is missing the following properties from type 'Tensor<Rank>': id, dataId, shape, size, and 165 more.

97         const out : tf.Tensor = this.model.predict(normalized);
                 ~~~


Found 1 error.
```
@grasskin - Any updates on when you might be able to incorporate @annxingyuan's changes so this could be merged in and released?

**Comment by grasskin** [comment]
Hi @wehriam, the model is still going through an internal review process, so hopefully that'll resolve.

As for the build error, those are some of the issues that arose while trying to get this model on tfjs >2.0.1, this codebase should be available with alpha functionality soon!

**Comment by mihaimaruseac** [comment]
The model has been released, afaik.

**Comment by jenperson** [comment]
Thank you for your contribution! This PR is being closed because a depth estimation model has been implemented.

**Pull request closed without merging**
