### PR TITLE
Add FaceDetection TFJS implementation

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[face-landmarks-detection/src/tfjs/detector.ts, line 113 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto6YrVEtYKJq2jk76P:-Mto6YrVEtYKJq2jk76Q:b-cx2512) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/detector.ts#L113)):*
> ```XML
>                 constants.SHORT_RANGE_IMAGE_TO_TENSOR_CONFIG);
> 
>     const inputTensors = shiftImageValue(imageTensor, [-1, 1]);
> ```

The calculator PR is merged, you can use convertImageToTensor for value shift.



_Code quote:_
```XML
const inputTensors = shiftImageValue(imageTensor, [-1, 1]);
```
___
*[face-landmarks-detection/src/tfjs/README.md, line 71 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto8l__-ux7INFc3jS0:-Mto8l__-ux7INFc3jS1:bhvo2mf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/README.md#L71)):*
> ```Markdown
> *   *maxFaces*: Defaults to 1. The maximum number of faces that will be detected by the model. The number of returned faces can be less than the maximum (for example when no faces are present in the input). It is highly recommended to set this value to the expected max number of faces, otherwise the model will continue to search for the missing faces which can slow down the performance.
> 
> *   *predictIrises*: If set to true, refines the landmark coordinates around the eyes and lips, and output additional landmarks around the irises.
> ```

Defaults to false.



_Code quote:_
```Markdown
 I
```
___
*[face-landmarks-detection/src/tfjs/README.md, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto8pg41ibJD0ZidHjP:-Mto8pg41ibJD0ZidHjQ:bec1lhw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/README.md#L73)):*
> ```Markdown
> *   *predictIrises*: If set to true, refines the landmark coordinates around the eyes and lips, and output additional landmarks around the irises.
> 
> *   *detectorModelUrl*: An optional string that specifies custom url of
> ```

See this PR for adding react-native support: https://github.com/tensorflow/tfjs-models/pull/911



_Code quote:_
```Markdown
A
```
___
*[face-landmarks-detection/src/tfjs/tfjs_test.ts, line 81 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto95sK47EA42bPI07b:-Mto95sK47EA42bPI07c:btgzrao) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/tfjs_test.ts#L81)):*
> ```XML
> });
> 
> describeWithFlags('TFJS FaceDetector static image ', BROWSER_ENVS, () => {
> ```

Will there be video test?



_Code quote:_
```XML
static image
```
___
*[face-landmarks-detection/src/tfjs/types.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto9Cg_2G6ZCtEXgHFV:-Mto9Cg_2G6ZCtEXgHFW:bhvo2mf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/types.ts#L50)):*
> ```XML
>  * `runtime`: Must set to be 'tfjs'.
>  *
>  * `predictIrises`: If set to true, refines the landmark coordinates around
> ```

Defaults to false.
___
*[face-landmarks-detection/src/tfjs/calculators/hand_landmarks_to_rect.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto9J8JDvWroJz8YebC:-Mto9J8JDvWroJz8YebD:b-ofemk0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/calculators/hand_landmarks_to_rect.ts#L22)):*
> ```XML
> import {Rect} from '../../shared/calculators/interfaces/shape_interfaces';
> 
> const WRIST_JOINT = 0;
> ```

Is this file relevant to this PR?



_Code quote:_
```XML
nst WRIST_JOINT = 0;
```
___
*[hand-pose-detection/src/tfjs/detector.ts, line 242 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto9YCQ2-7L9ENxUZGQ:-Mto9YCQ2-7L9ENxUZGR:bs05rj0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/hand-pose-detection/src/tfjs/detector.ts#L242)):*
> ```XML
> 
>     const detectionResult =
>         this.detectorModel.predict(imageValueShifted) as tf.Tensor3D;
> ```

Is it possible to separate these changes?



_Code quote:_
```XML
    const detectionResult =
        this.detectorModel.predict(imageValueShifted) as tf.Tensor3D;
```

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[face-landmarks-detection/src/tfjs/detector.ts, line 113 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto6YrVEtYKJq2jk76P:-Mtsq7r38x0w_ZCodE0I:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/detector.ts#L113)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

The calculator PR is merged, you can use convertImageToTensor for value shift.
</blockquote></details>

Done.
___
*[face-landmarks-detection/src/tfjs/README.md, line 71 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto8l__-ux7INFc3jS0:-Mtsq9Ds0sNtP3EGtYXM:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/README.md#L71)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Defaults to false.
</blockquote></details>

Done.
___
*[face-landmarks-detection/src/tfjs/README.md, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto8pg41ibJD0ZidHjP:-MtsqA-14zk009DkWhok:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/README.md#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

See this PR for adding react-native support: https://github.com/tensorflow/tfjs-models/pull/911
</blockquote></details>

Done.
___
*[face-landmarks-detection/src/tfjs/tfjs_test.ts, line 81 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto95sK47EA42bPI07b:-MtsqB3N8sKPgH-QmmP4:b-tfjx6e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/tfjs_test.ts#L81)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Will there be video test?
</blockquote></details>

MediaPipe doesn't have one, do they normally use ground truth videos or just call their own model on a video and use that?
___
*[face-landmarks-detection/src/tfjs/types.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto9Cg_2G6ZCtEXgHFV:-MtsqOPHATFLGe9wAgk5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/types.ts#L50)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Defaults to false.
</blockquote></details>

Done.
___
*[face-landmarks-detection/src/tfjs/calculators/hand_landmarks_to_rect.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto9J8JDvWroJz8YebC:-MtsqnAZDgxf0mIMrb0d:bdd8799) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/face-landmarks-detection/src/tfjs/calculators/hand_landmarks_to_rect.ts#L22)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Is this file relevant to this PR?
</blockquote></details>

Good catch removed
___
*[hand-pose-detection/src/tfjs/detector.ts, line 242 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mto9YCQ2-7L9ENxUZGQ:-Mtsqwv02OstXIMDRpbu:b7tuop3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/19c89b0ecbbd2b4274e96ed940e68b824cbdac2f/hand-pose-detection/src/tfjs/detector.ts#L242)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Is it possible to separate these changes?
</blockquote></details>

https://github.com/tensorflow/tfjs-models/pull/913

**Review by ivan-grishchenko — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[face-landmarks-detection/src/create_detector.ts, line 21 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZoICH2ndAqwTZiGtc:-MvZoICH2ndAqwTZiGtd:b71ukqq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/create_detector.ts#L21)):*
> ```XML
> import {load as loadMediaPipeFaceMeshMediaPipeDetector} from './mediapipe/detector';
> import {MediaPipeFaceMeshMediaPipeModelConfig, MediaPipeFaceMeshModelConfig} from './mediapipe/types';
> import {loadMeshModel as loadMediaPipeFaceMeshTfjsDetector} from './tfjs/detector';
> ```

In MediaPipe we have two separate solutions "Face Detection" and "Face Mesh". I see you are using word "detector" in a different way. Could you please clarify naming logic?
___
*[face-landmarks-detection/src/mediapipe/README.md, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZp8KC-lS8nqbhWp47:-MvZp1_S0SVDRKiwDBQS:b-s382x4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/mediapipe/README.md#L66)):*
> ```Markdown
> *   *maxFaces*: Defaults to 1. The maximum number of faces that will be detected by the model. The number of returned faces can be less than the maximum (for example when no faces are present in the input). It is highly recommended to set this value to the expected max number of faces, otherwise the model will continue to search for the missing faces which can slow down the performance.
> 
> *   *predictIrises*: Defaults to false. If set to true, refines the landmark coordinates around the eyes and lips, and output additional landmarks around the irises.
> ```

It's not just predicting irises. I think better naming would be "refineLandmarks"
___
*[face-landmarks-detection/src/tfjs/constants.ts, line 31 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZpgDW85lestnJe_rE:-MvZpgDW85lestnJe_rF:b-w36bnr) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L31)):*
> ```XML
> export const DEFAULT_LANDMARK_MODEL_URL_WITH_ATTENTION =
>     'https://storage.googleapis.com/tfjs-testing/face-detection/face_landmark_with_attention/model.json';
> export const SHORT_RANGE_DETECTOR_ANCHOR_CONFIG: AnchorConfig = {
> ```

Please ask Valik to review detectors part of this PR. Both configs and code.
___
*[face-landmarks-detection/src/tfjs/constants.ts, line 128 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZr6dNEOlYFe7Mxvgo:-MvZr6dNEOlYFe7Mxvgp:b-gcs7ko) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L128)):*
> ```XML
>   minSuppressionThreshold: 0.3
> };
> export const RECT_TRANSFORMATION_CONFIG: RectTransformationConfig = {
> ```

I see that in MediaPipe parameters are the same both for ROI from detector and from mesh.
But I think it actually should be scale 2.0 for detector and non square for mesh.
Let's double check.
___
*[face-landmarks-detection/src/tfjs/constants.ts, line 274 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZs80CDYM4VioihFtj:-MvZs80CDYM4VioihFtk:b-fcndqa) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L274)):*
> ```XML
>         472
>       ],
>       zRefinement: [
> ```

I guess when it's no a string, it's "assign_average"?
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 52 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZsHFyEOvcWamwkEg6:-MvZsHFyEOvcWamwkEg7:b-dljz2j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L52)):*
> ```XML
> 
>   constructor(
>       private readonly detectorModelType: 'short'|'full',
> ```

What about 'sparse'?
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 121 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZsga10OCHZ70YN7pk:-MvZsga10OCHZ70YN7pl:bd07vge) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L121)):*
> ```XML
>     const unfilteredDetections: Detection[] = await tensorsToDetections(
>         [logits, boxes], this.anchorTensor,
>         this.detectorModelType === 'full' ?
> ```

This logic is duplicated at least 3 times across this method. Please move to one place.
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 172 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZt7Vz9zo1w9V7LmnW:-MvZt7W-8rhz_y6Jcgav:b-2jaal6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L172)):*
> ```XML
>  * MediaPipFaceMesh class.
>  */
> class MediaPipeFaceMeshTfjsDetector implements FaceDetector {
> ```

Again a little confusing about using "detector" in the name of the class dedicated for landmarks tracking.
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 268 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZu5543FNRtrSnfE9H:-MvZu5543FNRtrSnfE9I:b-3f417) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L268)):*
> ```XML
>     // This calculator ensures that the output faceRects array doesn't contain
>     // overlapping regions based on the specified minSimilarityThreshold. Note
>     // that our implementation does not perform association between rects from
> ```

Even without Face IDs, you can do association based on overlapping.
Cause what happens now, when you set num_faces to 2 and there is only 1 face in frame - you'll call face detector on every frame.
While in fact you can just check that rect from previous frame overlaps with detection rect on current frame and keep using rect from previous frame. Even without face ID.
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 300 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mv_1I394jdh15Tu10ld:-Mv_1I394jdh15Tu10le:b9bqg00) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L300)):*
> ```XML
>       if (keypoints != null) {
>         keypoints.forEach((keypoint, i) => {
>           delete keypoint.z;
> ```

Why deleting Z?
___
*[shared/calculators/detector_inference.ts, line 25 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mv_2o29E8l8bzl38YrM:-Mv_2o29E8l8bzl38YrN:bwhul9d) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/shared/calculators/detector_inference.ts#L25)):*
> ```XML
> };
> 
> export function detectorInference(detectionResult: tf.Tensor3D):
> ```

Looks like it's not "inference" anymore. Rename?



_Code quote (from shared/calculators/detection_projection.ts):_
```XML
https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detection_projection_calculator.cc
```
___
*[shared/calculators/landmarks_refinement.ts, line 111 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mv_3SVv4opOXEqdooS7:-Mv_3SVv4opOXEqdooS8:bcpye7m) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/shared/calculators/landmarks_refinement.ts#L111)):*
> ```XML
>  */
> // ref:
> // https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detection_projection_calculator.cc
> ```

Wrong link

**Comment by mahlm** [comment]
Not sure if this is the right place to post, but [@tensorflow-models/face-landmarks-detection](https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection) hasn't had a deployment in a year. Is there a chance we could get an npm release of `face-landmarks-detection` once this is merged into master? Thanks!

**Review by ahmedsabie — COMMENTED** [review]
Once the package is finalized we will be releasing to NPM which should be soon hopefully

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-:-MvzHL-H47zrhhkNbeI8:b-97ymmy)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @bazarevsky, @ivan-grishchenko, and @lina128)

___
*[face-landmarks-detection/src/create_detector.ts, line 21 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZoICH2ndAqwTZiGtc:-Mvz1anl5dV4pP4fnm4B:b-agio03) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/create_detector.ts#L21)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

In MediaPipe we have two separate solutions "Face Detection" and "Face Mesh". I see you are using word "detector" in a different way. Could you please clarify naming logic?
</blockquote></details>

That is a good point since this tfjs implementation has both a detector class and a mesh class (with the latter using former as in MediaPipe). I renamed to LandmarksDetector to distinguish from just a face detector, and to also match the package name
___
*[face-landmarks-detection/src/mediapipe/README.md, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZp8KC-lS8nqbhWp47:-Mvz6PZb7FKO8wSLiy5p:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/mediapipe/README.md#L66)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

It's not just predicting irises. I think better naming would be "refineLandmarks"
</blockquote></details>

Done.
___
*[face-landmarks-detection/src/tfjs/constants.ts, line 128 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZr6dNEOlYFe7Mxvgo:-Mvz7BVPE-rUWx6Q0vpW:bf79t9r) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L128)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

I see that in MediaPipe parameters are the same both for ROI from detector and from mesh.
But I think it actually should be scale 2.0 for detector and non square for mesh.
Let's double check.
</blockquote></details>

I checked the Mediapipe code and see that both are the same, is there another way to double check?
___
*[face-landmarks-detection/src/tfjs/constants.ts, line 274 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZs80CDYM4VioihFtj:-Mvz8193-MFiDt9ucTcJ:b-51lai1) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L274)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

I guess when it's no a string, it's "assign_average"?
</blockquote></details>

Yes, added a type in the config declaration called AssignAverage to clarify this.
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 52 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZsHFyEOvcWamwkEg6:-Mvz9KsL8K2b6hvJpdFC:bbvtwm0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L52)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

What about 'sparse'?
</blockquote></details>

This matches the MediaPipe web solution for FaceDetector https://google.github.io/mediapipe/solutions/face_detection.html#model_selection, which in its implementation maps the full option to the full sparse model which is similarly done in this code.
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 121 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZsga10OCHZ70YN7pk:-MvzB_pJEBPaBMqPwMFV:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L121)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

This logic is duplicated at least 3 times across this method. Please move to one place.
</blockquote></details>

Done.
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 172 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZt7Vz9zo1w9V7LmnW:-MvzBeDn1s2fs0wsG1P6:b-886gsx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L172)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Again a little confusing about using "detector" in the name of the class dedicated for landmarks tracking.
</blockquote></details>

Fixed
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 268 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZu5543FNRtrSnfE9H:-MvzExPLAGLNpviXWZtQ:b-fi3q79) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L268)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Even without Face IDs, you can do association based on overlapping.
Cause what happens now, when you set num_faces to 2 and there is only 1 face in frame - you'll call face detector on every frame.
While in fact you can just check that rect from previous frame overlaps with detection rect on current frame and keep using rect from previous frame. Even without face ID.
</blockquote></details>

Ah that's a great point, fixed
___
*[face-landmarks-detection/src/tfjs/detector.ts, line 300 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mv_1I394jdh15Tu10ld:-MvzF_QE18yGxtkj_GS1:b-79k7j2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/detector.ts#L300)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Why deleting Z?
</blockquote></details>

There was a discussion on this in the hands implementation as well, and the main reason was there is no easy way to use it: https://github.com/tensorflow/tfjs-models/pull/842#pullrequestreview-775345382.
___
*[shared/calculators/detector_inference.ts, line 25 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mv_2o29E8l8bzl38YrM:-MvzGlEyAT1xXIBnjukz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/shared/calculators/detector_inference.ts#L25)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Looks like it's not "inference" anymore. Rename?
</blockquote></details>

Done.
___
*[shared/calculators/landmarks_refinement.ts, line 111 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-Mv_3SVv4opOXEqdooS7:-MvzGm4RAxwowEHvFXRD:b-886gsx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/shared/calculators/landmarks_refinement.ts#L111)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Wrong link
</blockquote></details>

Fixed

**Comment by mahlm** [comment]
@ahmedsabie We actually use the Z in our production application. It'd be nice to carry it over, otherwise we'll have to find a creative solution.

**Review by bazarevsky — APPROVED** [review]

**Review by ivan-grishchenko — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @ahmedsabie, @ivan-grishchenko, and @lina128)

___
*[face-landmarks-detection/src/tfjs/constants.ts, line 128 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZr6dNEOlYFe7Mxvgo:-MwbX-wEB_YbBrUxGIw6:bafr2gt) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L128)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

I checked the Mediapipe code and see that both are the same, is there another way to double check?
</blockquote></details>

Checked once again.
It actually should be non-square for mesh, but there is some processing bug with that in MP. You can leave TODO for fixing it later once MP is fixed.
Scale 2.0 instead of 1.5 is not that important as it happens only on first frame.

**Review by ahmedsabie — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-:-MwhT5HL5LD-jZk2YuMO:bb6un1j)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @ivan-grishchenko and @lina128)

___
*[face-landmarks-detection/src/tfjs/constants.ts, line 31 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZpgDW85lestnJe_rE:-MwhT7ClE9qqxCmc0ucu:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L31)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Please ask Valik to review detectors part of this PR. Both configs and code.
</blockquote></details>

Done
___
*[face-landmarks-detection/src/tfjs/constants.ts, line 128 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/912#-MvZr6dNEOlYFe7Mxvgo:-MwhT8Gr8VUPYy2teTqt:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c7fdd146e7510010cea251080e72c15663dcf95e/face-landmarks-detection/src/tfjs/constants.ts#L128)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Checked once again.
It actually should be non-square for mesh, but there is some processing bug with that in MP. You can leave TODO for fixing it later once MP is fixed.
Scale 2.0 instead of 1.5 is not that important as it happens only on first frame.
</blockquote></details>

Done

**Pull request merged**
