### PR TITLE
Add base class and types.

### PR DESCRIPTION
**Pull request by lina128**
fyi, @ardoerlemans, @ivan-grishchenko

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/pose_detector.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYNe8W4zVonHm2N-8c:-MVYNe8W4zVonHm2N-8d:b93rslq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c85e6f4e349c0551137389494216d4b600dbd0e/pose-detection/src/pose_detector.ts#L24)):*
> ```XML
>  * Each pipeline's detetector subclass should extend from this class.
>  */
> export abstract class PoseDetector {
> ```

An Interface will be better than base class
___
*[pose-detection/src/types.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYO1m20GiGovMB6mIf:-MVYO1m20GiGovMB6mIg:b3b5zw4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c85e6f4e349c0551137389494216d4b600dbd0e/pose-detection/src/types.ts#L19)):*
> ```XML
> import * as tf from '@tensorflow/tfjs-core';
> 
> export enum SupportedPipelines {
> ```

Will this enum be exposed to external API, I am not sure pipeline is a good word for model type, users might not know there are processing pipeline underneath, how about SupportedModels?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[pose-detection/src/pose_detector.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYNe8W4zVonHm2N-8c:-MVYasmV5QdK8vYonATl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c85e6f4e349c0551137389494216d4b600dbd0e/pose-detection/src/pose_detector.ts#L24)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

An Interface will be better than base class
</blockquote></details>

Done.
___
*[pose-detection/src/types.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYO1m20GiGovMB6mIf:-MVYbEbf79iwHLWgqyMn:b-iy6qgl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7c85e6f4e349c0551137389494216d4b600dbd0e/pose-detection/src/types.ts#L19)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Will this enum be exposed to external API, I am not sure pipeline is a good word for model type, users might not know there are processing pipeline underneath, how about SupportedModels?
</blockquote></details>

Yes, everything exposed to external API is exported in index.ts. Changed to SupportedModels.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[pose-detection/src/pose_detector.ts, line 28 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYdm3W0zcC3OlfdR_b:-MVYdm3W0zcC3OlfdR_c:bmfdszp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/808c8cdb3be5eb06659b0a806b950845e4c839b5/pose-detection/src/pose_detector.ts#L28)):*
> ```XML
>    * Load models for the pipeline.
>    */
>   load(): Promise<void>;
> ```

should load method have an option, since for posenet there are different type of model files to load, or you are thinking adding a global loading method that specifies the model options.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[pose-detection/src/pose_detector.ts, line 28 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYdm3W0zcC3OlfdR_b:-MVYf6cO25Qx0e1JchK2:b-cbdfrz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/808c8cdb3be5eb06659b0a806b950845e4c839b5/pose-detection/src/pose_detector.ts#L28)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should load method have an option, since for posenet there are different type of model files to load, or you are thinking adding a global loading method that specifies the model options.
</blockquote></details>

The detector class's constructor should take the model option.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/607)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[pose-detection/src/pose_detector.ts, line 28 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/607#-MVYdm3W0zcC3OlfdR_b:-MVYyyTM6w37UUWUPu9G:b5xgutl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/808c8cdb3be5eb06659b0a806b950845e4c839b5/pose-detection/src/pose_detector.ts#L28)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

The detector class's constructor should take the model option. 
</blockquote></details>

Per offline discussion, separate load and estimate interface and only expose estimate interface to user (through return signature). Load is used internally by createDetector, and should take care of construct and async load.

**Pull request merged**
