### PR TITLE
Update coco.js

### PR DESCRIPTION
**Pull request by hpssjellis**
One code change allows the loading and analysis of an image as soon as the image is chosen from the dropdown list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/16)

### CODE REVIEW

**Comment by oveddan** [comment]
Thanks for this - I agree and it will help with the UI. 

Could you also:
- [ ] Make it so that when the output stride dropdown is changed, the pose estimation also happens
- [ ] Get rid of the estimate pose button right below.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/16#-:-LC79CghCMwdtRIrqVBg:b1wamfg)*

**Comment by hpssjellis** [comment]
Made both extra changes.

Output Stride now works but the lower value of 8 seems to get poor results and the higher value of 32 seems to get better results without much detectable time difference.

Does not seem to match the notes on the page that say

_"The output stride and input image resolution have the largest effects on accuracy/speed. A higher output stride results in lower accuracy but higher speed. ..."_

**Comment by oveddan** [comment]
Thanks for the change.

The issue is that when the output stride dropdown is changed, the output stride becomes a string.  If you see the previous code we converted this to a number, so you should do the same.

Also - can you please do a rebase from master instead of a merge?

`git rebase origin/master`

instead of `git merge master`

It is better to just have the commit with your changes in this PR than also having the merge commit.

You can fix this by squashing the commits.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/16#-:-LCBCSWQ1OHHeYedvtOw:b-78ok8w)*

**Comment by hpssjellis** [comment]
I only use the browser version of git, so easier for me to close this PR and make a new one.

**Pull request closed without merging**
