### PR TITLE
Fix `@tensorflow-models` CDN url

### PR DESCRIPTION
**Pull request by fraserxu**
The CDN url for `https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@0.1.0` should be `@0.0.1`.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/14)

### CODE REVIEW

**Comment by fraserxu** [comment]
`v0.0.1` seems not work neither. Might have issue bundle into UMD modules.

screen shot 2018-05-09 at 9 49 39 am

**Comment by oveddan** [comment]
@fraserxu I believe the url should be:
`https://unpkg.com/@tensorflow-models/mobilenet`

Can you try that?

**Comment by fraserxu** [comment]
@oveddan indeed, use `unpkg` works for both urls.

**Comment by jimaek** [comment]
That URL redirects to https://unpkg.com/@tensorflow-models/mobilenet@0.0.1/dist/bundle.js

Which is also accessible from jsDelivr
https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@0.0.1/dist/bundle.js
It can also be auto-minified
https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@0.0.1/dist/bundle.min.js

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/14#-:-LC9aFtN4ys4XuzEW_QP:b-jbsf8z)*

**Pull request merged**
