### PR TITLE
Move common calculators to shared directory

### PR DESCRIPTION
**Pull request by ahmedsabie**
Any calculators that were originally in pose-detection but are not applicable exclusively to pose-detection are moved to the shared folder so that they can be used by other models (such as the upcoming tfjs hand-detection implementation)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/840)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/840)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[pose-detection/src/movenet/detector_utils.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6JNq4lypFyqn7_Hq:-Mkd6JNq4lypFyqn7_Hr:bopbv38) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/detector_utils.ts#L18)):*
> ```
> TrackerConfig
> ```
We should make tracker including trackers common calculators too.
___
*[pose-detection/src/movenet/calculators/interfaces/common_interfaces.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6yhY1olAmhNpoztt:-Mkd6yhY1olAmhNpoztu:b-3c5lmd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/calculators/interfaces/common_interfaces.ts#L21)):*
> ```
> export interface Track {
> ```
Move to shared folder.
___
*[pose-detection/src/movenet/calculators/interfaces/config_interfaces.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd7-uWApYTAT7U_0Zx:-Mkd7-uWApYTAT7U_0Zy:bugvyi3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/calculators/interfaces/config_interfaces.ts#L18)):*
> ```
> export interface TrackerConfig 
> ```
Move to shared folder.
___
*[scripts/diff.js, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd8_oP5lh_sphRhzrC:-Mkd8_oP5lh_sphRhzrD:b-ln61cs) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/scripts/diff.js#L98)):*
> ```
> sharedDiffOutput
> ```
Curious, if a packaged has symlink to the shared folder, the shared folder is treated as a regular folder, right? Why do we need to explicitly diff the shared folder?
___
*[pose-detection/src/movenet/calculators/keypoint_tracker.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6mwmDuBVpitXA5DB:-Mkd6mwmDuBVpitXA5DC:bttpfzi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/calculators/keypoint_tracker.ts#L18)):*
> ```
> import {Keypoint} from '../../shared/types';
> ```
Move tracker to shared folder.
___
*[pose-detection/src/movenet/calculators/keypoint_tracker_test.ts, line 17 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6rLB3GX_DPcqXI7Q:-Mkd6rLB3GX_DPcqXI7R:bnkht06) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/calculators/keypoint_tracker_test.ts#L17)):*
> ```
> import {Keypoint} from '../../shared/types';
> ```
Move to shared folder.
___
*[pose-detection/src/movenet/calculators/tracker.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6tuz7ZkojT0_Auza:-Mkd6tuz7ZkojT0_Auzb:b-j846sk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/calculators/tracker.ts#L18)):*
> ```
> import {Pose} from '../../types';
> ```
Move to shared folder.
___
*[shared/calculators/calculate_landmark_projection.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd9qvnDFZMm_8qw2db:-Mkd9qvnDFZMm_8qw2dc:b-4um17g) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/shared/calculators/calculate_landmark_projection.ts#L18)):*
> ```
> types
> ```
Should we rename types file to common_interfaces, given we also have shape_interfaces and config_interfaces? Also this file should be moved to interface folder.
___
*[shared/calculators/visibility_smoothing.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-MkdBhzfBzgYdbCVhFH4:-MkdBhzfBzgYdbCVhFH5:b-jbschz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/shared/calculators/visibility_smoothing.ts#L21)):*
> ```
> low_pass_filter
> ```
Probably good to group all the filters under filter folder and export under a secondary namespace filter. Same for tracker.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/840)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6JNq4lypFyqn7_Hq:-MkecrRZAduIdnJymqPe:bm7wzgl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/detector_utils.ts#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> TrackerConfig
> ```
We should make tracker including trackers common calculators too.
</blockquote></details>

trackers depend on the Pose type though, would it make it sense to move that to common as well?
___
*[scripts/diff.js, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd8_oP5lh_sphRhzrC:-Mkecw0n4DjmCZ39by7Q:bk2q9yi) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/scripts/diff.js#L98)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> sharedDiffOutput
> ```
Curious, if a packaged has symlink to the shared folder, the shared folder is treated as a regular folder, right? Why do we need to explicitly diff the shared folder?
</blockquote></details>

ah great catch it only matters if we are using git diff, but the command here is actually diff
___
*[shared/calculators/calculate_landmark_projection.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd9qvnDFZMm_8qw2db:-Mkem5YZB7Y58zDV8Awp:bq0ncok) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/shared/calculators/calculate_landmark_projection.ts#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> types
> ```
Should we rename types file to common_interfaces, given we also have shape_interfaces and config_interfaces? Also this file should be moved to interface folder.
</blockquote></details>

sounds good
___
*[shared/calculators/visibility_smoothing.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-MkdBhzfBzgYdbCVhFH4:-MkeehCP6kxttyOJzfj9:bq0ncok) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/shared/calculators/visibility_smoothing.ts#L21)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> low_pass_filter
> ```
Probably good to group all the filters under filter folder and export under a secondary namespace filter. Same for tracker.
</blockquote></details>

sounds good

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/840)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6JNq4lypFyqn7_Hq:-Mkh_a_311t0kbQWIhtp:b-xpu2ye) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/detector_utils.ts#L18)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

trackers depend on the Pose type though, would it make it sense to move that to common as well?
</blockquote></details>

Ah, you are right. Can we still have a shared calculators folder in pose? The tracker is not MoveNet specific. PoseNet can use this tracker too.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/840)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[pose-detection/src/movenet/detector_utils.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-Mkd6JNq4lypFyqn7_Hq:-Mkhx5nj8yuGXBpjyzpD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b701d329199c302b6aa4848940f7adcccde7b199/pose-detection/src/movenet/detector_utils.ts#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Ah, you are right. Can we still have a shared calculators folder in pose? The tracker is not MoveNet specific. PoseNet can use this tracker too.
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/840#-:-MkidSpX4LF_RimLR4jd:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Review by ardoerlemans — APPROVED** [review]

**Pull request merged**
