### PR TITLE
[task] refactor to make things work better for API docs

### PR DESCRIPTION
**Pull request by jinjingforever**
- Replace options types with interfaces in various places so that they can be picked up by our doc-gen system.
- Replace task model interfaces with classes (for the same reason).
- Add/Refactor comments. 

I will send another PR in tfjs-website repo that updates the current doc-gen system with some new features.

The end results look like this:
https://storage.googleapis.com/tfweb/doc-test/api_tasks/local/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/699)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/699)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tasks/src/task_model.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2vTD16BH2kfxSgq7j:-M_2vTD16BH2kfxSgq7k:bpo6208) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/task_model.ts#L55)):*
> ```XML
>  * model.cleanUp();
>  */
> export abstract class TaskModel {
> ```

what is the rationale of using abstract class instead of interface? since there are no implmentations.
___
*[tasks/src/tasks/image_classification/custom_model_tflite.ts, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2xPINAkY_ZutkB1Ie:-M_2xPINAkY_ZutkB1If:b33w391) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/custom_model_tflite.ts#L36)):*
> ```XML
>  * TODO: placeholder for now.
>  */
> export interface ICCustomModelTFLiteInferanceOptions {}
> ```

this seems to be duplicated
___
*[tasks/src/tasks/image_classification/custom_model_tflite.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2xtR88Ua73ccElvhf:-M_2xtR88Ua73ccElvhg:bs5qdqn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/custom_model_tflite.ts#L65)):*
> ```XML
>       sourceModelGlobal: TFLiteNS,
>       loadingOptions?: ICCustomModelTFLiteLoadingOptions):
>       Promise<ImageClassifier<ICCustomModelTFLiteInferanceOptions>> {
> ```

should the return type be `Promise<ICCUstomModelTFLite>`
___
*[tasks/src/tasks/image_classification/mobilenet_tflite.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2wGG-71VCULyRSuB0:-M_2wGG-71VCULyRSuB1:bd76qeh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/mobilenet_tflite.ts#L48)):*
> ```XML
>  * TODO: placeholder for now.
>  */
> export interface MobilenetTFLiteInferanceOptions {}
> ```

is this interface duplicated from above?

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/699)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tasks/src/task_model.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2vTD16BH2kfxSgq7j:-M_6a5wz5iVvJfJDlT2B:bpyfb3s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/task_model.ts#L55)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

what is the rationale of using abstract class instead of interface? since there are no implmentations.
</blockquote></details>

Good catch! This one can stay as interface. Done.
___
*[tasks/src/tasks/image_classification/custom_model_tflite.ts, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2xPINAkY_ZutkB1Ie:-M_6eZyh215zgss-wXZz:b-pnhr4h) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/custom_model_tflite.ts#L36)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this seems to be duplicated
</blockquote></details>

See below.
___
*[tasks/src/tasks/image_classification/custom_model_tflite.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2xtR88Ua73ccElvhf:-M_6eGim9pd546w_1Ajk:bm4qzni) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/custom_model_tflite.ts#L65)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the return type be `Promise<ICCUstomModelTFLite>`
</blockquote></details>

Good catch! Done
___
*[tasks/src/tasks/image_classification/mobilenet_tflite.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2wGG-71VCULyRSuB0:-M_6eRHN-XsP3l4rRg7N:b-g15oml) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/mobilenet_tflite.ts#L48)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is this interface duplicated from above?
</blockquote></details>

For now this is a placeholder. In theory different models should have their own inference options, so this one is not necessarily going to be the same as the one in custom_model_tflite.ts in the future, so it would be better to keep them separated.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/699)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[tasks/src/tasks/image_classification/custom_model_tflite.ts, line 35 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_78VFtEIjf7WrhMD1n:-M_78VFtEIjf7WrhMD1o:bp2zqrq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/74eefe134178938fe8ee942d562c78a91aff85af/tasks/src/tasks/image_classification/custom_model_tflite.ts#L35)):*
> ```XML
>  * TODO: placeholder for now.
>  */
> export interface ICCustomModelTFLiteInferanceOptions {}
> ```

`ICCustomLiteInferenceOption`
___
*[tasks/src/tasks/image_classification/mobilenet_tflite.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/699#-M_2wGG-71VCULyRSuB0:-M_78qtU3vwOt_LaMAVH:bqdgutw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b978d900026cdcc23f2c2ffe9828ed16df3d75e0/tasks/src/tasks/image_classification/mobilenet_tflite.ts#L48)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

For now this is a placeholder. In theory different models should have their own inference options, so this one is not necessarily going to be the same as the one in custom_model_tflite.ts in the future, so it would be better to keep them separated.
</blockquote></details>

got it, the `Inference` is mis-spelled, please check all files. thanks

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/699)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
