### PR TITLE
Fix blazeface memory leak

### PR DESCRIPTION
**Pull request by sklum**
Hi tfjs team 👋!

This PR fixes two memory leaks in blazeface - hopefully this is helpful even though it's deprecated.

I can confirm (at least in terms of allocated tensors) that there aren't any more leaks.  I also removed an unnecessary null check from the previous PR that added the `dispose()` method.

Is there any chance these changes could be pushed to `npm`?  I'd be happy to switch to the new face detection engine but that detector doesn't return a probability / confidence AFAIK and this functionality is required for my work.

Thanks for all your work and your willingness to open source this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1038)

### CODE REVIEW

**Comment by ahmedsabie** [comment]
@sklum Thanks for the fix! Can you modify [this test](https://github.com/tensorflow/tfjs-models/blob/master/blazeface/src/blazeface_test.ts#L32) to check the startTensors as well? The current test doesn't check for cleanup by the model, only cleanup by inference. Here's an [example](https://github.com/tensorflow/tfjs-models/blob/master/face-detection/src/tfjs/tfjs_test.ts#L51) doing that.

**Comment by sklum** [comment]
Will do!

**Comment by sklum** [comment]
Alright @ahmedsabie, added the test.  If you run the new test without calling `dispose()` within, it will indeed fail.  Calling `dispose()` works as expected.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1038)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

**Review by ahmedsabie — APPROVED** [review]

**Pull request merged**
