### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HalfdanJ**
Add link to issues, and add description of knn classifier

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/35)

### CODE REVIEW

**Comment by nsthorat** [comment]
I'm not quite ready to add this yet -- still a bit of refactoring to do to generalize it, but I will make sure to merge this once it's done.

**Comment by HalfdanJ** [comment]
Sure

**Comment by nsthorat** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[README.md, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/35#-LFY6We8-Y4eBCWj2Um7:-LFY6We96AWV5XKVLVaN:bswepah) ([raw file](https://github.com/tensorflow/tfjs-models/blob/871f5ed9d3c5905c07e74588ad638e90668127e0/README.md#L23)):*
> ```Markdown
> - [PoseNet](https://github.com/tensorflow/tfjs-models/tree/master/posenet) - Realtime pose detection. Blog post [here](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5).
>   - `npm install @tensorflow-models/posenet`
> - [KNN Image Classifier](https://github.com/tensorflow/tfjs-models/tree/master/knn-image-classifier) - Build custom image classifier using a KNN classifier
> ```

Can you remove "image" here? Then LGTM

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/35)*

**Comment by nsthorat** [comment]
Made the changes myself in https://github.com/tensorflow/tfjs-models/pull/39

**Pull request closed without merging**
