### PR TITLE
Add mask utilities for conversion between mask types

### PR DESCRIPTION
**Pull request by ahmedsabie**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Great work, Ahmed! I left one comment below, please address before merge.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-:-MoLX3lH151vOVOtiW5r:b-ylj6ho)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[shared/calculators/mask_util.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLTxw393oGpDOaiWBf:-MoLTxw393oGpDOaiWBg:b-da85bc) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L84)):*
> ```
> https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData#data_loss_due_to_browser_optimization
> ```
Nice find!
___
*[shared/calculators/mask_util.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLUt-t7o-FF_uTFFo5:-MoLUt-t7o-FF_uTFFo6:b7a93fz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L93)):*
> ```XML
>   const pixelsInput =
>       (image instanceof SVGImageElement || image instanceof OffscreenCanvas) ?
>       await toHTMLCanvasElementLossy(image) :
> ```

This creates a temporary canvas element, do we need to delete it after use (e.g. after fromPixels)? Otherwise, won't there be memory leak?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[shared/calculators/mask_util.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLUt-t7o-FF_uTFFo5:-MoWyIa_1-ipPvieDtwY:b-nbhycb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L93)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This creates a temporary canvas element, do we need to delete it after use (e.g. after fromPixels)? Otherwise, won't there be memory leak?
</blockquote></details>

The canvas element goes out of scope on return though so wouldn't it get garbage collected?

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[shared/calculators/mask_util.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLUt-t7o-FF_uTFFo5:-Mo_K3lqBf7qwJmAupAA:bfz15io) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L93)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

The canvas element goes out of scope on return though so wouldn't it get garbage collected?
</blockquote></details>

Yes. My thinking is, for high throughput pipeline (running every animation frame), this may still take up a lot of resources quickly before garbage collector has a chance to run, so we may want to delete unused resources aggressively. WDYT?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[shared/calculators/mask_util.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLUt-t7o-FF_uTFFo5:-Mo_cbXV90d8ommFOI0C:br9de1q) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L93)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Yes. My thinking is, for high throughput pipeline (running every animation frame), this may still take up a lot of resources quickly before garbage collector has a chance to run, so we may want to delete unused resources aggressively. WDYT?
</blockquote></details>

sounds good, added the fix

**Review by lina128 — COMMENTED** [review]
This PR adds a lot of files, do they belong to this PR?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-:-Mo_hcPu9VvyxHZQaWq7:bekquf3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[shared/calculators/mask_util.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLUt-t7o-FF_uTFFo5:-Moa8OCJ6EFfaRcXvvu3:b-x6h05f) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L93)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

sounds good, added the fix
</blockquote></details>

Sorry, my bad, it seems delete has nothing to do with directly freeing memory (https://docs.w3cub.com/javascript/errors/delete_in_strict_mode), so delete from an object doesn't help releasing the memory faster. No need to delete in this case.

**Review by ahmedsabie — COMMENTED** [review]
Woops sorry removed those

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-:-Moa_nhR6BqQVycenjmn:bcsbj7j)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[shared/calculators/mask_util.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/866#-MoLUt-t7o-FF_uTFFo5:-Moa_sQo16Sq3pyHL1cA:bfnz4sx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a7ccc3782e082b6c71185ba38dc0b5fb5af1ca21/shared/calculators/mask_util.ts#L93)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Sorry, my bad, it seems delete has nothing to do with directly freeing memory (https://docs.w3cub.com/javascript/errors/delete_in_strict_mode), so delete from an object doesn't help releasing the memory faster. No need to delete in this case.
</blockquote></details>

ah ok didn't know that either, thanks for clarifying! reverted change

**Pull request merged**
