### PR TITLE
[face-landmarks-detection] Make types extensible.

### PR DESCRIPTION
**Pull request by annxingyuan**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/528)

### CODE REVIEW

**Comment by annxingyuan** [comment]
Hi @tafsiri - looking at the comment here: https://github.com/tensorflow/tfjs-models/pull/526#issuecomment-707143180

I was wondering whether this PR would be a valid solution to this type of issue? Let me know your thoughts if you get a minute.

**Review by tafsiri — CHANGES_REQUESTED** [review]
Hey @annxingyuan I don't think this is the right way to go, but I am wondering if my comments below are just missing if you are trying to solve a more general problem than described in that comment. It doesn't look like the kind of interface that should take arbitrary things, over time if the options grow I think you would want the types to document/enforce that. Feel free to hit me up on GVC for a quick chat.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-:-MJXNtI-BipBEBjLQIof:bl9pjyj)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[face-landmarks-detection/src/types.ts, line 27 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJXNo8E7eLvhrwIB7Cu:-MJXNo8F93ohu3CS7-lh:b-m9c9r) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f48bba865d23d2912ee842cb4b7cc94c84484bc2/face-landmarks-detection/src/types.ts#L27)):*
> ```XML
> 
>   // tslint:disable-next-line:no-any
>   [x: string]: any;
> ```

why add this (I didn't understand relation to the comment linked to). 
___
*[face-landmarks-detection/src/types.ts, line 43 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJXNhf787ga8h-5gNck:-MJXNhf787ga8h-5gNcl:b3y5b40) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f48bba865d23d2912ee842cb4b7cc94c84484bc2/face-landmarks-detection/src/types.ts#L43)):*
> ```XML
> 
>   // tslint:disable-next-line:no-any
>   [x: string]: any;
> ```

why not add predictIrises here?

**Review by annxingyuan — COMMENTED** [review]
Hi @tafsiri - thanks for the discussion yesterday. I tried to follow your suggestions with this latest set of changes - let me know what you think.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-:-MJb8Wls7lwR4KJCjyIG:b-ofoo04)* status: 0 of 1 approvals obtained (waiting on @annxingyuan)

**Review by tafsiri — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/528)* status: 0 of 1 approvals obtained (waiting on @annxingyuan)

___
*[face-landmarks-detection/src/types.ts, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbpz2JECIb4H7uo7Og:-MJbpz2K-u5VV3dL-Ybw:b6pml3u) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/types.ts#L26)):*
> ```XML
> // The union of types describing packages that detect face landmarks in an
> // input (currently with only one option).
> export type FaceLandmarksPackage = MediaPipeFaceMesh;
> ```

Having Package in the name seems a bit odd. how about 'FaceLandMarksDetector'
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 52 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbqkad4xD9IPpHAkBs:-MJbqkad4xD9IPpHAkBt:bkr9qly) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L52)):*
> ```XML
> }
> 
> export interface AnnotatedPredictionValues {
> ```

Optional: You can still make these extend a common interface that defined kind and mesh as required (i remember you saying you want to enforce that they all have the same 'mesh' property.
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 52 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbrXnR7tDGfmgCHyoi:-MJbrXnR7tDGfmgCHyoj:b-elahgh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L52)):*
> ```XML
> }
> 
> export interface AnnotatedPredictionValues {
> ```

Also, why export these interfaces? Are they used outside this file?
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 53 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbqQrY2EsYtvgKxsRl:-MJbqQrY2EsYtvgKxsRm:b-6fugxv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L53)):*
> ```XML
> 
> export interface AnnotatedPredictionValues {
>   kind: 'MediaPipePrediction';
> ```

How is this interface related to the AnnotatedPredictionTensors below? Will a user ever need to differentiate between the two? If so the 'kind' attribute should not have the same value. From my read of the returnTensors option above these should have different values to help the type checker differentiate between the two.
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 236 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbrmBPDWwFevAbeDki:-MJbrmBPDWwFevAbeDkj:bkr9585) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L236)):*
> ```XML
>   private detectionConfidence: number;
> 
>   public kind = 'MediaPipeFaceMesh' as const ;
> ```

curious to understand the "as const" cast? I don't think i've seen that before, what happens without it. Would it be helpful to assign that string to a const and use it above and here?
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 336 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbsiRt32kFNv_vOB6E:-MJbsiRt32kFNv_vOB6F:b4imjh7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L336)):*
> ```XML
>         if (returnTensors) {
>           const annotatedPrediction: AnnotatedPrediction = {
>             kind: 'MediaPipePrediction',
> ```

Optional: Consider extracting this into one const defined somewhere?

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/528)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[face-landmarks-detection/src/types.ts, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbpz2JECIb4H7uo7Og:-MJc4MDmBUGZ1Ns84Bbo:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/types.ts#L26)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Having Package in the name seems a bit odd. how about 'FaceLandMarksDetector'
</blockquote></details>

Done
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 52 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbrXnR7tDGfmgCHyoi:-MJc4X8C654T15L8i_nQ:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L52)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Also, why export these interfaces? Are they used outside this file?
</blockquote></details>

Done
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 53 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbqQrY2EsYtvgKxsRl:-MJc4h6P5bAsKPSr1VqP:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L53)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

How is this interface related to the AnnotatedPredictionTensors below? Will a user ever need to differentiate between the two? If so the 'kind' attribute should not have the same value. From my read of the returnTensors option above these should have different values to help the type checker differentiate between the two.
</blockquote></details>

Done
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 236 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbrmBPDWwFevAbeDki:-MJc59f5-PKzu-J90CwY:b-5mpcti) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L236)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

curious to understand the "as const" cast? I don't think i've seen that before, what happens without it. Would it be helpful to assign that string to a const and use it above and here?
</blockquote></details>

The issue is that without `as const` the value 'MediaPipeFaceMesh' is widened to `string` rather than the particular value of kind in the interface - following the advice given here: https://stackoverflow.com/questions/37978528/typescript-type-string-is-not-assignable-to-type
___
*[face-landmarks-detection/src/mediapipe-facemesh/index.ts, line 336 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-MJbsiRt32kFNv_vOB6E:-MJc919U7tW6hEkzATxk:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/48efed4591fea5f032ceb03e7ec6343c74af9dec/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L336)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Optional: Consider extracting this into one const defined somewhere?
</blockquote></details>

Done

**Review by tafsiri — APPROVED** [review]
Thanks! Looks good.

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/528#-:-MJcNgO-C2Wd9j_qEzx4:bd9pifs)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

**Pull request merged**
