### PR TITLE
Update posenet model and demo

### PR DESCRIPTION
**Pull request by dsmilkov**
- Update posenet and mobilenet model to depend on latest tfjs
- Update posenet demo to depend on the public posenet npm package
- Release new posenet (0.1.1)

Fixes https://github.com/tensorflow/tfjs/issues/323

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/26)

### CODE REVIEW

**Comment by tafsiri** [comment]
:lgtm_strong:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/26#-:-LDrMEwkD_ZkBtSPqg80:b-jbsf8z)*

**Comment by oveddan** [comment]
Thanks for fixing this.  I'm torn about the idea of pointing to the public posenet npm package.

The pro is that it's an easier example for people to follow when they want to develop their own demo, as they can just copy and paste the demo folder into their own application and import posenet the same way.

The con is that when doing updates to the posenet library itself, you can't test the changes with the demos.

IMO the con would make it more challenging to do updates to the posenet library, without adding a lot of automated tests.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/26#-:-LDrN1004cl6lJQH8meq:by1fnif)*

**Comment by dsmilkov** [comment]
Have you used [yalc](https://www.npmjs.com/package/yalc). It works much better than `yarn link`.
Run `yalc push` in the posenet folder to publish posenet locally.
Then run `yalc link \@tensorflow-models/posenet` in the demo directory

Future changes to posenet source code require only `yarn build && yalc push` and re-running the demo.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/26#-:-LDrO2ib85OPU6oY-ZSd:br9tb4b)*

**Comment by oveddan** [comment]
That's great to know, thank you.  

These changes would make it easier for developers to get the demos up and running, as it removes the step of needing to go into the posenet folder and doing `yarn && yarn build` first.

As part of this could you please update the readme in the demos folder to remove the first steps that say you need to go into `posenet` and run `yarn` `yarn build`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/26#-:-LDrPdJk3GUTlMrr08W3:bsyhus5)*

**Comment by dsmilkov** [comment]
Great point. Updated readme

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/26#-:-LDrSEzYCe6iuPQgZPfn:b-ovhgjn)*

**Pull request merged**
