### PR TITLE
 multiple pose bug fix & output visualizations in the image demo

### PR DESCRIPTION
**Pull request by oveddan**
This PR fixes a bug in multi-pose estimation that caused inaccuracies and jitteriness.  
It also adds visualizations of the model outputs to the images demo.

I had been working on a modification to the "coco" demo that allows the outputs used for multiple-pose estimation to be visualized.  This would show the heatmap (in yellow), short-range offsets (in red) and mid-range offset vectors (in blue) for a specific part, with the opacity is determined by the score of the corresponding heatmap point.  Note that the midrange vector origin is the heatmap coordinate + short-range offset.  Here it is on the tennis example, with the left knee selected and an **output stride of 8**:

visualization

These new visualizations above are included as part of the PR.

For details of the multi-pose estimation algorithm, **refer to the research paper [PersonLab: Person Pose Estimation and Instance Segmentation with a Bottom-Up, Part-Based, Geometric Embedding Model](https://arxiv.org/pdf/1803.08225)** and the section `Fast greedy decoding` on which it is based, or the PoseNet [decodeMultiplePoses function](https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/multiPose/decodeMultiplePoses.ts#L117) where it is implemented.

When **turning the output stride up to 32**, the innacuracy issues for multi-pose estimation became clear.   Below, the left image shows the mid-range offsets for the right shoulder, and the right image shows the heatmap and short-range offsets for the right elbow for the backpack image:

badoffsets

As can be seen above, even though the displacement vectors for the right shoulder are pointing near the right elbow, and the short-range offset vectors are pointing at the right elbow, the estimated keypoint for the right elbow is way off. 

Essentially what the code was doing is:

```javascript
point = lastKeypoint + midRangeOffset
nearestHeatmapIndex = getNearestHeatmapIndexAtPoint(point)
offsetVector = getOffsetVectorAtIndex(nearestHeatmapIndex)

estimatedKeypoint =  lastKeypoint + midRangeOffset + offsetVector
```

What this means is essentially the short range's offset was considered to have an origin at the end of the last displacement vector, instead of from the heatmap point.  When adding the vectors this way, the final estimated keypoint is off from where it should be.

After changing this to have the offset originate from the heatmap point:
```javascript
estimatedKeypoint =  nearestHeatmapIndex * outputStride + offsetVector
```

The results are improved significantly:

fixed

This fix reduces much of the jitteriness and inaccuracies that occured in multi-pose estimation, especially when using the camera.

This PR also:
* For the camera demo, changes it to default to multi-pose since that is now stable, and loads the 0.75 model by default since that gets reasonable real-time performance on my Macbook.
* Ignores `yalc` files in the case someone is developing locally and wants to use yalc to link dependencies to local posenet.
* exports the `poseChain` from multi-pose estimation so that it can be used in the image demo.
* updates the tfjs version of the camera demo to get around a bug [that occured in fromPixels](https://github.com/tensorflow/tfjs/issues/349)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Nice job finding this!

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[posenet/demos/camera.js, line 281 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpeE_9EaQXGJ6NQ4C:-LEkpbeU1t653SxdDrol:bpnu7d7) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/camera.js#L281)):*
> ```JavaScript
> export async function bindPage() {
>   // Load the PoseNet model weights with architecture 0.75
>   const net = await posenet.load(0.75);
> ```

do you want to just make this the default?

---

*[posenet/demos/coco.js, line 50 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpgdiA4oW3NJ1oxDM:-LEkpgdiA4oW3NJ1oxDN:biyq8og) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L50)):*
> ```JavaScript
> ];
> 
> const { partIds, poseChain } = posenet;
> ```

no spaces around {}, are vscode settings okay? here and below

---

*[posenet/demos/coco.js, line 61 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpinX1Hm5BRRPPcVy:-LEkpinX1Hm5BRRPPcVz:b-ts7qnr) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L61)):*
> ```JavaScript
>     poses.forEach((pose) => {
>         if (pose.score >= minPoseConfidence) {
>             if (guiState.showKeypoints)
> ```

use {} even for single line body ifs

---

*[posenet/demos/coco.js, line 107 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpnHn7dmP5g719Qxm:-LEkpnHn7dmP5g719Qxn:bfi2m91) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L107)):*
> ```JavaScript
>     // displacements not used for single pose decoding
>     const showDisplacements = false;
>     const partId = Number(part);
> ```

you can use `+part` to cast to number

---

*[posenet/demos/coco.js, line 109 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpm-m9p8570FrP26d:-LEkpm-m9p8570FrP26e:b-lqgfcz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L109)):*
> ```JavaScript
>     const partId = Number(part);
> 
>     visualizeOutputs(partId, showHeatmap, showOffsets, showDisplacements, canvas.getContext('2d'));
> ```

break 80 chars here and below

---

*[posenet/demos/coco.js, line 156 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpswd9tFQidLzR7M3:-LEkpswd9tFQidLzR7M4:b23shvv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L156)):*
> ```JavaScript
> const childToParentEdges =
>    parentChildrenTuples.reduce((result, [, partId], i) => {
>     if (result[partId])
> ```

use {} here and elsewhere with single body

---

*[posenet/src/keypoints.ts, line 65 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpyQo4MwbO72VE4_V:-LEkpyQo4MwbO72VE4_W:bdxnej8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/src/keypoints.ts#L65)):*
> ```XML
>   ['rightKnee', 'rightAnkle']
> ];
> ```

remove excess breaklines

---

*[posenet/src/multiPose/decodePose.ts, line 87 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkq1wI3NnP2ykbggmT:-LEkq1wI3NnP2ykbggmU:brx08s3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/src/multiPose/decodePose.ts#L87)):*
> ```XML
>   const targetKeypoint = addVectors(
>       {
>         x: displacedPointIndeces.x * outputStride,
> ```

s/Indeces/Indices here and elsewhere

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-:-LEkq5lFAwoZ6Nouhtja:b-f6yryl)*

**Comment by oveddan** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[posenet/demos/camera.js, line 281 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpeE_9EaQXGJ6NQ4C:-LEkvg1I96exIUbGkOmP:bm4cei2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/camera.js#L281)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

do you want to just make this the default?
</blockquote></details>

I think that makes sense.

---

*[posenet/demos/coco.js, line 50 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpgdiA4oW3NJ1oxDM:-LEkvjZ00gaO8IPbXi4d:b-f450dk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L50)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

no spaces around {}, are vscode settings okay? here and below
</blockquote></details>

I'll make sure master has the proper vscode settings then rebase into here, and fix all lint issues, and make sure travis lints the demos folders. As of now, I don't believe it was being checked for the demos folder.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29)*

**Comment by oveddan** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[posenet/demos/coco.js, line 156 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpswd9tFQidLzR7M3:-LEkyg8v8pl3ZUy5ob7O:b-akrdda) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L156)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

use {} here and elsewhere with single body
</blockquote></details>

Do you have a set of eslint rules you recommend, and settings for vscode that would help it autoformat and wrap lines longer than 80 columns for plain javascript files?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29)*

**Comment by nsthorat** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[posenet/demos/coco.js, line 156 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpswd9tFQidLzR7M3:-LEl3MPd1fQCtlNluSG7:bbt2s1z) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L156)):*
<details><summary><i>Previously, oveddan (Dan Oved) wrote…</i></summary><blockquote>

Do you have a set of eslint rules you recommend, and settings for vscode that would help it autoformat and wrap lines longer than 80 columns for plain javascript files?
</blockquote></details>

I think the same settings should apply, you may have to add JS like this:

https://github.com/tensorflow/tfjs-examples/blob/master/.vscode/settings.json#L11

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29)*

**Comment by oveddan** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[posenet/demos/camera.js, line 281 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpeE_9EaQXGJ6NQ4C:-LEl6dtS4PpT3S9b9kA4:bbx111s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/camera.js#L281)):*
<details><summary><i>Previously, oveddan (Dan Oved) wrote…</i></summary><blockquote>

I think that makes sense.
</blockquote></details>

Can we do this in a separate PR?

---

*[posenet/demos/coco.js, line 107 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpnHn7dmP5g719Qxm:-LEl6iVT5uogCtvtEAJt:b-nawtt8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/coco.js#L107)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

you can use `+part` to cast to number
</blockquote></details>

Good to know! I changed this everywhere.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29)*

**Comment by nsthorat** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[posenet/demos/camera.js, line 281 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/29#-LEkpeE_9EaQXGJ6NQ4C:-LEl6ulK3cRy24D58djt:bb7s9xe) ([raw file](https://github.com/tensorflow/tfjs-models/blob/460f5cd970093a5d49d46398baa34567b28353f0/posenet/demos/camera.js#L281)):*
<details><summary><i>Previously, oveddan (Dan Oved) wrote…</i></summary><blockquote>

Can we do this in a separate PR?
</blockquote></details>

yep!

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/29)*

**Pull request merged**
