### PR TITLE
Initialize MediaPipe solution during create_detector.

### PR DESCRIPTION
**Pull request by mhays-google**
Waiting until the first frame to initialize the solution causes
some frames to drop.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712)* status: 0 of 1 approvals obtained (waiting on @mhays-google)

___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bFv8qBHtO9iKUJdsi:-M_bFv8rD4QMWNO8BKiI:bh7tcjd) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L59)):*
> ```
> default:  /
> ```
case 'full':
default:
    modelComplexity = 1;
___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bGBDM3g7XjkXoxjnJ:-M_bGBDM3g7XjkXoxjnK:b-v6e3xg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L152)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   const config = validateModelConfig(modelConfig);
>   const result = new BlazePoseMediaPipeDetector(config);
>   await result.initialize();
>   return result;
> ```
</details>

Why can't this be implemented in load?

**Review by mhays-google — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bFv8qBHtO9iKUJdsi:-M_bIdfE4jVBaF6-hhWJ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L59)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> default:  /
> ```
case 'full':
default:
    modelComplexity = 1;
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bGBDM3g7XjkXoxjnJ:-M_bH87r3YmQ86dOIo37:bkdsv7e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L152)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>   const config = validateModelConfig(modelConfig);
>   const result = new BlazePoseMediaPipeDetector(config);
>   await result.initialize();
>   return result;
> ```
Why can't this be implemented in load?
</blockquote></details>

To expose it in load, I need to add a new method to an exported class.  But there is no need -- the only method that is needed is the factore.

This antipattern is called `leaky interface.`. The fix is to expose only the method that is needed.  TBH, all of the detectors should only expose the single factory method instead of the entire thing.

**Review by mhays-google — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bGBDM3g7XjkXoxjnJ:-M_bIlvU9ZWPY89jzkm9:b-xsln0a) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L152)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

To expose it in load, I need to add a new method to an exported class.  But there is no need -- the only method that is needed is the factore.

This antipattern is called `leaky interface.`. The fix is to expose only the method that is needed.  TBH, all of the detectors should only expose the single factory method instead of the entire thing.

</blockquote></details>

"Leaky Abstraction" -- not "Leaky interface."  ;-)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mhays-google)

___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bGBDM3g7XjkXoxjnJ:-M_bLGsY0qFeymIeh7Jz:b3ndas3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L152)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

"Leaky Abstraction" -- not "Leaky interface."  ;-)
</blockquote></details>

Got it. Sounds good. As discussed offline, let's refactor to this pattern for all sub detector class in a follow up PR.

**Review by mhays-google — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[pose-detection/src/blazepose_mediapipe/detector.ts, line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-M_bGBDM3g7XjkXoxjnJ:-M_bMhKL3T-iO5C84CPs:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/cd983efdc1529f88153f661df9b86d07d737389f/pose-detection/src/blazepose_mediapipe/detector.ts#L152)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Got it. Sounds good. As discussed offline, let's refactor to this pattern for all sub detector class in a follow up PR.
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
LGTM. Thank you Michael!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/712#-:-M_bMrYW5MdQ5oEO73-a:b-gsdj50)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
