### PR TITLE
Add external sources as option

### PR DESCRIPTION
**Pull request by ybigus**
I am using @tensorflow-models/handpose library in my project and needed an option to use private CDN for models.
This PR introduces an optional object for the load method, so users could specify other than TFHub sources.
Proposed object signature is:
```
    {
        fromExternalStorage: {
            handdetectorModelUrl: 'https://cdn.xxxx.com/tf-models/handdetector/model.json',
            handskeletonModelUrl: 'https://cdn.xxxx.com/tf-models/handskeleton/model.json',
            anchorsUrl: 'https://cdn.xxxx.com/tf-models/handskeleton/anchors.json',
            fromTFHub: false
        }
    }
```

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/582)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the contribution! This is useful for others with similar need, please see my comments below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-:-MT3lnGLAagXt0aptpRK:bexiag0)* status: 0 of 1 approvals obtained (waiting on @ybigus)

___
*[handpose/README.md, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-MT3ky9XEZvKg0rMF_aW:-MT3ky9XEZvKg0rMF_aX:b-6enoos) ([raw file](https://github.com/tensorflow/tfjs-models/blob/21786085b953a7948f8ba6fbb9ef2f163be9752d/handpose/README.md#L111)):*
> ```Markdown
> `handpose.load()` takes a configuration object with the following properties:
> 
> * **fromExternalStorage** optional object with paths for **handskeletonModelUrl**, **handdetectorModelUrl**, **anchorsUrl**
> ```

instead of call fromExternalStorage, use modelUrls to be consistent with other models  https://github.com/tensorflow/tfjs-models/blob/master/coco-ssd/src/index.ts#L47
Please also declare an interface that defines this structure, you can use it as type for load method signature.
___
*[handpose/src/index.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-MT3lIqiAZMPYWGKMqNQ:-MT3lIqiAZMPYWGKMqNR:bty5a6d) ([raw file](https://github.com/tensorflow/tfjs-models/blob/21786085b953a7948f8ba6fbb9ef2f163be9752d/handpose/src/index.ts#L34)):*
> ```XML
> 
> // Load the mesh detector model.
> async function loadHandPoseModel(modelPath: string, fromTFHub: boolean) {
> ```

call modelUrl to be more precise
___
*[handpose/src/index.ts, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-MT3lLqW4pIpDT86Y_1_:-MT3lLqW4pIpDT86Y_1a:b-q8lmty) ([raw file](https://github.com/tensorflow/tfjs-models/blob/21786085b953a7948f8ba6fbb9ef2f163be9752d/handpose/src/index.ts#L41)):*
> ```XML
> // of bounding boxes, each of which is assigned a score during prediction. The
> // anchors define the coordinates of these boxes.
> async function loadAnchors(anchorsPath: string) {
> ```

same here, anchorsUrl

**Comment by ybigus** [comment]
@pyu10055 thanks for the suggestions, I just updated methods signatures. The new load method signature is:
To load from custom CDN:
```
handpose.load({
    modelUrl: 'https://cdn.xxxx.com/tf-models/handskeleton/model.json',
    handDetectorModelUrl: 'https://cdn.xxxx.com/tf-models/handdetector/model.json',
    anchorsUrl: 'https://cdn.xxxx.com/tf-models/handskeleton/anchors.json',
    fromTFHub: false,
    detectionConfidence: 0.9
});
```
To load from the TFHub:
```
handpose.load({
    detectionConfidence: 0.9
})
```

**Review by ybigus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/582)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[handpose/README.md, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-MT3ky9XEZvKg0rMF_aW:-MTjOXjZ5XpH9AsGMkZg:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/40e513563ee33d934654087decbdc7b420e3e9d8/handpose/README.md#L111)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

instead of call fromExternalStorage, use modelUrls to be consistent with other models  https://github.com/tensorflow/tfjs-models/blob/master/coco-ssd/src/index.ts#L47
Please also declare an interface that defines this structure, you can use it as type for load method signature.
</blockquote></details>

Done.
___
*[handpose/src/index.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-MT3lIqiAZMPYWGKMqNQ:-MTjObBI0l37wEBHUj7e:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/40e513563ee33d934654087decbdc7b420e3e9d8/handpose/src/index.ts#L34)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

call modelUrl to be more precise
</blockquote></details>

Done.
___
*[handpose/src/index.ts, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/582#-MT3lLqW4pIpDT86Y_1_:-MTjOdPQEZXA11S1LC4v:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/40e513563ee33d934654087decbdc7b420e3e9d8/handpose/src/index.ts#L41)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

same here, anchorsUrl
</blockquote></details>

Done.

**Comment by ybigus** [comment]
hi, @pyu10055 just wondering are you requesting any other changes?

**Comment by ybigus** [comment]
@pyu10055 sorry for disturb, do you require any other changes?

**Comment by ybigus** [comment]
@pyu10055 hey. Requested changes were made. This PR is 6months old. WDYT is it still actual? If no let’s close it, otherwise let me please know if you requesting other changes.

**Pull request closed without merging**
