### PR TITLE
[task] Enable cloudbulid, fix lint errors, and add tests

### PR DESCRIPTION
**Pull request by jinjingforever**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/738)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thanks, the build seems to be failing. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/738#-:-MaUScDI4yqkKsnkLQkJ:bklpmno)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tasks/run_tests.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/738#-MaUFYQLBlecxhYm57fP:-MaUFYQLBlecxhYm57fQ:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs-models/blob/7a80f12d9d1578298e66f4efd2be948d5f8a1db4/tasks/run_tests.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2019 Google LLC. All Rights Reserved.
> ```

2021

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/738)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tasks/run_tests.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/738#-MaUFYQLBlecxhYm57fP:-Mb7lT3qBk91xhFbB3v_:b-p2spfn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6efdf922c71b98ea20a4d07c140f5f0ee3a657b9/tasks/run_tests.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Fixed the test and updated the year. PTAL. Thanks!

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/738)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/738)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tasks/src/tasks/common.ts, line 107 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/738#-Mb9465UCNXQzCKT4HZA:-MbCX3NnBBVS8zOGgdLM:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/8ecae290048712a9bdfe7a013d645d54fb4b2048/tasks/src/tasks/common.ts#L107)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

webgl does not deps on cpu anymore, the cpu impl code is compiled into webgl js files.
</blockquote></details>

Done

**Pull request merged**
